[package]
edition.workspace = true
license.workspace = true
name = "lyra-model-provider"
version.workspace = true

[lib]
doctest = false
name = "lyra_model_provider"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
lyra-api = { workspace = true }
lyra-login = { workspace = true }
lyra-model-provider-info = { workspace = true }
lyra-protocol = { workspace = true }
http = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
