[package]
name = "lyra-utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
lyra-core = { workspace = true }
lyra-model-provider-info = { workspace = true }
lyra-protocol = { workspace = true }

[dev-dependencies]
lyra-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
