import type { LyraDesktopApi } from "../../../shared/desktop-bridge";
import type { GlobalDialogOpenRequest } from "../global-dialog";

export type AiHistorySurfaceProps = {
  readonly desktopApi: LyraDesktopApi | null;
  readonly locale: string;
  readonly title: string;
  readonly newSessionTitle: string;
  readonly newConversationLabel: string;
  readonly openConversationLabel: string;
  readonly renameConversationLabel?: string;
  readonly deleteConversationLabel: string;
  readonly archiveConversationLabel: string;
  readonly unarchiveConversationLabel: string;
  readonly archivedConversationLabel: string;
  readonly archivedProjectLabel: string;
  readonly deleteArchivedConversationTitle: string;
  readonly deleteArchivedConversationDescription: string;
  readonly deleteArchivedConversationConfirm: string;
  readonly deleteArchivedConversationCancel: string;
  readonly profileLabel: string;
  readonly sessionIdLabel: string;
  readonly loadingSessionsLabel: string;
  readonly emptyStateTitle: string;
  readonly emptyStateDescription: string;
  readonly scopeGlobalLabel: string;
  readonly scopeProjectLabel: string;
  readonly noProjectSessionsEmptyLabel: string;
  readonly noProjectsEmptyLabel: string;
  readonly projectSessionCountLabel: string;
  readonly backToProjectsLabel: string;
  readonly projectPathLabel: string;
  readonly threadPreviewEmptyLabel: string;
  readonly previewEmptyTitle: string;
  readonly previewEmptyDescription: string;
  readonly previewLoadingLabel: string;
  readonly richRenderingEnabled?: boolean;
  readonly themeSignature?: string;
  readonly defaultProfileId?: string | null;
  readonly defaultProviderId?: string | null;
  readonly openDialog?: (request: GlobalDialogOpenRequest) => void;
};
