use crate::catalog::common::{
    file_field, map, model, password_field, select_field, text_field, textarea_field, url_field,
};
use crate::profile::types::AiProviderPreset;

pub fn presets() -> Vec<AiProviderPreset> {
    vec![
        AiProviderPreset {
            id: "anthropic".to_string(),
            provider_id: "anthropic".to_string(),
            protocol_id: "anthropic_messages".to_string(),
            label: "Anthropic".to_string(),
            description: "Anthropic Messages API with Claude models.".to_string(),
            section: "recommended".to_string(),
            icon_key: "anthropic".to_string(),
            default_model: "claude-sonnet-4-5".to_string(),
            discovery_mode: "mixed".to_string(),
            capability: "full".to_string(),
            model_discovery_supported: true,
            custom_headers_supported: true,
            custom_models_supported: false,
            connection_fields: vec![url_field("baseUrl", "Base URL", "connection", "https://api.anthropic.com", false)],
            auth_fields: vec![password_field("apiKey", "API Key", "auth", "sk-ant-...", true)],
            default_connection_config: map(&[("baseUrl", "https://api.anthropic.com")]),
            default_auth_config: map(&[]),
            recommended_models: vec![
                model("claude-sonnet-4-5", "Claude Sonnet 4.5", "Balanced Claude coding model."),
                model("claude-opus-4-6", "Claude Opus 4.6", "Anthropic flagship model."),
                model("claude-haiku-4-5", "Claude Haiku 4.5", "Fast Claude model."),
            ],
        },
        AiProviderPreset {
            id: "google_ai".to_string(),
            provider_id: "google_ai".to_string(),
            protocol_id: "gemini_generate_content".to_string(),
            label: "Google AI".to_string(),
            description: "Google AI Studio Gemini API.".to_string(),
            section: "recommended".to_string(),
            icon_key: "google_ai".to_string(),
            default_model: "models/gemini-2.5-pro".to_string(),
            discovery_mode: "mixed".to_string(),
            capability: "full".to_string(),
            model_discovery_supported: true,
            custom_headers_supported: false,
            custom_models_supported: false,
            connection_fields: vec![url_field("baseUrl", "Base URL", "connection", "https://generativelanguage.googleapis.com/v1beta", false)],
            auth_fields: vec![password_field("apiKey", "API Key", "auth", "AIza...", true)],
            default_connection_config: map(&[("baseUrl", "https://generativelanguage.googleapis.com/v1beta")]),
            default_auth_config: map(&[]),
            recommended_models: vec![
                model("models/gemini-2.5-pro", "Gemini 2.5 Pro", "High-end Gemini model."),
                model("models/gemini-2.5-flash", "Gemini 2.5 Flash", "Fast Gemini model."),
                model("models/gemini-2.0-flash", "Gemini 2.0 Flash", "Lower-latency Gemini model."),
            ],
        },
        AiProviderPreset {
            id: "vertex_ai".to_string(),
            provider_id: "vertex_ai".to_string(),
            protocol_id: "gemini_generate_content".to_string(),
            label: "Vertex AI".to_string(),
            description: "Vertex AI Gemini preset with service-account auth fields and static model presets.".to_string(),
            section: "all".to_string(),
            icon_key: "vertex_ai".to_string(),
            default_model: "gemini-2.5-pro".to_string(),
            discovery_mode: "static".to_string(),
            capability: "static".to_string(),
            model_discovery_supported: false,
            custom_headers_supported: false,
            custom_models_supported: false,
            connection_fields: vec![
                text_field("projectId", "Project ID", "connection", "my-gcp-project", true),
                text_field("region", "Region", "connection", "us-central1", true),
            ],
            auth_fields: vec![
                file_field("serviceAccountFile", "Service Account File", "auth", "/path/to/service-account.json"),
                textarea_field("serviceAccountJson", "Service Account JSON", "auth", "{\n  \"type\": \"service_account\"\n}", false),
            ],
            default_connection_config: map(&[("projectId", ""), ("region", "us-central1")]),
            default_auth_config: map(&[("serviceAccountFile", "")]),
            recommended_models: vec![
                model("gemini-2.5-pro", "Gemini 2.5 Pro", "Vertex Gemini flagship model."),
                model("gemini-2.5-flash", "Gemini 2.5 Flash", "Vertex Gemini fast model."),
            ],
        },
        AiProviderPreset {
            id: "amazon_bedrock".to_string(),
            provider_id: "amazon_bedrock".to_string(),
            protocol_id: "bedrock_converse".to_string(),
            label: "Amazon Bedrock".to_string(),
            description: "Amazon Bedrock Converse preset with signed runtime support and static model presets.".to_string(),
            section: "all".to_string(),
            icon_key: "amazon_bedrock".to_string(),
            default_model: "anthropic.claude-3-5-sonnet-20241022-v2:0".to_string(),
            discovery_mode: "static".to_string(),
            capability: "static".to_string(),
            model_discovery_supported: false,
            custom_headers_supported: false,
            custom_models_supported: false,
            connection_fields: vec![
                text_field("region", "Region", "connection", "us-east-1", true),
                url_field("endpointOverride", "Endpoint Override", "connection", "https://bedrock-runtime.us-east-1.amazonaws.com", false),
            ],
            auth_fields: vec![
                select_field(
                    "authMethod",
                    "Authentication Method",
                    "auth",
                    &[
                        ("named_profile", "Named Profile"),
                        ("static_credentials", "Static Credentials"),
                        ("api_key", "Bedrock API Key"),
                    ],
                ),
                text_field("profile", "AWS Profile", "auth", "default", false),
                text_field("accessKeyId", "Access Key ID", "auth", "AKIA...", false),
                password_field("secretAccessKey", "Secret Access Key", "auth", "...", false),
                password_field("sessionToken", "Session Token", "auth", "...", false),
                password_field("apiKey", "Bedrock API Key", "auth", "...", false),
            ],
            default_connection_config: map(&[("region", "us-east-1"), ("endpointOverride", "")]),
            default_auth_config: map(&[("authMethod", "named_profile"), ("profile", "default")]),
            recommended_models: vec![
                model("anthropic.claude-3-5-sonnet-20241022-v2:0", "Claude 3.5 Sonnet", "Popular Bedrock Claude preset."),
                model("us.anthropic.claude-3-7-sonnet-20250219-v1:0", "Claude 3.7 Sonnet", "Bedrock Claude reasoning preset."),
                model("amazon.nova-pro-v1:0", "Nova Pro", "Amazon Nova preset."),
            ],
        },
    ]
}
