[package]
name = "lyra-agent-core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[features]
jemalloc = []
jemalloc-prof = []
session-json = []
pdf = []

[dependencies]
anyhow.workspace = true
chrono = { workspace = true, features = ["clock", "serde"] }
lyra-agent-api.workspace = true
lyra-agent-runtime.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = { workspace = true }
