[package]
name = "lyra-agent-core"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
async-trait.workspace = true
bytes.workspace = true
chrono = { workspace = true, features = ["clock", "serde"] }
futures = { workspace = true, features = ["executor"] }
once_cell.workspace = true
reqwest = { workspace = true, features = ["json", "stream", "rustls-tls"] }
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "sync"] }
uuid = { workspace = true, features = ["v4", "serde"] }
