// build.rs — compile-time embed of curated DESIGN.md design references.
//
// Walks assets/design-md/<brand>/DESIGN.md, extracts the YAML frontmatter
// `description` field for the index, and generates OUT_DIR/design_catalog.rs
// containing a static slice of DesignEntry structs with embedded content.
//
// We read file content at build time and emit it as raw string literals (r#"..."#)
// instead of using include_str!(), because include_str! paths inside an include!()'d
// generated file resolve relative to OUT_DIR, not relative to the source file
// that does the include!().

use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let design_dir = manifest_dir.join("assets/design-md");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let catalog_path = out_dir.join("design_catalog.rs");

    println!("cargo:rerun-if-changed=assets/design-md");

    // Each entry: (brand, description, full DESIGN.md content)
    let mut entries: Vec<(String, String, String)> = Vec::new();

    if design_dir.exists() {
        let mut brands: Vec<_> = fs::read_dir(&design_dir)
            .expect("failed to read assets/design-md directory")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .collect();
        brands.sort_by_key(|e| e.file_name());

        for entry in &brands {
            let brand = entry.file_name().to_string_lossy().to_string();
            let design_md = entry.path().join("DESIGN.md");
            if !design_md.exists() {
                continue;
            }

            let content = fs::read_to_string(&design_md).unwrap_or_default();
            let description = extract_description(&content).unwrap_or_default();
            entries.push((brand, description, content));
        }
    }

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs — do not edit.\n\n");
    output.push_str("pub(crate) struct DesignEntry {\n");
    output.push_str("    pub brand: &'static str,\n");
    output.push_str("    pub description: &'static str,\n");
    output.push_str("    pub content: &'static str,\n");
    output.push_str("}\n\n");
    output.push_str("pub(crate) static DESIGN_CATALOG: &[DesignEntry] = &[\n");

    for (brand, description, content) in &entries {
        let desc_escaped = escape_rust_string(description);
        let brand_escaped = escape_rust_string(brand);
        // Use raw string literal r#"..."# for content (DESIGN.md may contain " and #)
        // If content contains "#, bump the # count
        let hash_count = needed_hash_count(content);
        let content_literal = format!("r{0}\"{1}\"{0}", "#".repeat(hash_count), content);
        output.push_str(&format!(
            "    DesignEntry {{ brand: \"{brand_escaped}\", description: \"{desc_escaped}\", content: {content_literal} }},\n"
        ));
    }

    output.push_str("];\n");

    fs::write(&catalog_path, output).expect("failed to write design_catalog.rs");

    eprintln!("design_catalog: {} entries", entries.len());
}

/// Escape a string for a regular Rust string literal ("...").
fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Find the minimum number of # needed for a raw string literal r#"..."#
/// so that the content does not contain the closing sequence "#.
fn needed_hash_count(content: &str) -> usize {
    let mut max_seq = 0;
    let mut current = 0;
    for ch in content.chars() {
        if ch == '#' {
            current += 1;
            if current > max_seq {
                max_seq = current;
            }
        } else {
            current = 0;
        }
    }
    // Need at least max_seq+1 # to avoid the closing "# sequence
    max_seq + 1
}

/// Extract the `description` value from YAML frontmatter.
/// Handles both quoted and unquoted values, single-line only.
fn extract_description(content: &str) -> Option<String> {
    let in_frontmatter = content.trim_start().starts_with("---");
    if !in_frontmatter {
        return None;
    }

    let lines: Vec<&str> = content.lines().collect();
    let mut in_fm = false;
    for line in &lines {
        let trimmed = line.trim();
        if trimmed == "---" {
            if in_fm {
                break;
            }
            in_fm = true;
            continue;
        }
        if !in_fm {
            continue;
        }
        if let Some(rest) = trimmed.strip_prefix("description:") {
            let value = rest.trim();
            let value = value
                .strip_prefix('"')
                .and_then(|v| v.strip_suffix('"'))
                .unwrap_or(value);
            let value = value
                .strip_prefix('\'')
                .and_then(|v| v.strip_suffix('\''))
                .unwrap_or(value);
            return Some(value.to_string());
        }
    }
    None
}
