import type { WorkbenchThemeVars } from "./types";

export const WORKBENCH_SEMANTIC_TOKENS = {
  "--lyra-shell-titlebar-h": "var(--lyra-control-h-34)",
  "--lyra-shell-browser-tabbar-h": "var(--lyra-control-h-34)",
  "--lyra-shell-terminal-tabbar-h": "var(--lyra-control-h-34)",
  "--lyra-shell-panel-pad-x": "var(--lyra-space-14)",
  "--lyra-shell-panel-pad-y": "var(--lyra-space-12)",
  "--lyra-shell-section-gap": "var(--lyra-space-14)",

  "--lyra-control-h-compact": "var(--lyra-control-h-28)",
  "--lyra-control-h-default": "var(--lyra-control-h-32)",
  "--lyra-control-h-prominent": "var(--lyra-control-h-40)",
  "--lyra-control-icon-size-sm": "var(--lyra-icon-size-14)",
  "--lyra-control-icon-size-md": "var(--lyra-icon-size-16)",
  "--lyra-control-radius-compact": "var(--lyra-radius-6)",
  "--lyra-control-radius-default": "var(--lyra-radius-8)",
  "--lyra-control-radius-pill": "var(--lyra-radius-pill)",
  "--lyra-control-pad-x-compact": "var(--lyra-space-8)",
  "--lyra-control-pad-x-default": "var(--lyra-space-10)",
  "--lyra-control-gap-inline": "var(--lyra-space-6)",

  "--lyra-list-row-h-compact": "var(--lyra-control-h-28)",
  "--lyra-list-row-h-default": "var(--lyra-control-h-36)",
  "--lyra-list-row-gap": "var(--lyra-space-8)",
  "--lyra-list-row-pad-x": "var(--lyra-space-10)",
  "--lyra-list-row-pad-y": "var(--lyra-space-10)",

  "--lyra-surface-radius-sm": "var(--lyra-radius-8)",
  "--lyra-surface-radius-md": "var(--lyra-radius-10)",
  "--lyra-surface-radius-lg": "var(--lyra-radius-12)",
  "--lyra-dialog-pad": "var(--lyra-space-16)",
  "--lyra-dialog-max-w": "560px",
  "--lyra-card-pad": "var(--lyra-space-12)",
  "--lyra-surface-gap": "var(--lyra-space-14)",

  "--lyra-tab-h": "var(--lyra-shell-browser-tabbar-h)",
  "--lyra-tab-radius": "var(--lyra-radius-8)",
  "--lyra-tab-pad-x": "var(--lyra-space-10)",
  "--lyra-tab-gap": "var(--lyra-space-8)",
  "--lyra-tab-active-w": "156px",
  "--lyra-tab-collapsed-w": "34px",
  "--lyra-tab-min-w": "118px",
  "--lyra-tab-max-w": "180px",
  "--lyra-tab-active-max-w": "240px",
  "--lyra-tab-nav-slot-w": "32px",

  "--lyra-text-size-caption": "var(--lyra-text-size-11)",
  "--lyra-text-size-meta": "var(--lyra-text-size-12)",
  "--lyra-text-size-body": "var(--lyra-text-size-13)",
  "--lyra-text-size-body-strong": "var(--lyra-text-size-14)",
  "--lyra-text-size-title-sm": "var(--lyra-text-size-16)",
  "--lyra-text-size-title-md": "var(--lyra-text-size-20)",
  "--lyra-text-line-caption": "var(--lyra-text-line-16)",
  "--lyra-text-line-body": "var(--lyra-text-line-20)",
  "--lyra-text-line-title": "var(--lyra-text-line-24)",

  "--lyra-optical-icon-y-nudge": "-1px",
  "--lyra-optical-caret-y-nudge": "-1px",
  "--lyra-optical-pill-content-x": "var(--lyra-space-10)",
  "--lyra-optical-tab-top-accent-h": "var(--lyra-stroke-emphasis)",

  "--lyra-size-titlebar-h": "var(--lyra-shell-titlebar-h)",
  "--lyra-size-browser-tab-h": "var(--lyra-shell-browser-tabbar-h)",
  "--lyra-size-terminal-tab-h": "var(--lyra-shell-terminal-tabbar-h)",
  "--lyra-size-icon-button-w": "var(--lyra-control-h-26)",
  "--lyra-size-icon-button-h": "var(--lyra-control-h-22)",
  "--lyra-size-browser-nav-slot": "var(--lyra-tab-nav-slot-w)",
  "--lyra-size-browser-pill-h": "var(--lyra-control-h-52)",
  "--lyra-size-browser-pill-compact-h": "var(--lyra-control-h-40)",
  "--lyra-size-browser-circle": "var(--lyra-control-h-28)",
  "--lyra-size-browser-shell-max-w": "980px",
  "--lyra-size-results-sidebar-w": "320px",
  "--lyra-size-notification-preview-min-w": "180px",
  "--lyra-size-notification-preview-max-w": "360px"
} satisfies WorkbenchThemeVars;
