import { useMemo } from "react";

import type { createTranslator } from "../i18n";
import { createWorkbenchUiPackOptions } from "../ui-platform";
import type { WorkspaceSurfaceI18nProps } from "./workspace-surface-router";
import {
  createSettingLocaleOptions,
  createSettingSplitOverflowPolicyOptions,
  createSettingSplitThreePaneLayoutOptions,
  createSettingSplitTriggerModeOptions,
  createSettingTerminalThemeOptions,
  createSettingThemeOptions
} from "./service";

type WorkbenchTranslator = ReturnType<typeof createTranslator>;

export const useWorkbenchLabels = (t: WorkbenchTranslator) =>
  useMemo(
    () => ({
      terminal: {
        newTab: t("terminal.newTab"),
        splitHorizontal: t("terminal.splitHorizontal"),
        splitVertical: t("terminal.splitVertical"),
        moveTerminalToTop: t("panel.moveTerminalToTop"),
        moveTerminalToBottom: t("panel.moveTerminalToBottom"),
        closeTab: t("terminal.closeTab"),
        emptyDock: t("terminal.emptyDock"),
        unavailable: t("terminal.unavailable")
      },
      settingsOptions: {
        locale: createSettingLocaleOptions(t),
        theme: createSettingThemeOptions(t),
        uiStyle: createWorkbenchUiPackOptions(t),
        terminalTheme: createSettingTerminalThemeOptions(t),
        splitTriggerMode: createSettingSplitTriggerModeOptions(t),
        splitThreePaneLayout: createSettingSplitThreePaneLayoutOptions(t),
        splitOverflowPolicy: createSettingSplitOverflowPolicyOptions(t),
        systemNotificationMode: [
          { value: "off" as const, label: t("settings.systemNotificationModeOffLabel") },
          {
            value: "background" as const,
            label: t("settings.systemNotificationModeBackgroundLabel")
          },
          { value: "all" as const, label: t("settings.systemNotificationModeAllLabel") }
        ],
        systemNotificationClickBehavior: [
          {
            value: "open_center" as const,
            label: t("settings.systemNotificationClickOpenCenterLabel")
          },
          {
            value: "open_source" as const,
            label: t("settings.systemNotificationClickOpenSourceLabel")
          }
        ],
        linuxCompatProfile: [
          {
            value: "reliable" as const,
            label: t("settings.linuxCompatProfileReliableLabel"),
            description: t("settings.linuxCompatProfileReliableDescription")
          },
          {
            value: "native" as const,
            label: t("settings.linuxCompatProfileNativeLabel"),
            description: t("settings.linuxCompatProfileNativeDescription")
          },
          {
            value: "performance" as const,
            label: t("settings.linuxCompatProfilePerformanceLabel"),
            description: t("settings.linuxCompatProfilePerformanceDescription")
          }
        ],
        searchScope: [
          {
            value: "home" as const,
            label: t("settings.searchScopeHomeLabel"),
            description: t("settings.searchScopeHomeDescription")
          },
          {
            value: "full_system" as const,
            label: t("settings.searchScopeFullSystemLabel"),
            description: t("settings.searchScopeFullSystemDescription")
          },
          {
            value: "workspace" as const,
            label: t("settings.searchScopeWorkspaceLabel"),
            description: t("settings.searchScopeWorkspaceDescription")
          },
          {
            value: "custom" as const,
            label: t("settings.searchScopeCustomLabel"),
            description: t("settings.searchScopeCustomDescription")
          }
        ],
        searchWebEngine: [
          { value: "bing", label: t("settings.searchWebEngineBing") },
          { value: "brave", label: t("settings.searchWebEngineBrave") },
          { value: "duckduckgo", label: t("settings.searchWebEngineDuckDuckGo") },
          { value: "searxng", label: t("settings.searchWebEngineSearxng") }
        ],
        deepSearchBudget: [
          { value: "low" as const, label: t("settings.deepSearchBudgetLowLabel") },
          { value: "medium" as const, label: t("settings.deepSearchBudgetMediumLabel") },
          { value: "high" as const, label: t("settings.deepSearchBudgetHighLabel") }
        ],
        deepSearchLocalOpenBehavior: [
          { value: "open_file" as const, label: t("settings.deepSearchOpenFileLabel") },
          { value: "reveal_in_manager" as const, label: t("settings.deepSearchRevealInManagerLabel") }
        ],
        deepSearchCrawlPolicy: [
          {
            value: "accessibility_only" as const,
            label: t("settings.deepSearchCrawlPolicyAccessibilityOnlyLabel")
          }
        ],
        omniboxNonBrowserSubmitTarget: [
          {
            value: "new_tab" as const,
            label: t("settings.omniboxNonBrowserSubmitTargetNewTabLabel")
          },
          {
            value: "replace_active_tab" as const,
            label: t("settings.omniboxNonBrowserSubmitTargetReplaceActiveLabel")
          }
        ]
      },
      settingsSurface: {
        title: t("settings.pageTitle"),
        aiCategoryLabel: t("settings.aiCategoryLabel"),
        notificationsCategoryLabel: t("settings.notificationsCategoryLabel"),
        linuxCategoryLabel: t("settings.linuxCategoryLabel"),
        languageLabel: t("settings.languageLabel"),
        themeLabel: t("settings.themeLabel"),
        uiStyleLabel: t("settings.uiStyleLabel"),
        uiStyleExternalReloadRequired: t("settings.uiStyleExternalReloadRequired"),
        uiStyleExternalUntrusted: t("settings.uiStyleExternalUntrusted"),
        terminalThemeLabel: t("settings.terminalThemeLabel"),
        splitTriggerModeLabel: t("settings.splitTriggerModeLabel"),
        splitThreePaneLayoutLabel: t("settings.splitThreePaneLayoutLabel"),
        splitOverflowPolicyLabel: t("settings.splitOverflowPolicyLabel"),
        aiRichRenderLabel: t("settings.aiRichRenderLabel"),
        aiRichRenderDescription: t("settings.aiRichRenderDescription"),
        aiRichRenderEnabledLabel: t("settings.aiRichRenderEnabled"),
        aiRichRenderDisabledLabel: t("settings.aiRichRenderDisabled"),
        aiStopBehaviorLabel: t("settings.aiStopBehaviorLabel"),
        aiStopBehaviorDescription: t("settings.aiStopBehaviorDescription"),
        aiStopBehaviorTurnOnlyLabel: t("settings.aiStopBehaviorTurnOnlyLabel"),
        aiStopBehaviorTurnOnlyDescription: t("settings.aiStopBehaviorTurnOnlyDescription"),
        aiStopBehaviorTurnAndBackgroundLabel: t("settings.aiStopBehaviorTurnAndBackgroundLabel"),
        aiStopBehaviorTurnAndBackgroundDescription: t("settings.aiStopBehaviorTurnAndBackgroundDescription"),
        preventSleepLabel: t("settings.preventSleepLabel"),
        preventSleepDescription: t("settings.preventSleepDescription"),
        preventSleepEnabledLabel: t("settings.preventSleepEnabled"),
        preventSleepDisabledLabel: t("settings.preventSleepDisabled"),
        jsReplLabel: t("settings.jsReplLabel"),
        jsReplDescription: t("settings.jsReplDescription"),
        jsReplEnabledLabel: t("settings.jsReplEnabled"),
        jsReplDisabledLabel: t("settings.jsReplDisabled"),
        forceWebPageThemingLabel: t("settings.forceWebPageThemingLabel"),
        forceWebPageThemingDescription: t("settings.forceWebPageThemingDescription"),
        forceWebPageThemingEnabledLabel: t("settings.forceWebPageThemingEnabled"),
        forceWebPageThemingDisabledLabel: t("settings.forceWebPageThemingDisabled"),
        searchCategoryLabel: t("settings.searchCategoryLabel"),
        searchScopeLabel: t("settings.searchScopeLabel"),
        searchCustomRootsLabel: t("settings.searchCustomRootsLabel"),
        searchCustomRootsPlaceholder: t("settings.searchCustomRootsPlaceholder"),
        searchWebEnginesLabel: t("settings.searchWebEnginesLabel"),
        searchSearxngEndpointLabel: t("settings.searchSearxngEndpointLabel"),
        searchDeepBudgetLabel: t("settings.deepSearchDefaultBudgetLabel"),
        deepSearchRestoreViewportLabel: t("settings.deepSearchRestoreViewportLabel"),
        deepSearchLocalOpenBehaviorLabel: t("settings.deepSearchLocalOpenBehaviorLabel"),
        deepSearchSiteExpansionLabel: t("settings.deepSearchSiteExpansionLabel"),
        deepSearchProactiveGuessLabel: t("settings.deepSearchProactiveGuessLabel"),
        deepSearchCrawlPolicyLabel: t("settings.deepSearchCrawlPolicyLabel"),
        searchEnableFuzzyLabel: t("settings.searchEnableFuzzyLabel"),
        searchEnableContentLabel: t("settings.searchEnableContentLabel"),
        searchIncludeHiddenLabel: t("settings.searchIncludeHiddenLabel"),
        searchAutoIndexLabel: t("settings.searchAutoIndexLabel"),
        searchIndexStatusLabel: t("settings.searchIndexStatusLabel"),
        searchRebuildIndexLabel: t("settings.searchRebuildIndexLabel"),
        omniboxNonBrowserSubmitTargetLabel: t("settings.omniboxNonBrowserSubmitTargetLabel"),
        systemNotificationModeLabel: t("settings.systemNotificationModeLabel"),
        systemNotificationModeOffLabel: t("settings.systemNotificationModeOffLabel"),
        systemNotificationModeBackgroundLabel: t("settings.systemNotificationModeBackgroundLabel"),
        systemNotificationModeAllLabel: t("settings.systemNotificationModeAllLabel"),
        systemNotificationClickBehaviorLabel: t("settings.systemNotificationClickBehaviorLabel"),
        systemNotificationClickOpenCenterLabel: t("settings.systemNotificationClickOpenCenterLabel"),
        systemNotificationClickOpenSourceLabel: t("settings.systemNotificationClickOpenSourceLabel"),
        systemNotificationActionsLabel: t("settings.systemNotificationActionsLabel"),
        systemNotificationActionsDescription: t("settings.systemNotificationActionsDescription"),
        systemNotificationActionsEnabled: t("settings.systemNotificationActionsEnabled"),
        systemNotificationActionsDisabled: t("settings.systemNotificationActionsDisabled"),
        linuxCompatProfileLabel: t("settings.linuxCompatProfileLabel"),
        linuxCompatProfileDescription: t("settings.linuxCompatProfileDescription"),
        linuxCompatProfileReliableLabel: t("settings.linuxCompatProfileReliableLabel"),
        linuxCompatProfileReliableDescription: t("settings.linuxCompatProfileReliableDescription"),
        linuxCompatProfileNativeLabel: t("settings.linuxCompatProfileNativeLabel"),
        linuxCompatProfileNativeDescription: t("settings.linuxCompatProfileNativeDescription"),
        linuxCompatProfilePerformanceLabel: t("settings.linuxCompatProfilePerformanceLabel"),
        linuxCompatProfilePerformanceDescription: t("settings.linuxCompatProfilePerformanceDescription"),
        linuxCompatStatusLabel: t("settings.linuxCompatStatusLabel"),
        linuxCompatCurrentStatusLabel: t("settings.linuxCompatCurrentStatusLabel"),
        linuxCompatSystemLabel: t("settings.linuxCompatSystemLabel"),
        linuxCompatDesktopLabel: t("settings.linuxCompatDesktopLabel"),
        linuxCompatGpuLabel: t("settings.linuxCompatGpuLabel"),
        linuxCompatSwitchesLabel: t("settings.linuxCompatSwitchesLabel"),
        linuxCompatWarningsLabel: t("settings.linuxCompatWarningsLabel"),
        linuxCompatExportDiagnosticsLabel: t("settings.linuxCompatExportDiagnosticsLabel"),
        linuxCompatRestartLabel: t("settings.linuxCompatRestartLabel"),
        linuxCompatRestartDescription: t("settings.linuxCompatRestartDescription"),
        linuxCompatRestartNowLabel: t("settings.linuxCompatRestartNowLabel"),
        linuxCompatRestartDialogTitle: t("settings.linuxCompatRestartDialogTitle"),
        linuxCompatRestartDialogDescription: t("settings.linuxCompatRestartDialogDescription"),
        linuxCompatRestartDialogCancel: t("settings.linuxCompatRestartDialogCancel"),
        linuxCompatRecoveryTitle: t("settings.linuxCompatRecoveryTitle"),
        linuxCompatRecoveryDescription: t("settings.linuxCompatRecoveryDescription"),
        linuxCompatDiagnosticsExported: t("settings.linuxCompatDiagnosticsExported"),
        linuxCompatDiagnosticsFailed: t("settings.linuxCompatDiagnosticsFailed")
      },
      settingsAi: {
        categoryLabel: t("settings.aiCategoryLabel"),
        profilesTitle: t("settings.aiProfilesTitle"),
        providerTitle: t("settings.aiProviderTitle"),
        connectionTitle: t("settings.aiConnectionTitle"),
        additionalFieldsTitle: t("settings.aiAdditionalFieldsTitle"),
        addProfile: t("settings.aiAddProfile"),
        editProfile: t("settings.aiEditProfile"),
        saveProfile: t("settings.aiSaveProfile"),
        deleteProfile: t("settings.aiDeleteProfile"),
        cancel: t("settings.aiCancel"),
        profileNameLabel: t("settings.aiProfileNameLabel"),
        profileNamePlaceholder: t("settings.aiProfileNamePlaceholder"),
        urlLabel: t("settings.aiBaseUrlLabel"),
        urlPlaceholder: t("settings.aiBaseUrlPlaceholder"),
        keyLabel: t("settings.aiApiKeyLabel"),
        keyPlaceholder: t("settings.aiApiKeyPlaceholder"),
        modelLabel: t("settings.aiModelLabel"),
        mainModelLabel: t("settings.aiMainModelLabel"),
        modelModeAllLabel: t("settings.aiModelModeAllLabel"),
        modelModeCustomLabel: t("settings.aiModelModeCustomLabel"),
        modelPlaceholder: t("settings.aiModelPlaceholder"),
        modelsHelp: t("settings.aiModelsHelp"),
        headersLabel: t("settings.aiHeadersLabel"),
        headersPlaceholder: t("settings.aiHeadersPlaceholder"),
        emptyTitle: t("settings.aiEmptyTitle"),
        emptyDescription: t("settings.aiEmptyDescription"),
        recommendedSection: t("settings.aiRecommendedSection"),
        allSection: t("settings.aiAllSection"),
        customSection: t("settings.aiCustomSection"),
        secretConfigured: t("settings.aiSecretConfigured"),
        secretMissing: t("settings.aiSecretMissing"),
        noDiscoveredModels: t("settings.aiNoDiscoveredModels"),
        advancedSettingsLabel: t("settings.aiAdvancedSettingsLabel"),
        selectProviderLabel: t("settings.aiSelectProviderLabel"),
        deleteProfileConfirmTitle: t("settings.aiDeleteProfileConfirmTitle"),
        deleteProfileConfirmDescription: t("settings.aiDeleteProfileConfirmDescription"),
        memoryConfigTitle: t("settings.aiMemoryConfigTitle"),
        memoryConfigDescription: t("settings.aiMemoryConfigDescription"),
        memoryConfigPlaceholder: t("settings.aiMemoryConfigPlaceholder"),
        memoryConfigLoad: t("settings.aiMemoryConfigLoad"),
        memoryConfigSave: t("settings.aiMemoryConfigSave"),
        memoryConfigStatusIdle: t("settings.aiMemoryConfigStatusIdle"),
        memoryConfigStatusLoaded: t("settings.aiMemoryConfigStatusLoaded"),
        memoryConfigStatusSaved: t("settings.aiMemoryConfigStatusSaved"),
        memoryConfigStatusInvalidJson: t("settings.aiMemoryConfigStatusInvalidJson")
      },
      fileManager: {
        title: t("files.title"),
        locationHome: t("files.locationHome"),
        locationDesktop: t("files.locationDesktop"),
        locationDocuments: t("files.locationDocuments"),
        locationDownloads: t("files.locationDownloads"),
        downloadManagerTitle: t("files.downloadManagerTitle"),
        locationTrash: t("files.locationTrash"),
        homeSectionFavorites: t("files.homeSectionFavorites"),
        homeSectionLocations: t("files.homeSectionLocations"),
        homeSectionDevices: t("files.homeSectionDevices"),
        homeSectionRecent: t("files.homeSectionRecent"),
        navigationBack: t("files.navigationBack"),
        navigationForward: t("files.navigationForward"),
        navigationUp: t("files.navigationUp"),
        refresh: t("files.refresh"),
        addFavorite: t("files.addFavorite"),
        removeFavorite: t("files.removeFavorite"),
        newFolder: t("files.newFolder"),
        newFile: t("files.newFile"),
        delete: t("files.delete"),
        restore: t("files.restore"),
        emptyTrash: t("files.emptyTrash"),
        noRecentLocations: t("files.noRecentLocations"),
        emptyDirectory: t("files.emptyDirectory"),
        emptyTrashState: t("files.emptyTrashState"),
        noFavorites: t("files.noFavorites"),
        emptyDownloads: t("files.emptyDownloads"),
        loading: t("files.loading"),
        unavailable: t("files.unavailable"),
        diskAvailable: t("files.diskAvailable"),
        diskKindSystem: t("files.diskKindSystem"),
        diskKindLocal: t("files.diskKindLocal"),
        diskKindRemovable: t("files.diskKindRemovable"),
        diskKindExternal: t("files.diskKindExternal"),
        deviceUnmounted: t("files.deviceUnmounted"),
        nameColumn: t("files.nameColumn"),
        locationColumn: t("files.locationColumn"),
        originalLocationColumn: t("files.originalLocationColumn"),
        createPlaceholderFile: t("files.createPlaceholderFile"),
        createPlaceholderDirectory: t("files.createPlaceholderDirectory"),
        createConfirm: t("files.createConfirm"),
        createCancel: t("files.createCancel"),
        contextOpen: t("files.contextOpen"),
        contextMountDevice: t("files.contextMountDevice"),
        contextMoveToTrash: t("files.contextMoveToTrash"),
        contextRestore: t("files.contextRestore"),
        contextEmptyTrash: t("files.contextEmptyTrash"),
        contextEjectDevice: t("files.contextEjectDevice"),
        viewList: t("files.viewList"),
        viewLarge: t("files.viewLarge"),
        downloadAddUrl: t("files.downloadAddUrl"),
        downloadImportClipboard: t("files.downloadImportClipboard"),
        downloadImportExternalBrowser: t("files.downloadImportExternalBrowser"),
        downloadUrlPlaceholder: t("files.downloadUrlPlaceholder"),
        downloadOpenFile: t("files.downloadOpenFile"),
        downloadRevealFile: t("files.downloadRevealFile"),
        downloadPause: t("files.downloadPause"),
        downloadResume: t("files.downloadResume"),
        downloadCancel: t("files.downloadCancel"),
        downloadRetry: t("files.downloadRetry"),
        downloadRemove: t("files.downloadRemove"),
        downloadPauseAll: t("files.downloadPauseAll"),
        downloadResumeAll: t("files.downloadResumeAll"),
        downloadCancelAll: t("files.downloadCancelAll"),
        downloadPriority: t("files.downloadPriority"),
        downloadPriorityLow: t("files.downloadPriorityLow"),
        downloadPriorityNormal: t("files.downloadPriorityNormal"),
        downloadPriorityHigh: t("files.downloadPriorityHigh"),
        downloadStateQueued: t("files.downloadStateQueued"),
        downloadStateDownloading: t("files.downloadStateDownloading"),
        downloadStatePaused: t("files.downloadStatePaused"),
        downloadStateCompleted: t("files.downloadStateCompleted"),
        downloadStateFailed: t("files.downloadStateFailed"),
        downloadStateCanceled: t("files.downloadStateCanceled"),
        downloadSourceBrowser: t("files.downloadSourceBrowser"),
        downloadSourceManual: t("files.downloadSourceManual"),
        downloadConnections: t("files.downloadConnections"),
        downloadUnknownSize: t("files.downloadUnknownSize"),
        downloadSpeedIdle: t("files.downloadSpeedIdle"),
        downloadDurationSeconds: t("files.downloadDurationSeconds"),
        downloadDurationMinutes: t("files.downloadDurationMinutes"),
        downloadDurationHours: t("files.downloadDurationHours"),
        downloadEta: t("files.downloadEta"),
        downloadChecksumPending: t("files.downloadChecksumPending"),
        downloadChecksumVerified: t("files.downloadChecksumVerified"),
        downloadChecksumFailed: t("files.downloadChecksumFailed"),
        downloadSettings: t("files.downloadSettings"),
        downloadSettingsSave: t("files.downloadSettingsSave"),
        downloadSettingsSpeedLimit: t("files.downloadSettingsSpeedLimit"),
        downloadSettingsNoLimit: t("files.downloadSettingsNoLimit"),
        downloadAdvancedOptions: t("files.downloadAdvancedOptions"),
        downloadAdvancedCookie: t("files.downloadAdvancedCookie"),
        downloadAdvancedHeaders: t("files.downloadAdvancedHeaders"),
        downloadAdvancedMirrors: t("files.downloadAdvancedMirrors"),
        downloadAdvancedBtSelectedFiles: t("files.downloadAdvancedBtSelectedFiles"),
        downloadAdvancedBtTrackers: t("files.downloadAdvancedBtTrackers"),
        downloadAdvancedPartialFile: t("files.downloadAdvancedPartialFile"),
        downloadAdvancedChecksumAlgorithm: t("files.downloadAdvancedChecksumAlgorithm"),
        downloadAdvancedChecksumNone: t("files.downloadAdvancedChecksumNone"),
        downloadAdvancedChecksumExpected: t("files.downloadAdvancedChecksumExpected"),
        downloadAdvancedMaxRetries: t("files.downloadAdvancedMaxRetries"),
        downloadAdvancedRetryDelay: t("files.downloadAdvancedRetryDelay"),
        downloadAdvancedProxyMode: t("files.downloadAdvancedProxyMode"),
        downloadAdvancedProxyUrl: t("files.downloadAdvancedProxyUrl"),
        downloadSettingsSchedule: t("files.downloadSettingsSchedule"),
        downloadSettingsScheduleEnabled: t("files.downloadSettingsScheduleEnabled"),
        downloadSettingsScheduleStart: t("files.downloadSettingsScheduleStart"),
        downloadSettingsScheduleEnd: t("files.downloadSettingsScheduleEnd"),
        downloadSettingsScheduleOutsideAction: t("files.downloadSettingsScheduleOutsideAction"),
        downloadSettingsSchedulePause: t("files.downloadSettingsSchedulePause"),
        downloadSettingsScheduleSpeedLimit: t("files.downloadSettingsScheduleSpeedLimit"),
        downloadSettingsScheduleLimit: t("files.downloadSettingsScheduleLimit"),
        downloadSettingsSaveRules: t("files.downloadSettingsSaveRules"),
        downloadSettingsAddSaveRule: t("files.downloadSettingsAddSaveRule"),
        downloadSettingsRemoveSaveRule: t("files.downloadSettingsRemoveSaveRule"),
        downloadSettingsRuleEnabled: t("files.downloadSettingsRuleEnabled"),
        downloadSettingsRuleName: t("files.downloadSettingsRuleName"),
        downloadSettingsRuleDirectory: t("files.downloadSettingsRuleDirectory"),
        downloadSettingsRuleExtensions: t("files.downloadSettingsRuleExtensions"),
        downloadSettingsRuleHosts: t("files.downloadSettingsRuleHosts"),
        downloadSettingsRuleProtocols: t("files.downloadSettingsRuleProtocols"),
        downloadSettingsRuleTags: t("files.downloadSettingsRuleTags"),
        downloadSettingsProxyMode: t("files.downloadSettingsProxyMode"),
        downloadSettingsProxySystem: t("files.downloadSettingsProxySystem"),
        downloadSettingsProxyDirect: t("files.downloadSettingsProxyDirect"),
        downloadSettingsProxyHttp: t("files.downloadSettingsProxyHttp"),
        downloadSettingsProxySocks5: t("files.downloadSettingsProxySocks5"),
        downloadSettingsProxyUrl: t("files.downloadSettingsProxyUrl"),
        downloadSettingsCookie: t("files.downloadSettingsCookie"),
        downloadSettingsHeaders: t("files.downloadSettingsHeaders"),
        downloadSettingsPostProcessing: t("files.downloadSettingsPostProcessing"),
        downloadSettingsAutoExtract: t("files.downloadSettingsAutoExtract"),
        downloadSettingsDeleteArchive: t("files.downloadSettingsDeleteArchive"),
        downloadSettingsDetectSplitArchives: t("files.downloadSettingsDetectSplitArchives"),
        downloadSettingsExtractDirectory: t("files.downloadSettingsExtractDirectory"),
        downloadSettingsBt: t("files.downloadSettingsBt"),
        downloadSettingsBtDht: t("files.downloadSettingsBtDht"),
        downloadSettingsBtPeerExchange: t("files.downloadSettingsBtPeerExchange"),
        downloadSettingsBtLocalPeerDiscovery: t("files.downloadSettingsBtLocalPeerDiscovery"),
        downloadSettingsBtSeedTime: t("files.downloadSettingsBtSeedTime"),
        downloadSettingsBtTrackers: t("files.downloadSettingsBtTrackers"),
        downloadSettingsBtUploadLimit: t("files.downloadSettingsBtUploadLimit"),
        downloadRemoteApi: t("files.downloadRemoteApi"),
        downloadRemoteApiStart: t("files.downloadRemoteApiStart"),
        downloadRemoteApiStop: t("files.downloadRemoteApiStop"),
        downloadRemoteApiRunning: t("files.downloadRemoteApiRunning"),
        downloadRemoteApiStopped: t("files.downloadRemoteApiStopped"),
        downloadRemoteApiHost: t("files.downloadRemoteApiHost"),
        downloadRemoteApiPort: t("files.downloadRemoteApiPort"),
        downloadRemoteApiAllowLan: t("files.downloadRemoteApiAllowLan"),
        downloadRemoteApiToken: t("files.downloadRemoteApiToken"),
        chooserBindProjectLabel: t("files.chooserBindProjectLabel"),
        chooserSelectDirectoryPlaceholder: t("files.chooserSelectDirectoryPlaceholder")
      },
      fileEditor: {
        loading: t("editor.loading"),
        unsupported: t("editor.unsupported"),
        unavailable: t("editor.unavailable"),
        readOnly: t("editor.readOnly"),
        conflict: t("editor.conflict"),
        retry: t("editor.retry"),
        save: t("editor.save"),
        openDiff: t("editor.openDiff"),
        closeDiff: t("editor.closeDiff")
      },
      imageViewer: {
        loading: "Loading image",
        unavailable: "Image viewer unavailable",
        unsupported: "This image format is not supported by native tiling.",
        retry: "Retry",
        fit: "Fit",
        actualSize: "100%",
        zoomIn: "Zoom in",
        zoomOut: "Zoom out",
        reset: "Reset",
        rotateLeft: "Rotate left",
        rotateRight: "Rotate right",
        background: "Background",
        previous: "Previous image",
        next: "Next image",
        nativeTiles: "Native tiles",
        sourceOnly: "Original source",
        metadata: "Metadata"
      },
      fileEditorReview: {
        accept: t("ai.editorWorkAccept"),
        reject: t("ai.editorWorkReject"),
        undo: t("ai.editorWorkUndo"),
        previous: t("ai.editorWorkPrevious"),
        next: t("ai.editorWorkNext"),
        acceptAll: t("ai.editorWorkAcceptAll")
      },
      notificationTopbar: {
        openCenter: t("notification.topbarOpenCenter"),
        openPreview: t("notification.topbarOpenPreview")
      },
      notificationCenter: {
        title: t("notification.centerTitle"),
        listTitle: t("notification.centerListTitle"),
        markAllRead: t("notification.centerMarkAllRead"),
        clearAll: t("notification.centerClearAll"),
        openSource: t("notification.centerOpenSource"),
        sourceFallback: t("notification.centerSourceFallback"),
        unread: t("notification.centerUnread")
      },
      resourceMonitor: {
        title: t("resources.activityMonitorTitle"),
        subtitle: t("resources.activityMonitorSubtitle"),
        pid: t("resources.activityMonitorPid"),
        resources: t("resources.activityMonitorResources"),
        coreGroups: t("resources.activityMonitorCoreGroups"),
        tombstoned: t("resources.activityMonitorTombstoned"),
        generation: t("resources.activityMonitorGeneration"),
        coreSharing: t("resources.activityMonitorCoreSharing"),
        empty: t("resources.activityMonitorEmpty"),
        views: t("resources.activityMonitorViews"),
        state: t("resources.activityMonitorState"),
        kind: t("resources.activityMonitorKind"),
        label: t("resources.activityMonitorLabel"),
        core: t("resources.activityMonitorCore"),
        scopeLyra: t("resources.activityMonitorScopeLyra"),
        scopeAll: t("resources.activityMonitorScopeAll"),
        runtime: t("resources.activityMonitorRuntime"),
        kernel: t("resources.activityMonitorKernel"),
        unifiedLoad: t("resources.activityMonitorUnifiedLoad"),
        cpu: t("resources.activityMonitorCpu"),
        memory: t("resources.activityMonitorMemory"),
        buffers: t("resources.activityMonitorBuffers"),
        disk: t("resources.activityMonitorDisk"),
        network: t("resources.activityMonitorNetwork"),
        gpu: t("resources.activityMonitorGpu"),
        lyra: t("resources.activityMonitorLyra"),
        activities: t("resources.activityMonitorActivities"),
        usage: t("resources.activityMonitorUsage"),
        actions: t("resources.activityMonitorActions"),
        unavailable: t("resources.activityMonitorUnavailable"),
        cores: t("resources.activityMonitorCores"),
        loadAverage: t("resources.activityMonitorLoadAverage"),
        networkReceived: t("resources.activityMonitorNetworkReceived"),
        networkTransmitted: t("resources.activityMonitorNetworkTransmitted"),
        free: t("resources.activityMonitorFree"),
        actionFailed: t("resources.activityMonitorActionFailed"),
        lifecycleStates: {
          foreground: t("resources.lifecycleForeground"),
          visible: t("resources.lifecycleVisible"),
          "hot-hidden": t("resources.lifecycleHotHidden"),
          "warm-suspended": t("resources.lifecycleWarmSuspended"),
          frozen: t("resources.lifecycleFrozen"),
          tombstoned: t("resources.lifecycleTombstoned"),
          restoring: t("resources.lifecycleRestoring"),
          archived: t("resources.lifecycleArchived")
        },
        activityKinds: {
          "lyra-resource": t("resources.activityKindLyraResource"),
          process: t("resources.activityKindProcess"),
          runtime: t("resources.activityKindRuntime")
        },
        activityActions: {
          restart: t("resources.activityActionRestart"),
          kill: t("resources.activityActionKill"),
          suspend: t("resources.activityActionSuspend"),
          resume: t("resources.activityActionResume"),
          inspect: t("resources.activityActionInspect"),
          reveal: t("resources.activityActionReveal")
        }
      },
      workspaceI18n: {
        searchPlaceholder: t("browser.searchPlaceholder"),
        searchActionLabel: t("browser.searchAction"),
        resultsHeading: t("browser.resultsHeading"),
        resultsBlendTitle: t("browser.resultsBlendTitle"),
        resultsEngineOverview: t("browser.resultsEngineOverview"),
        resultsNoResults: t("browser.resultsNoResults"),
        resultsEngineError: t("browser.resultsEngineError"),
        resultsOfficial: t("browser.resultsOfficial"),
        resultsOfficialHomepage: t("browser.resultsOfficialHomepage"),
        resultsOfficialSubsite: t("browser.resultsOfficialSubsite"),
        resultsOfficialDocs: t("browser.resultsOfficialDocs"),
        resultsOfficialLogin: t("browser.resultsOfficialLogin"),
        resultsOfficialDownload: t("browser.resultsOfficialDownload"),
        resultsOfficialSupport: t("browser.resultsOfficialSupport"),
        resultsSourceFilter: t("browser.resultsSourceFilter"),
        resultsAllTab: t("browser.resultsAllTab"),
        resultsWebTab: t("browser.resultsWebTab"),
        resultsLocalTab: t("browser.resultsLocalTab"),
        resultsLocalTitle: t("browser.resultsLocalTitle"),
        resultsLocalPanelTitle: t("browser.resultsLocalPanelTitle"),
        resultsLocalNoMatches: t("browser.resultsLocalNoMatches"),
        resultsLocalSearchingMore: t("browser.resultsLocalSearchingMore"),
        resultsLocalScope: t("browser.resultsLocalScope"),
        resultsLocalScannedFiles: t("browser.resultsLocalScannedFiles"),
        resultsLocalScannedDirs: t("browser.resultsLocalScannedDirs"),
        resultsLocalContentScans: t("browser.resultsLocalContentScans"),
        resultsLocalMatched: t("browser.resultsLocalMatched"),
        resultsLocalIndex: t("browser.resultsLocalIndex"),
        resultsLocalScore: t("browser.resultsLocalScore"),
        resultsLocalLine: t("browser.resultsLocalLine"),
        channelIdle: t("browser.channelIdle"),
        channelLoading: t("browser.channelLoading"),
        channelReady: t("browser.channelReady"),
        channelError: t("browser.channelError"),
        deepSearchToggle: t("browser.deepSearchToggle"),
        deepSearchChip: t("browser.deepSearchChip"),
        deepSearchHeading: t("browser.deepSearchHeading"),
        deepSearchStop: t("browser.deepSearchStop"),
        deepSearchFitView: t("browser.deepSearchFitView"),
        deepSearchResetLayout: t("browser.deepSearchResetLayout"),
        deepSearchLoading: t("browser.deepSearchLoading"),
        deepSearchEmpty: t("browser.deepSearchEmpty"),
        deepSearchOverview: t("browser.deepSearchOverview"),
        deepSearchSelectedNode: t("browser.deepSearchSelectedNode"),
        deepSearchPhase: t("browser.deepSearchPhase"),
        deepSearchBudget: t("browser.deepSearchBudget"),
        deepSearchWebStatus: t("browser.deepSearchWebStatus"),
        deepSearchLocalStatus: t("browser.deepSearchLocalStatus"),
        deepSearchDeduped: t("browser.deepSearchDeduped"),
        deepSearchDerived: t("browser.deepSearchDerived"),
        deepSearchRounds: t("browser.deepSearchRounds"),
        deepSearchOpen: t("browser.deepSearchOpen"),
        deepSearchExpand: t("browser.deepSearchExpand"),
        deepSearchCenter: t("browser.deepSearchCenter"),
        deepSearchNoSelection: t("browser.deepSearchNoSelection"),
        deepSearchAll: t("browser.deepSearchAll"),
        deepSearchSnippet: t("browser.deepSearchSnippet"),
        deepSearchSource: t("browser.deepSearchSource"),
        deepSearchConnectedLinks: t("browser.deepSearchConnectedLinks"),
        deepSearchEdgeFilters: t("browser.deepSearchEdgeFilters"),
        deepSearchDirection: t("browser.deepSearchDirection"),
        deepSearchIncoming: t("browser.deepSearchIncoming"),
        deepSearchOutgoing: t("browser.deepSearchOutgoing"),
        deepSearchBoth: t("browser.deepSearchBoth"),
        deepSearchDiscovered: t("browser.deepSearchDiscovered"),
        deepSearchExpanded: t("browser.deepSearchExpanded"),
        deepSearchRelated: t("browser.deepSearchRelated"),
        deepSearchHostsSubdomain: t("browser.deepSearchHostsSubdomain"),
        deepSearchContainsPage: t("browser.deepSearchContainsPage"),
        deepSearchLineage: t("browser.deepSearchLineage"),
        deepSearchAlternateLinks: t("browser.deepSearchAlternateLinks"),
        deepSearchRevealInManager: t("browser.deepSearchRevealInManager"),
        deepSearchMatchKind: t("browser.deepSearchMatchKind"),
        deepSearchLine: t("browser.deepSearchLine"),
        deepSearchSharedTerms: t("browser.deepSearchSharedTerms"),
        deepSearchDomain: t("browser.deepSearchDomain"),
        deepSearchSubdomain: t("browser.deepSearchSubdomain"),
        deepSearchPage: t("browser.deepSearchPage"),
        deepSearchVerified: t("browser.deepSearchVerified"),
        deepSearchGuessed: t("browser.deepSearchGuessed"),
        deepSearchDiscoveredBy: t("browser.deepSearchDiscoveredBy"),
        deepSearchVerificationScore: t("browser.deepSearchVerificationScore"),
        deepSearchGuessedDomains: t("browser.deepSearchGuessedDomains"),
        deepSearchVerifiedDomains: t("browser.deepSearchVerifiedDomains"),
        deepSearchSubdomains: t("browser.deepSearchSubdomains"),
        deepSearchVisitedPages: t("browser.deepSearchVisitedPages"),
        deepSearchQueuedPages: t("browser.deepSearchQueuedPages"),
        deepSearchDroppedPages: t("browser.deepSearchDroppedPages"),
        deepSearchSiteExpansionStatus: t("browser.deepSearchSiteExpansionStatus")
      } satisfies WorkspaceSurfaceI18nProps,
    }),
    [t]
  );

export type WorkbenchLabels = ReturnType<typeof useWorkbenchLabels>;
