import { useMemo } from "react";

import type { createTranslator } from "../i18n";
import type { SoftwareStoreBuiltinApp } from "../software-store";
import { createWorkbenchUiPackOptions } from "../ui-platform";
import type { WorkspaceSurfaceI18nProps } from "./workspace-surface-router";
import {
  createSettingLocaleOptions,
  createSettingSplitOverflowPolicyOptions,
  createSettingSplitThreePaneLayoutOptions,
  createSettingSplitTriggerModeOptions,
  createSettingThemeOptions
} from "./service";

type WorkbenchTranslator = ReturnType<typeof createTranslator>;

export const useWorkbenchLabels = (t: WorkbenchTranslator) =>
  useMemo(
    () => ({
      terminal: {
        newTab: t("terminal.newTab"),
        newTabWithProfile: t("terminal.newTabWithProfile"),
        profile: t("terminal.profile"),
        splitHorizontal: t("terminal.splitHorizontal"),
        splitVertical: t("terminal.splitVertical"),
        moveTerminalToTop: t("panel.moveTerminalToTop"),
        moveTerminalToBottom: t("panel.moveTerminalToBottom"),
        closeTab: t("terminal.closeTab"),
        renameTab: t("terminal.renameTab"),
        pinTab: t("terminal.pinTab"),
        unpinTab: t("terminal.unpinTab"),
        favoriteTab: t("terminal.favoriteTab"),
        unfavoriteTab: t("terminal.unfavoriteTab"),
        exited: t("terminal.exited"),
        emptyDock: t("terminal.emptyDock"),
        unavailable: t("terminal.unavailable")
      },
      settingsOptions: {
        locale: createSettingLocaleOptions(t),
        theme: createSettingThemeOptions(t),
        uiStyle: createWorkbenchUiPackOptions(t),
        splitTriggerMode: createSettingSplitTriggerModeOptions(t),
        splitThreePaneLayout: createSettingSplitThreePaneLayoutOptions(t),
        splitOverflowPolicy: createSettingSplitOverflowPolicyOptions(t),
        systemNotificationMode: [
          { value: "off" as const, label: t("settings.systemNotificationModeOffLabel") },
          {
            value: "background" as const,
            label: t("settings.systemNotificationModeBackgroundLabel")
          },
          { value: "all" as const, label: t("settings.systemNotificationModeAllLabel") }
        ],
        systemNotificationClickBehavior: [
          {
            value: "open_center" as const,
            label: t("settings.systemNotificationClickOpenCenterLabel")
          },
          {
            value: "open_source" as const,
            label: t("settings.systemNotificationClickOpenSourceLabel")
          }
        ],
        linuxCompatProfile: [
          {
            value: "reliable" as const,
            label: t("settings.linuxCompatProfileReliableLabel"),
            description: t("settings.linuxCompatProfileReliableDescription")
          },
          {
            value: "native" as const,
            label: t("settings.linuxCompatProfileNativeLabel"),
            description: t("settings.linuxCompatProfileNativeDescription")
          },
          {
            value: "performance" as const,
            label: t("settings.linuxCompatProfilePerformanceLabel"),
            description: t("settings.linuxCompatProfilePerformanceDescription")
          }
        ],
        searchScope: [
          {
            value: "home" as const,
            label: t("settings.searchScopeHomeLabel"),
            description: t("settings.searchScopeHomeDescription")
          },
          {
            value: "full_system" as const,
            label: t("settings.searchScopeFullSystemLabel"),
            description: t("settings.searchScopeFullSystemDescription")
          },
          {
            value: "workspace" as const,
            label: t("settings.searchScopeWorkspaceLabel"),
            description: t("settings.searchScopeWorkspaceDescription")
          },
          {
            value: "custom" as const,
            label: t("settings.searchScopeCustomLabel"),
            description: t("settings.searchScopeCustomDescription")
          }
        ],
        searchWebEngine: [
          { value: "bing", label: t("settings.searchWebEngineBing") },
          { value: "brave", label: t("settings.searchWebEngineBrave") },
          { value: "duckduckgo", label: t("settings.searchWebEngineDuckDuckGo") },
          { value: "searxng", label: t("settings.searchWebEngineSearxng") }
        ],
        deepSearchBudget: [
          { value: "low" as const, label: t("settings.deepSearchBudgetLowLabel") },
          { value: "medium" as const, label: t("settings.deepSearchBudgetMediumLabel") },
          { value: "high" as const, label: t("settings.deepSearchBudgetHighLabel") }
        ],
        deepSearchLocalOpenBehavior: [
          { value: "open_file" as const, label: t("settings.deepSearchOpenFileLabel") },
          { value: "reveal_in_manager" as const, label: t("settings.deepSearchRevealInManagerLabel") }
        ],
        deepSearchCrawlPolicy: [
          {
            value: "accessibility_only" as const,
            label: t("settings.deepSearchCrawlPolicyAccessibilityOnlyLabel")
          }
        ],
        omniboxNonBrowserSubmitTarget: [
          {
            value: "new_tab" as const,
            label: t("settings.omniboxNonBrowserSubmitTargetNewTabLabel")
          },
          {
            value: "replace_active_tab" as const,
            label: t("settings.omniboxNonBrowserSubmitTargetReplaceActiveLabel")
          }
        ]
      },
      settingsSurface: {
        title: t("settings.pageTitle"),
        aiCategoryLabel: t("settings.aiCategoryLabel"),
        notificationsCategoryLabel: t("settings.notificationsCategoryLabel"),
        linuxCategoryLabel: t("settings.linuxCategoryLabel"),
        languageLabel: t("settings.languageLabel"),
        themeLabel: t("settings.themeLabel"),
        uiStyleLabel: t("settings.uiStyleLabel"),
        uiStyleExternalReloadRequired: t("settings.uiStyleExternalReloadRequired"),
        uiStyleExternalUntrusted: t("settings.uiStyleExternalUntrusted"),
        splitTriggerModeLabel: t("settings.splitTriggerModeLabel"),
        splitThreePaneLayoutLabel: t("settings.splitThreePaneLayoutLabel"),
        splitOverflowPolicyLabel: t("settings.splitOverflowPolicyLabel"),
        aiRichRenderLabel: t("settings.aiRichRenderLabel"),
        aiRichRenderDescription: t("settings.aiRichRenderDescription"),
        aiRichRenderEnabledLabel: t("settings.aiRichRenderEnabled"),
        aiRichRenderDisabledLabel: t("settings.aiRichRenderDisabled"),
        aiStopBehaviorLabel: t("settings.aiStopBehaviorLabel"),
        aiStopBehaviorDescription: t("settings.aiStopBehaviorDescription"),
        aiStopBehaviorTurnOnlyLabel: t("settings.aiStopBehaviorTurnOnlyLabel"),
        aiStopBehaviorTurnOnlyDescription: t("settings.aiStopBehaviorTurnOnlyDescription"),
        aiStopBehaviorTurnAndBackgroundLabel: t("settings.aiStopBehaviorTurnAndBackgroundLabel"),
        aiStopBehaviorTurnAndBackgroundDescription: t("settings.aiStopBehaviorTurnAndBackgroundDescription"),
        preventSleepLabel: t("settings.preventSleepLabel"),
        preventSleepDescription: t("settings.preventSleepDescription"),
        preventSleepEnabledLabel: t("settings.preventSleepEnabled"),
        preventSleepDisabledLabel: t("settings.preventSleepDisabled"),
        jsReplLabel: t("settings.jsReplLabel"),
        jsReplDescription: t("settings.jsReplDescription"),
        jsReplEnabledLabel: t("settings.jsReplEnabled"),
        jsReplDisabledLabel: t("settings.jsReplDisabled"),
        forceWebPageThemingLabel: t("settings.forceWebPageThemingLabel"),
        forceWebPageThemingDescription: t("settings.forceWebPageThemingDescription"),
        forceWebPageThemingEnabledLabel: t("settings.forceWebPageThemingEnabled"),
        forceWebPageThemingDisabledLabel: t("settings.forceWebPageThemingDisabled"),
        searchCategoryLabel: t("settings.searchCategoryLabel"),
        searchScopeLabel: t("settings.searchScopeLabel"),
        searchCustomRootsLabel: t("settings.searchCustomRootsLabel"),
        searchCustomRootsPlaceholder: t("settings.searchCustomRootsPlaceholder"),
        searchWebEnginesLabel: t("settings.searchWebEnginesLabel"),
        searchSearxngEndpointLabel: t("settings.searchSearxngEndpointLabel"),
        searchDeepBudgetLabel: t("settings.deepSearchDefaultBudgetLabel"),
        deepSearchRestoreViewportLabel: t("settings.deepSearchRestoreViewportLabel"),
        deepSearchLocalOpenBehaviorLabel: t("settings.deepSearchLocalOpenBehaviorLabel"),
        deepSearchSiteExpansionLabel: t("settings.deepSearchSiteExpansionLabel"),
        deepSearchProactiveGuessLabel: t("settings.deepSearchProactiveGuessLabel"),
        deepSearchCrawlPolicyLabel: t("settings.deepSearchCrawlPolicyLabel"),
        searchEnableFuzzyLabel: t("settings.searchEnableFuzzyLabel"),
        searchEnableContentLabel: t("settings.searchEnableContentLabel"),
        searchIncludeHiddenLabel: t("settings.searchIncludeHiddenLabel"),
        searchAutoIndexLabel: t("settings.searchAutoIndexLabel"),
        searchIndexStatusLabel: t("settings.searchIndexStatusLabel"),
        searchRebuildIndexLabel: t("settings.searchRebuildIndexLabel"),
        omniboxNonBrowserSubmitTargetLabel: t("settings.omniboxNonBrowserSubmitTargetLabel"),
        systemNotificationModeLabel: t("settings.systemNotificationModeLabel"),
        systemNotificationModeOffLabel: t("settings.systemNotificationModeOffLabel"),
        systemNotificationModeBackgroundLabel: t("settings.systemNotificationModeBackgroundLabel"),
        systemNotificationModeAllLabel: t("settings.systemNotificationModeAllLabel"),
        systemNotificationClickBehaviorLabel: t("settings.systemNotificationClickBehaviorLabel"),
        systemNotificationClickOpenCenterLabel: t("settings.systemNotificationClickOpenCenterLabel"),
        systemNotificationClickOpenSourceLabel: t("settings.systemNotificationClickOpenSourceLabel"),
        systemNotificationActionsLabel: t("settings.systemNotificationActionsLabel"),
        systemNotificationActionsDescription: t("settings.systemNotificationActionsDescription"),
        systemNotificationActionsEnabled: t("settings.systemNotificationActionsEnabled"),
        systemNotificationActionsDisabled: t("settings.systemNotificationActionsDisabled"),
        linuxCompatProfileLabel: t("settings.linuxCompatProfileLabel"),
        linuxCompatProfileDescription: t("settings.linuxCompatProfileDescription"),
        linuxCompatProfileReliableLabel: t("settings.linuxCompatProfileReliableLabel"),
        linuxCompatProfileReliableDescription: t("settings.linuxCompatProfileReliableDescription"),
        linuxCompatProfileNativeLabel: t("settings.linuxCompatProfileNativeLabel"),
        linuxCompatProfileNativeDescription: t("settings.linuxCompatProfileNativeDescription"),
        linuxCompatProfilePerformanceLabel: t("settings.linuxCompatProfilePerformanceLabel"),
        linuxCompatProfilePerformanceDescription: t("settings.linuxCompatProfilePerformanceDescription"),
        linuxCompatStatusLabel: t("settings.linuxCompatStatusLabel"),
        linuxCompatCurrentStatusLabel: t("settings.linuxCompatCurrentStatusLabel"),
        linuxCompatSystemLabel: t("settings.linuxCompatSystemLabel"),
        linuxCompatDesktopLabel: t("settings.linuxCompatDesktopLabel"),
        linuxCompatGpuLabel: t("settings.linuxCompatGpuLabel"),
        linuxCompatSwitchesLabel: t("settings.linuxCompatSwitchesLabel"),
        linuxCompatWarningsLabel: t("settings.linuxCompatWarningsLabel"),
        linuxCompatRestartLabel: t("settings.linuxCompatRestartLabel"),
        linuxCompatRestartDescription: t("settings.linuxCompatRestartDescription"),
        linuxCompatRestartNowLabel: t("settings.linuxCompatRestartNowLabel"),
        linuxCompatRestartDialogTitle: t("settings.linuxCompatRestartDialogTitle"),
        linuxCompatRestartDialogDescription: t("settings.linuxCompatRestartDialogDescription"),
        linuxCompatRestartDialogCancel: t("settings.linuxCompatRestartDialogCancel"),
        linuxCompatRecoveryTitle: t("settings.linuxCompatRecoveryTitle"),
        linuxCompatRecoveryDescription: t("settings.linuxCompatRecoveryDescription"),
        linuxCompatRequestFailed: t("settings.linuxCompatRequestFailed")
      },
      settingsAi: {
        categoryLabel: t("settings.aiCategoryLabel"),
        profilesTitle: t("settings.aiProfilesTitle"),
        providerTitle: t("settings.aiProviderTitle"),
        connectionTitle: t("settings.aiConnectionTitle"),
        additionalFieldsTitle: t("settings.aiAdditionalFieldsTitle"),
        addProfile: t("settings.aiAddProfile"),
        editProfile: t("settings.aiEditProfile"),
        saveProfile: t("settings.aiSaveProfile"),
        deleteProfile: t("settings.aiDeleteProfile"),
        cancel: t("settings.aiCancel"),
        profileNameLabel: t("settings.aiProfileNameLabel"),
        profileNamePlaceholder: t("settings.aiProfileNamePlaceholder"),
        urlLabel: t("settings.aiBaseUrlLabel"),
        urlPlaceholder: t("settings.aiBaseUrlPlaceholder"),
        keyLabel: t("settings.aiApiKeyLabel"),
        keyPlaceholder: t("settings.aiApiKeyPlaceholder"),
        modelLabel: t("settings.aiModelLabel"),
        mainModelLabel: t("settings.aiMainModelLabel"),
        modelModeAllLabel: t("settings.aiModelModeAllLabel"),
        modelModeCustomLabel: t("settings.aiModelModeCustomLabel"),
        modelPlaceholder: t("settings.aiModelPlaceholder"),
        modelsHelp: t("settings.aiModelsHelp"),
        headersLabel: t("settings.aiHeadersLabel"),
        headersPlaceholder: t("settings.aiHeadersPlaceholder"),
        emptyTitle: t("settings.aiEmptyTitle"),
        emptyDescription: t("settings.aiEmptyDescription"),
        recommendedSection: t("settings.aiRecommendedSection"),
        allSection: t("settings.aiAllSection"),
        customSection: t("settings.aiCustomSection"),
        secretConfigured: t("settings.aiSecretConfigured"),
        secretMissing: t("settings.aiSecretMissing"),
        noDiscoveredModels: t("settings.aiNoDiscoveredModels"),
        advancedSettingsLabel: t("settings.aiAdvancedSettingsLabel"),
        selectProviderLabel: t("settings.aiSelectProviderLabel"),
        deleteProfileConfirmTitle: t("settings.aiDeleteProfileConfirmTitle"),
        deleteProfileConfirmDescription: t("settings.aiDeleteProfileConfirmDescription"),
        configFileTitle: t("settings.aiConfigFileTitle"),
        configFileDescription: t("settings.aiConfigFileDescription"),
        openConfigFile: t("settings.aiOpenConfigFile"),
        refreshAgent: t("settings.aiRefreshAgent"),
        agentConfigAriaLabel: t("settings.aiAgentConfigAriaLabel"),
        providerAutoFallback: t("settings.aiProviderAutoFallback"),
        defaultModelFallback: t("settings.aiDefaultModelFallback"),
        customProviderFallback: t("settings.aiCustomProviderFallback"),
        accountsTitle: t("settings.aiAccountsTitle"),
        accountsAriaLabel: t("settings.aiAccountsAriaLabel"),
        noDefaultProvider: t("settings.aiNoDefaultProvider"),
        noDefaultModel: t("settings.aiNoDefaultModel"),
        accountsEmptyTitle: t("settings.aiAccountsEmptyTitle"),
        accountsEmptyDescription: t("settings.aiAccountsEmptyDescription"),
        accountConfigured: t("settings.aiAccountConfigured"),
        accountNotConfigured: t("settings.aiAccountNotConfigured"),
        accountDefault: t("settings.aiAccountDefault"),
        loginProvidersTitle: t("settings.aiLoginProvidersTitle"),
        loginProvidersDescription: t("settings.aiLoginProvidersDescription"),
        startLogin: t("settings.aiStartLogin"),
        completeLogin: t("settings.aiCompleteLogin"),
        callbackInputLabel: t("settings.aiCallbackInputLabel"),
        callbackInputPlaceholder: t("settings.aiCallbackInputPlaceholder"),
        loginCallbackDescription: t("settings.aiLoginCallbackDescription"),
        gmailLoginTitle: t("settings.aiGmailLoginTitle"),
        gmailLoginDescription: t("settings.aiGmailLoginDescription"),
        gmailClientIdLabel: t("settings.aiGmailClientIdLabel"),
        gmailClientSecretLabel: t("settings.aiGmailClientSecretLabel"),
        gmailAccessTierLabel: t("settings.aiGmailAccessTierLabel"),
        gmailAccessReadOnly: t("settings.aiGmailAccessReadOnly"),
        gmailAccessFull: t("settings.aiGmailAccessFull"),
        apiKeyProviderTitle: t("settings.aiApiKeyProviderTitle"),
        apiKeyProviderDescription: t("settings.aiApiKeyProviderDescription"),
        removeAccount: t("settings.aiRemoveAccount"),
        providerProfileTitle: t("settings.aiProviderProfileTitle"),
        authHeaderLabel: t("settings.aiAuthHeaderLabel"),
        roleModelsTitle: t("settings.aiRoleModelsTitle"),
        roleSwarmSubagentLabel: t("settings.aiRoleSwarmSubagentLabel"),
        roleReviewLabel: t("settings.aiRoleReviewLabel"),
        roleJudgeLabel: t("settings.aiRoleJudgeLabel"),
        roleMemoryLabel: t("settings.aiRoleMemoryLabel"),
        roleAmbientLabel: t("settings.aiRoleAmbientLabel"),
        roleProviderDefaultPlaceholder: t("settings.aiRoleProviderDefaultPlaceholder"),
        roleMemoryDefaultPlaceholder: t("settings.aiRoleMemoryDefaultPlaceholder"),
        saveRoleModels: t("settings.aiSaveRoleModels"),
        notificationsTitle: t("settings.aiNotificationsTitle"),
        notificationsDescription: t("settings.aiNotificationsDescription"),
        desktopNotificationsLabel: t("settings.aiDesktopNotificationsLabel"),
        ntfyTopicLabel: t("settings.aiNtfyTopicLabel"),
        ntfyServerLabel: t("settings.aiNtfyServerLabel"),
        emailNotificationsLabel: t("settings.aiEmailNotificationsLabel"),
        emailToLabel: t("settings.aiEmailToLabel"),
        emailSmtpHostLabel: t("settings.aiEmailSmtpHostLabel"),
        emailSmtpPortLabel: t("settings.aiEmailSmtpPortLabel"),
        emailFromLabel: t("settings.aiEmailFromLabel"),
        emailPasswordLabel: t("settings.aiEmailPasswordLabel"),
        emailImapHostLabel: t("settings.aiEmailImapHostLabel"),
        emailImapPortLabel: t("settings.aiEmailImapPortLabel"),
        emailReplyLabel: t("settings.aiEmailReplyLabel"),
        telegramNotificationsLabel: t("settings.aiTelegramNotificationsLabel"),
        telegramBotTokenLabel: t("settings.aiTelegramBotTokenLabel"),
        telegramChatIdLabel: t("settings.aiTelegramChatIdLabel"),
        telegramReplyLabel: t("settings.aiTelegramReplyLabel"),
        discordNotificationsLabel: t("settings.aiDiscordNotificationsLabel"),
        discordBotTokenLabel: t("settings.aiDiscordBotTokenLabel"),
        discordChannelIdLabel: t("settings.aiDiscordChannelIdLabel"),
        discordBotUserIdLabel: t("settings.aiDiscordBotUserIdLabel"),
        discordReplyLabel: t("settings.aiDiscordReplyLabel"),
        saveNotifications: t("settings.aiSaveNotifications"),
        runtimeUnavailable: t("settings.aiRuntimeUnavailable"),
        fileEditorUnavailable: t("settings.aiFileEditorUnavailable"),
        configPathUnavailable: t("settings.aiConfigPathUnavailable"),
        sectionAgent: t("settings.aiSectionAgent"),
        sectionSessions: t("settings.aiSectionSessions"),
        memoryConfigTitle: t("settings.aiMemoryConfigTitle"),
        memoryConfigDescription: t("settings.aiMemoryConfigDescription"),
        memoryConfigPlaceholder: t("settings.aiMemoryConfigPlaceholder"),
        memoryConfigLoad: t("settings.aiMemoryConfigLoad"),
        memoryConfigSave: t("settings.aiMemoryConfigSave"),
        memoryConfigStatusIdle: t("settings.aiMemoryConfigStatusIdle"),
        memoryConfigStatusLoaded: t("settings.aiMemoryConfigStatusLoaded"),
        memoryConfigStatusSaved: t("settings.aiMemoryConfigStatusSaved"),
        memoryConfigStatusInvalidJson: t("settings.aiMemoryConfigStatusInvalidJson")
      },
      fileManager: {
        title: t("files.title"),
        locationHome: t("files.locationHome"),
        locationDesktop: t("files.locationDesktop"),
        locationDocuments: t("files.locationDocuments"),
        locationDownloads: t("files.locationDownloads"),
        downloadManagerTitle: t("files.downloadManagerTitle"),
        locationTrash: t("files.locationTrash"),
        homeSectionFavorites: t("files.homeSectionFavorites"),
        homeSectionLocations: t("files.homeSectionLocations"),
        homeSectionDevices: t("files.homeSectionDevices"),
        homeSectionRecent: t("files.homeSectionRecent"),
        navigationBack: t("files.navigationBack"),
        navigationForward: t("files.navigationForward"),
        navigationUp: t("files.navigationUp"),
        refresh: t("files.refresh"),
        addFavorite: t("files.addFavorite"),
        removeFavorite: t("files.removeFavorite"),
        newFolder: t("files.newFolder"),
        newFile: t("files.newFile"),
        delete: t("files.delete"),
        restore: t("files.restore"),
        emptyTrash: t("files.emptyTrash"),
        noRecentLocations: t("files.noRecentLocations"),
        emptyDirectory: t("files.emptyDirectory"),
        emptyTrashState: t("files.emptyTrashState"),
        noFavorites: t("files.noFavorites"),
        emptyDownloads: t("files.emptyDownloads"),
        loading: t("files.loading"),
        unavailable: t("files.unavailable"),
        diskAvailable: t("files.diskAvailable"),
        diskKindSystem: t("files.diskKindSystem"),
        diskKindLocal: t("files.diskKindLocal"),
        diskKindRemovable: t("files.diskKindRemovable"),
        diskKindExternal: t("files.diskKindExternal"),
        deviceUnmounted: t("files.deviceUnmounted"),
        nameColumn: t("files.nameColumn"),
        locationColumn: t("files.locationColumn"),
        originalLocationColumn: t("files.originalLocationColumn"),
        createPlaceholderFile: t("files.createPlaceholderFile"),
        createPlaceholderDirectory: t("files.createPlaceholderDirectory"),
        createConfirm: t("files.createConfirm"),
        createCancel: t("files.createCancel"),
        contextOpen: t("files.contextOpen"),
        contextMountDevice: t("files.contextMountDevice"),
        contextMoveToTrash: t("files.contextMoveToTrash"),
        contextRestore: t("files.contextRestore"),
        contextEmptyTrash: t("files.contextEmptyTrash"),
        contextEjectDevice: t("files.contextEjectDevice"),
        viewList: t("files.viewList"),
        viewLarge: t("files.viewLarge"),
        downloadAddUrl: t("files.downloadAddUrl"),
        downloadImportClipboard: t("files.downloadImportClipboard"),
        downloadImportExternalBrowser: t("files.downloadImportExternalBrowser"),
        downloadUrlPlaceholder: t("files.downloadUrlPlaceholder"),
        downloadOpenFile: t("files.downloadOpenFile"),
        downloadRevealFile: t("files.downloadRevealFile"),
        downloadPause: t("files.downloadPause"),
        downloadResume: t("files.downloadResume"),
        downloadCancel: t("files.downloadCancel"),
        downloadRetry: t("files.downloadRetry"),
        downloadRemove: t("files.downloadRemove"),
        downloadPauseAll: t("files.downloadPauseAll"),
        downloadResumeAll: t("files.downloadResumeAll"),
        downloadCancelAll: t("files.downloadCancelAll"),
        downloadPriority: t("files.downloadPriority"),
        downloadPriorityLow: t("files.downloadPriorityLow"),
        downloadPriorityNormal: t("files.downloadPriorityNormal"),
        downloadPriorityHigh: t("files.downloadPriorityHigh"),
        downloadStateQueued: t("files.downloadStateQueued"),
        downloadStateDownloading: t("files.downloadStateDownloading"),
        downloadStatePaused: t("files.downloadStatePaused"),
        downloadStateCompleted: t("files.downloadStateCompleted"),
        downloadStateFailed: t("files.downloadStateFailed"),
        downloadStateCanceled: t("files.downloadStateCanceled"),
        downloadSourceBrowser: t("files.downloadSourceBrowser"),
        downloadSourceManual: t("files.downloadSourceManual"),
        downloadConnections: t("files.downloadConnections"),
        downloadUnknownSize: t("files.downloadUnknownSize"),
        downloadSpeedIdle: t("files.downloadSpeedIdle"),
        downloadDurationSeconds: t("files.downloadDurationSeconds"),
        downloadDurationMinutes: t("files.downloadDurationMinutes"),
        downloadDurationHours: t("files.downloadDurationHours"),
        downloadEta: t("files.downloadEta"),
        downloadChecksumPending: t("files.downloadChecksumPending"),
        downloadChecksumVerified: t("files.downloadChecksumVerified"),
        downloadChecksumFailed: t("files.downloadChecksumFailed"),
        downloadSettings: t("files.downloadSettings"),
        downloadSettingsSave: t("files.downloadSettingsSave"),
        downloadSettingsSpeedLimit: t("files.downloadSettingsSpeedLimit"),
        downloadSettingsNoLimit: t("files.downloadSettingsNoLimit"),
        downloadAdvancedOptions: t("files.downloadAdvancedOptions"),
        downloadAdvancedCookie: t("files.downloadAdvancedCookie"),
        downloadAdvancedHeaders: t("files.downloadAdvancedHeaders"),
        downloadAdvancedMirrors: t("files.downloadAdvancedMirrors"),
        downloadAdvancedBtSelectedFiles: t("files.downloadAdvancedBtSelectedFiles"),
        downloadAdvancedBtTrackers: t("files.downloadAdvancedBtTrackers"),
        downloadAdvancedPartialFile: t("files.downloadAdvancedPartialFile"),
        downloadAdvancedChecksumAlgorithm: t("files.downloadAdvancedChecksumAlgorithm"),
        downloadAdvancedChecksumNone: t("files.downloadAdvancedChecksumNone"),
        downloadAdvancedChecksumExpected: t("files.downloadAdvancedChecksumExpected"),
        downloadAdvancedMaxRetries: t("files.downloadAdvancedMaxRetries"),
        downloadAdvancedRetryDelay: t("files.downloadAdvancedRetryDelay"),
        downloadAdvancedProxyMode: t("files.downloadAdvancedProxyMode"),
        downloadAdvancedProxyUrl: t("files.downloadAdvancedProxyUrl"),
        downloadSettingsSchedule: t("files.downloadSettingsSchedule"),
        downloadSettingsScheduleEnabled: t("files.downloadSettingsScheduleEnabled"),
        downloadSettingsScheduleStart: t("files.downloadSettingsScheduleStart"),
        downloadSettingsScheduleEnd: t("files.downloadSettingsScheduleEnd"),
        downloadSettingsScheduleOutsideAction: t("files.downloadSettingsScheduleOutsideAction"),
        downloadSettingsSchedulePause: t("files.downloadSettingsSchedulePause"),
        downloadSettingsScheduleSpeedLimit: t("files.downloadSettingsScheduleSpeedLimit"),
        downloadSettingsScheduleLimit: t("files.downloadSettingsScheduleLimit"),
        downloadSettingsSaveRules: t("files.downloadSettingsSaveRules"),
        downloadSettingsAddSaveRule: t("files.downloadSettingsAddSaveRule"),
        downloadSettingsRemoveSaveRule: t("files.downloadSettingsRemoveSaveRule"),
        downloadSettingsRuleEnabled: t("files.downloadSettingsRuleEnabled"),
        downloadSettingsRuleName: t("files.downloadSettingsRuleName"),
        downloadSettingsRuleDirectory: t("files.downloadSettingsRuleDirectory"),
        downloadSettingsRuleExtensions: t("files.downloadSettingsRuleExtensions"),
        downloadSettingsRuleHosts: t("files.downloadSettingsRuleHosts"),
        downloadSettingsRuleProtocols: t("files.downloadSettingsRuleProtocols"),
        downloadSettingsRuleTags: t("files.downloadSettingsRuleTags"),
        downloadSettingsProxyMode: t("files.downloadSettingsProxyMode"),
        downloadSettingsProxySystem: t("files.downloadSettingsProxySystem"),
        downloadSettingsProxyDirect: t("files.downloadSettingsProxyDirect"),
        downloadSettingsProxyHttp: t("files.downloadSettingsProxyHttp"),
        downloadSettingsProxySocks5: t("files.downloadSettingsProxySocks5"),
        downloadSettingsProxyUrl: t("files.downloadSettingsProxyUrl"),
        downloadSettingsCookie: t("files.downloadSettingsCookie"),
        downloadSettingsHeaders: t("files.downloadSettingsHeaders"),
        downloadSettingsPostProcessing: t("files.downloadSettingsPostProcessing"),
        downloadSettingsAutoExtract: t("files.downloadSettingsAutoExtract"),
        downloadSettingsDeleteArchive: t("files.downloadSettingsDeleteArchive"),
        downloadSettingsDetectSplitArchives: t("files.downloadSettingsDetectSplitArchives"),
        downloadSettingsExtractDirectory: t("files.downloadSettingsExtractDirectory"),
        downloadSettingsBt: t("files.downloadSettingsBt"),
        downloadSettingsBtDht: t("files.downloadSettingsBtDht"),
        downloadSettingsBtPeerExchange: t("files.downloadSettingsBtPeerExchange"),
        downloadSettingsBtLocalPeerDiscovery: t("files.downloadSettingsBtLocalPeerDiscovery"),
        downloadSettingsBtSeedTime: t("files.downloadSettingsBtSeedTime"),
        downloadSettingsBtTrackers: t("files.downloadSettingsBtTrackers"),
        downloadSettingsBtUploadLimit: t("files.downloadSettingsBtUploadLimit"),
        downloadRemoteApi: t("files.downloadRemoteApi"),
        downloadRemoteApiStart: t("files.downloadRemoteApiStart"),
        downloadRemoteApiStop: t("files.downloadRemoteApiStop"),
        downloadRemoteApiRunning: t("files.downloadRemoteApiRunning"),
        downloadRemoteApiStopped: t("files.downloadRemoteApiStopped"),
        downloadRemoteApiHost: t("files.downloadRemoteApiHost"),
        downloadRemoteApiPort: t("files.downloadRemoteApiPort"),
        downloadRemoteApiAllowLan: t("files.downloadRemoteApiAllowLan"),
        downloadRemoteApiToken: t("files.downloadRemoteApiToken"),
        chooserBindProjectLabel: t("files.chooserBindProjectLabel"),
        chooserSelectDirectoryPlaceholder: t("files.chooserSelectDirectoryPlaceholder")
      },
      fileEditor: {
        loading: t("editor.loading"),
        unsupported: t("editor.unsupported"),
        unavailable: t("editor.unavailable"),
        readOnly: t("editor.readOnly"),
        conflict: t("editor.conflict"),
        retry: t("editor.retry"),
        save: t("editor.save"),
        openDiff: t("editor.openDiff"),
        closeDiff: t("editor.closeDiff")
      },
      imageViewer: {
        loading: t("imageViewer.loading"),
        unavailable: t("imageViewer.unavailable"),
        unsupported: t("imageViewer.unsupported"),
        retry: t("imageViewer.retry"),
        fit: t("imageViewer.fit"),
        actualSize: t("imageViewer.actualSize"),
        zoomIn: t("imageViewer.zoomIn"),
        zoomOut: t("imageViewer.zoomOut"),
        reset: t("imageViewer.reset"),
        rotateLeft: t("imageViewer.rotateLeft"),
        rotateRight: t("imageViewer.rotateRight"),
        background: t("imageViewer.background"),
        previous: t("imageViewer.previous"),
        next: t("imageViewer.next"),
        nativeTiles: t("imageViewer.nativeTiles"),
        sourceOnly: t("imageViewer.sourceOnly"),
        metadata: t("imageViewer.metadata")
      },
      fileEditorReview: {
        accept: t("ai.editorWorkAccept"),
        reject: t("ai.editorWorkReject"),
        undo: t("ai.editorWorkUndo"),
        previous: t("ai.editorWorkPrevious"),
        next: t("ai.editorWorkNext"),
        acceptAll: t("ai.editorWorkAcceptAll")
      },
      notificationTopbar: {
        openCenter: t("notification.topbarOpenCenter"),
        openPreview: t("notification.topbarOpenPreview")
      },
      agentSessionHistory: {
        title: t("agentHistory.title"),
        searchPlaceholder: t("agentHistory.searchPlaceholder"),
        refresh: t("agentHistory.refresh"),
        loading: t("agentHistory.loading"),
        emptyTitle: t("agentHistory.emptyTitle"),
        emptyDescription: t("agentHistory.emptyDescription"),
        errorTitle: t("agentHistory.errorTitle"),
        openSession: t("agentHistory.openSession"),
        openInAiPanel: t("agentHistory.openInAiPanel"),
        previewTitle: t("agentHistory.previewTitle"),
        previewEmptyTitle: t("agentHistory.previewEmptyTitle"),
        previewEmptyDescription: t("agentHistory.previewEmptyDescription"),
        messages: t("agentHistory.messages"),
        groupSaved: t("agentHistory.groupSaved"),
        groupRecent: t("agentHistory.groupRecent"),
        groupArchived: t("agentHistory.groupArchived"),
        saved: t("agentHistory.saved"),
        unsaved: t("agentHistory.unsaved"),
        archive: t("agentHistory.archive"),
        unarchive: t("agentHistory.unarchive"),
        rename: t("agentHistory.rename"),
        delete: t("agentHistory.delete"),
        renameTitle: t("agentHistory.renameTitle"),
        renamePlaceholder: t("agentHistory.renamePlaceholder"),
        saveRename: t("agentHistory.saveRename"),
        clearRename: t("agentHistory.clearRename"),
        cancelAction: t("agentHistory.cancelAction"),
        deleteConfirmTitle: t("agentHistory.deleteConfirmTitle"),
        deleteConfirmDescription: t("agentHistory.deleteConfirmDescription"),
        deleteConfirmAction: t("agentHistory.deleteConfirmAction"),
        updated: t("agentHistory.updated"),
        workingDir: t("agentHistory.workingDir"),
        modelFallback: t("agentHistory.modelFallback"),
        statusFallback: t("agentHistory.statusFallback"),
        runtimeUnavailable: t("agentHistory.runtimeUnavailable")
      },
      agentProjectTree: {
        title: t("agentProjectTree.title"),
        open: t("agentProjectTree.open"),
        openSourceControl: t("agentProjectTree.openSourceControl"),
        refresh: t("agentProjectTree.refresh"),
        loading: t("agentProjectTree.loading"),
        emptyDirectory: t("agentProjectTree.emptyDirectory"),
        unavailable: t("agentProjectTree.unavailable"),
        selectFileTitle: t("agentProjectTree.selectFileTitle"),
        selectFileDescription: t("agentProjectTree.selectFileDescription")
      },
      agentGit: {
        title: t("agentGit.title"),
        open: t("agentGit.open"),
        refresh: t("agentGit.refresh"),
        loading: t("agentGit.loading"),
        notRepositoryTitle: t("agentGit.notRepositoryTitle"),
        notRepositoryDescription: t("agentGit.notRepositoryDescription"),
        emptyTitle: t("agentGit.emptyTitle"),
        emptyDescription: t("agentGit.emptyDescription"),
        changes: t("agentGit.changes"),
        staged: t("agentGit.staged"),
        unstaged: t("agentGit.unstaged"),
        untracked: t("agentGit.untracked"),
        conflicts: t("agentGit.conflicts"),
        stage: t("agentGit.stage"),
        unstage: t("agentGit.unstage"),
        discard: t("agentGit.discard"),
        discardConfirm: t("agentGit.discardConfirm"),
        selectFileTitle: t("agentGit.selectFileTitle"),
        selectFileDescription: t("agentGit.selectFileDescription"),
        binaryDiff: t("agentGit.binaryDiff"),
        noDiff: t("agentGit.noDiff"),
        unavailable: t("agentGit.unavailable")
      },
      agentSelfDev: {
        title: t("agentSelfDev.title"),
        open: t("agentSelfDev.open"),
        subtitle: t("agentSelfDev.subtitle"),
        promptLabel: t("agentSelfDev.promptLabel"),
        promptPlaceholder: t("agentSelfDev.promptPlaceholder"),
        targetLabel: t("agentSelfDev.targetLabel"),
        targetAgentCore: t("agentSelfDev.targetAgentCore"),
        targetDesktopGui: t("agentSelfDev.targetDesktopGui"),
        targetValidation: t("agentSelfDev.targetValidation"),
        targetGeneral: t("agentSelfDev.targetGeneral"),
        inheritContext: t("agentSelfDev.inheritContext"),
        start: t("agentSelfDev.start"),
        starting: t("agentSelfDev.starting"),
        repo: t("agentSelfDev.repo"),
        status: t("agentSelfDev.status"),
        idle: t("agentSelfDev.idle"),
        running: t("agentSelfDev.running"),
        unavailable: t("agentSelfDev.unavailable"),
        emptyTitle: t("agentSelfDev.emptyTitle"),
        emptyDescription: t("agentSelfDev.emptyDescription"),
        restartRequired: t("agentSelfDev.restartRequired")
      },
      agentOvernight: {
        title: t("agentOvernight.title"),
        open: t("agentOvernight.open"),
        subtitle: t("agentOvernight.subtitle"),
        missionLabel: t("agentOvernight.missionLabel"),
        missionPlaceholder: t("agentOvernight.missionPlaceholder"),
        durationLabel: t("agentOvernight.durationLabel"),
        customMinutes: t("agentOvernight.customMinutes"),
        oneHour: t("agentOvernight.oneHour"),
        fourHours: t("agentOvernight.fourHours"),
        eightHours: t("agentOvernight.eightHours"),
        inheritContext: t("agentOvernight.inheritContext"),
        start: t("agentOvernight.start"),
        starting: t("agentOvernight.starting"),
        refresh: t("agentOvernight.refresh"),
        loading: t("agentOvernight.loading"),
        cancel: t("agentOvernight.cancel"),
        review: t("agentOvernight.review"),
        running: t("agentOvernight.running"),
        idle: t("agentOvernight.idle"),
        latestRuns: t("agentOvernight.latestRuns"),
        noRunsTitle: t("agentOvernight.noRunsTitle"),
        noRunsDescription: t("agentOvernight.noRunsDescription"),
        status: t("agentOvernight.status"),
        model: t("agentOvernight.model"),
        provider: t("agentOvernight.provider"),
        workingDir: t("agentOvernight.workingDir"),
        targetWake: t("agentOvernight.targetWake"),
        lastActivity: t("agentOvernight.lastActivity"),
        progress: t("agentOvernight.progress"),
        taskCards: t("agentOvernight.taskCards"),
        events: t("agentOvernight.events"),
        log: t("agentOvernight.log"),
        reviewPreview: t("agentOvernight.reviewPreview"),
        transcript: t("agentOvernight.transcript"),
        emptyTasks: t("agentOvernight.emptyTasks"),
        emptyEvents: t("agentOvernight.emptyEvents"),
        emptyTranscript: t("agentOvernight.emptyTranscript"),
        unavailable: t("agentOvernight.unavailable")
      },
      notificationCenter: {
        title: t("notification.centerTitle"),
        listTitle: t("notification.centerListTitle"),
        markAllRead: t("notification.centerMarkAllRead"),
        clearAll: t("notification.centerClearAll"),
        openSource: t("notification.centerOpenSource"),
        sourceFallback: t("notification.centerSourceFallback"),
        unread: t("notification.centerUnread")
      },
      softwareStore: {
        title: t("softwareStore.title"),
        open: t("softwareStore.open"),
        tabTitle: t("softwareStore.tabTitle"),
        searchPlaceholder: t("softwareStore.searchPlaceholder"),
        refresh: t("softwareStore.refresh"),
        loading: t("softwareStore.loading"),
        unavailable: t("softwareStore.unavailable"),
        allTab: t("softwareStore.allTab"),
        builtinTab: t("softwareStore.builtinTab"),
        uiuxTab: t("softwareStore.uiuxTab"),
        builtinBadge: t("softwareStore.builtinBadge"),
        uiuxBadge: t("softwareStore.uiuxBadge"),
        activeBadge: t("softwareStore.activeBadge"),
        pendingBadge: t("softwareStore.pendingBadge"),
        trustedBadge: t("softwareStore.trustedBadge"),
        untrustedBadge: t("softwareStore.untrustedBadge"),
        revokedBadge: t("softwareStore.revokedBadge"),
        detailsTitle: t("softwareStore.detailsTitle"),
        selectItemTitle: t("softwareStore.selectItemTitle"),
        selectItemDescription: t("softwareStore.selectItemDescription"),
        emptyTitle: t("softwareStore.emptyTitle"),
        emptyDescription: t("softwareStore.emptyDescription"),
        typeLabel: t("softwareStore.typeLabel"),
        categoryLabel: t("softwareStore.categoryLabel"),
        versionLabel: t("softwareStore.versionLabel"),
        sourceLabel: t("softwareStore.sourceLabel"),
        statusLabel: t("softwareStore.statusLabel"),
        permissionsLabel: t("softwareStore.permissionsLabel"),
        actionsLabel: t("softwareStore.actionsLabel"),
        noActions: t("softwareStore.noActions"),
        riskLabel: t("softwareStore.riskLabel"),
        agentAccessLabel: t("softwareStore.agentAccessLabel"),
        noPermissions: t("softwareStore.noPermissions"),
        builtinType: t("softwareStore.builtinType"),
        uiuxType: t("softwareStore.uiuxType"),
        agentAccessNotConnected: t("softwareStore.agentAccessNotConnected"),
        agentAccessReadOnly: t("softwareStore.agentAccessReadOnly"),
        agentAccessControllable: t("softwareStore.agentAccessControllable"),
        openBuiltin: t("softwareStore.openBuiltin"),
        openUnavailable: t("softwareStore.openUnavailable"),
        chooseLocal: t("softwareStore.chooseLocal"),
        installLocal: t("softwareStore.installLocal"),
        installGit: t("softwareStore.installGit"),
        installNpm: t("softwareStore.installNpm"),
        gitUrlLabel: t("softwareStore.gitUrlLabel"),
        gitRefLabel: t("softwareStore.gitRefLabel"),
        gitSubdirLabel: t("softwareStore.gitSubdirLabel"),
        npmPackageLabel: t("softwareStore.npmPackageLabel"),
        npmVersionLabel: t("softwareStore.npmVersionLabel"),
        npmSubdirLabel: t("softwareStore.npmSubdirLabel"),
        trust: t("softwareStore.trust"),
        revokeTrust: t("softwareStore.revokeTrust"),
        activate: t("softwareStore.activate"),
        activating: t("softwareStore.activating"),
        operationSucceeded: t("softwareStore.operationSucceeded"),
        operationFailed: t("softwareStore.operationFailed"),
        reloadRequired: t("softwareStore.reloadRequired"),
        installedAtLabel: t("softwareStore.installedAtLabel"),
        updatedAtLabel: t("softwareStore.updatedAtLabel"),
        localSource: t("softwareStore.localSource"),
        gitSource: t("softwareStore.gitSource"),
        npmSource: t("softwareStore.npmSource"),
        builtinSource: t("softwareStore.builtinSource"),
        builtinApps: [
          {
            id: "browser-search",
            title: t("softwareStore.browserSearchTitle"),
            description: t("softwareStore.browserSearchDescription"),
            category: t("softwareStore.categoryCore"),
            agentAccess: "readOnly" as const,
            openable: true
          },
          {
            id: "file-manager",
            title: t("softwareStore.fileManagerTitle"),
            description: t("softwareStore.fileManagerDescription"),
            category: t("softwareStore.categoryCore"),
            agentAccess: "controllable" as const,
            openable: true
          },
          {
            id: "downloads",
            title: t("softwareStore.downloadsTitle"),
            description: t("softwareStore.downloadsDescription"),
            category: t("softwareStore.categoryCore"),
            agentAccess: "notConnected" as const,
            openable: false,
            openDisabledReason: t("softwareStore.contextRequired")
          },
          {
            id: "terminal",
            title: t("softwareStore.terminalTitle"),
            description: t("softwareStore.terminalDescription"),
            category: t("softwareStore.categoryCore"),
            agentAccess: "controllable" as const,
            openable: false,
            openDisabledReason: t("softwareStore.contextRequired")
          },
          {
            id: "image-viewer",
            title: t("softwareStore.imageViewerTitle"),
            description: t("softwareStore.imageViewerDescription"),
            category: t("softwareStore.categoryMedia"),
            agentAccess: "readOnly" as const,
            openable: false,
            openDisabledReason: t("softwareStore.contextRequired")
          },
          {
            id: "notifications",
            title: t("softwareStore.notificationsTitle"),
            description: t("softwareStore.notificationsDescription"),
            category: t("softwareStore.categorySystem"),
            agentAccess: "readOnly" as const,
            openable: false,
            openDisabledReason: t("softwareStore.contextRequired")
          },
          {
            id: "settings",
            title: t("softwareStore.settingsTitle"),
            description: t("softwareStore.settingsDescription"),
            category: t("softwareStore.categorySystem"),
            agentAccess: "notConnected" as const,
            openable: true
          },
          {
            id: "agent-history",
            title: t("softwareStore.agentHistoryTitle"),
            description: t("softwareStore.agentHistoryDescription"),
            category: t("softwareStore.categoryAgent"),
            agentAccess: "readOnly" as const,
            openable: true
          },
          {
            id: "agent-project-tree",
            title: t("softwareStore.agentProjectTreeTitle"),
            description: t("softwareStore.agentProjectTreeDescription"),
            category: t("softwareStore.categoryAgent"),
            agentAccess: "controllable" as const,
            openable: false,
            openDisabledReason: t("softwareStore.contextRequired")
          },
          {
            id: "agent-git",
            title: t("softwareStore.agentGitTitle"),
            description: t("softwareStore.agentGitDescription"),
            category: t("softwareStore.categoryAgent"),
            agentAccess: "controllable" as const,
            openable: false,
            openDisabledReason: t("softwareStore.contextRequired")
          },
          {
            id: "agent-selfdev",
            title: t("softwareStore.agentSelfDevTitle"),
            description: t("softwareStore.agentSelfDevDescription"),
            category: t("softwareStore.categoryAgent"),
            agentAccess: "controllable" as const,
            openable: false,
            openDisabledReason: t("softwareStore.contextRequired")
          },
          {
            id: "agent-overnight",
            title: t("softwareStore.agentOvernightTitle"),
            description: t("softwareStore.agentOvernightDescription"),
            category: t("softwareStore.categoryAgent"),
            agentAccess: "controllable" as const,
            openable: false,
            openDisabledReason: t("softwareStore.contextRequired")
          },
          {
            id: "login-manager",
            title: t("softwareStore.loginManagerTitle"),
            description: t("softwareStore.loginManagerDescription"),
            category: t("softwareStore.categorySystem"),
            agentAccess: "controllable" as const,
            openable: true
          },
          {
            id: "software-store",
            title: t("softwareStore.selfTitle"),
            description: t("softwareStore.selfDescription"),
            category: t("softwareStore.categorySystem"),
            agentAccess: "notConnected" as const,
            openable: true
          }
        ] satisfies readonly SoftwareStoreBuiltinApp[]
      },
      loginManager: {
        title: t("loginManager.title"),
        open: t("loginManager.open"),
        tabTitle: t("loginManager.tabTitle"),
        searchPlaceholder: t("loginManager.searchPlaceholder"),
        refresh: t("loginManager.refresh"),
        sessionsTab: t("loginManager.sessionsTab"),
        credentialsTab: t("loginManager.credentialsTab"),
        reviewTab: t("loginManager.reviewTab"),
        passwordsUnavailable: t("loginManager.passwordsUnavailable"),
        emptySessionsTitle: t("loginManager.emptySessionsTitle"),
        emptySessionsDescription: t("loginManager.emptySessionsDescription"),
        emptyCredentialsTitle: t("loginManager.emptyCredentialsTitle"),
        emptyCredentialsDescription: t("loginManager.emptyCredentialsDescription"),
        openSite: t("loginManager.openSite"),
        logoutSite: t("loginManager.logoutSite"),
        deleteCredential: t("loginManager.deleteCredential"),
        reveal: t("loginManager.reveal"),
        copy: t("loginManager.copy"),
        copied: t("loginManager.copied"),
        fill: t("loginManager.fill"),
        edit: t("loginManager.edit"),
        save: t("loginManager.save"),
        cancel: t("loginManager.cancel"),
        accountLabel: t("loginManager.accountLabel"),
        authMethodLabel: t("loginManager.authMethodLabel"),
        notesLabel: t("loginManager.notesLabel"),
        statusObserved: t("loginManager.statusObserved"),
        statusPossible: t("loginManager.statusPossible"),
        sourceObserved: t("loginManager.sourceObserved"),
        sourceInferred: t("loginManager.sourceInferred"),
        sourceManual: t("loginManager.sourceManual"),
        sourceUnknown: t("loginManager.sourceUnknown"),
        methodLabels: {
          site_session: t("loginManager.methodSiteSession"),
          password: t("loginManager.methodPassword"),
          passkey: t("loginManager.methodPasskey"),
          oauth: t("loginManager.methodOauth"),
          sso: t("loginManager.methodSso"),
          magic_link: t("loginManager.methodMagicLink"),
          unknown: t("loginManager.methodUnknown")
        }
      },
      workspaceI18n: {
        searchPlaceholder: t("browser.searchPlaceholder"),
        searchActionLabel: t("browser.searchAction"),
        resultsHeading: t("browser.resultsHeading"),
        resultsBlendTitle: t("browser.resultsBlendTitle"),
        resultsEngineOverview: t("browser.resultsEngineOverview"),
        resultsNoResults: t("browser.resultsNoResults"),
        resultsEngineError: t("browser.resultsEngineError"),
        resultsOfficial: t("browser.resultsOfficial"),
        resultsOfficialHomepage: t("browser.resultsOfficialHomepage"),
        resultsOfficialSubsite: t("browser.resultsOfficialSubsite"),
        resultsOfficialDocs: t("browser.resultsOfficialDocs"),
        resultsOfficialLogin: t("browser.resultsOfficialLogin"),
        resultsOfficialDownload: t("browser.resultsOfficialDownload"),
        resultsOfficialSupport: t("browser.resultsOfficialSupport"),
        resultsSourceFilter: t("browser.resultsSourceFilter"),
        resultsAllTab: t("browser.resultsAllTab"),
        resultsWebTab: t("browser.resultsWebTab"),
        resultsLocalTab: t("browser.resultsLocalTab"),
        resultsLocalTitle: t("browser.resultsLocalTitle"),
        resultsLocalPanelTitle: t("browser.resultsLocalPanelTitle"),
        resultsLocalNoMatches: t("browser.resultsLocalNoMatches"),
        resultsLocalSearchingMore: t("browser.resultsLocalSearchingMore"),
        resultsLocalScope: t("browser.resultsLocalScope"),
        resultsLocalScannedFiles: t("browser.resultsLocalScannedFiles"),
        resultsLocalScannedDirs: t("browser.resultsLocalScannedDirs"),
        resultsLocalContentScans: t("browser.resultsLocalContentScans"),
        resultsLocalMatched: t("browser.resultsLocalMatched"),
        resultsLocalIndex: t("browser.resultsLocalIndex"),
        resultsLocalScore: t("browser.resultsLocalScore"),
        resultsLocalLine: t("browser.resultsLocalLine"),
        channelIdle: t("browser.channelIdle"),
        channelLoading: t("browser.channelLoading"),
        channelReady: t("browser.channelReady"),
        channelError: t("browser.channelError"),
        deepSearchToggle: t("browser.deepSearchToggle"),
        deepSearchChip: t("browser.deepSearchChip"),
        deepSearchHeading: t("browser.deepSearchHeading"),
        deepSearchStop: t("browser.deepSearchStop"),
        deepSearchFitView: t("browser.deepSearchFitView"),
        deepSearchResetLayout: t("browser.deepSearchResetLayout"),
        deepSearchLoading: t("browser.deepSearchLoading"),
        deepSearchEmpty: t("browser.deepSearchEmpty"),
        deepSearchOverview: t("browser.deepSearchOverview"),
        deepSearchSelectedNode: t("browser.deepSearchSelectedNode"),
        deepSearchPhase: t("browser.deepSearchPhase"),
        deepSearchBudget: t("browser.deepSearchBudget"),
        deepSearchWebStatus: t("browser.deepSearchWebStatus"),
        deepSearchLocalStatus: t("browser.deepSearchLocalStatus"),
        deepSearchDeduped: t("browser.deepSearchDeduped"),
        deepSearchDerived: t("browser.deepSearchDerived"),
        deepSearchRounds: t("browser.deepSearchRounds"),
        deepSearchOpen: t("browser.deepSearchOpen"),
        deepSearchExpand: t("browser.deepSearchExpand"),
        deepSearchCenter: t("browser.deepSearchCenter"),
        deepSearchNoSelection: t("browser.deepSearchNoSelection"),
        deepSearchAll: t("browser.deepSearchAll"),
        deepSearchSnippet: t("browser.deepSearchSnippet"),
        deepSearchSource: t("browser.deepSearchSource"),
        deepSearchConnectedLinks: t("browser.deepSearchConnectedLinks"),
        deepSearchEdgeFilters: t("browser.deepSearchEdgeFilters"),
        deepSearchDirection: t("browser.deepSearchDirection"),
        deepSearchIncoming: t("browser.deepSearchIncoming"),
        deepSearchOutgoing: t("browser.deepSearchOutgoing"),
        deepSearchBoth: t("browser.deepSearchBoth"),
        deepSearchDiscovered: t("browser.deepSearchDiscovered"),
        deepSearchExpanded: t("browser.deepSearchExpanded"),
        deepSearchRelated: t("browser.deepSearchRelated"),
        deepSearchHostsSubdomain: t("browser.deepSearchHostsSubdomain"),
        deepSearchContainsPage: t("browser.deepSearchContainsPage"),
        deepSearchLineage: t("browser.deepSearchLineage"),
        deepSearchAlternateLinks: t("browser.deepSearchAlternateLinks"),
        deepSearchRevealInManager: t("browser.deepSearchRevealInManager"),
        deepSearchMatchKind: t("browser.deepSearchMatchKind"),
        deepSearchLine: t("browser.deepSearchLine"),
        deepSearchSharedTerms: t("browser.deepSearchSharedTerms"),
        deepSearchDomain: t("browser.deepSearchDomain"),
        deepSearchSubdomain: t("browser.deepSearchSubdomain"),
        deepSearchPage: t("browser.deepSearchPage"),
        deepSearchVerified: t("browser.deepSearchVerified"),
        deepSearchGuessed: t("browser.deepSearchGuessed"),
        deepSearchDiscoveredBy: t("browser.deepSearchDiscoveredBy"),
        deepSearchVerificationScore: t("browser.deepSearchVerificationScore"),
        deepSearchGuessedDomains: t("browser.deepSearchGuessedDomains"),
        deepSearchVerifiedDomains: t("browser.deepSearchVerifiedDomains"),
        deepSearchSubdomains: t("browser.deepSearchSubdomains"),
        deepSearchVisitedPages: t("browser.deepSearchVisitedPages"),
        deepSearchQueuedPages: t("browser.deepSearchQueuedPages"),
        deepSearchDroppedPages: t("browser.deepSearchDroppedPages"),
        deepSearchSiteExpansionStatus: t("browser.deepSearchSiteExpansionStatus")
      } satisfies WorkspaceSurfaceI18nProps,
    }),
    [t]
  );

export type WorkbenchLabels = ReturnType<typeof useWorkbenchLabels>;
