import { useMemo } from "react";

import type { createTranslator } from "../i18n";
import { createWorkbenchUiPackOptions } from "../ui-platform";
import type { WorkspaceSurfaceI18nProps } from "./workspace-surface-router";
import {
  createSettingLocaleOptions,
  createSettingSplitOverflowPolicyOptions,
  createSettingSplitThreePaneLayoutOptions,
  createSettingSplitTriggerModeOptions,
  createSettingTerminalThemeOptions,
  createSettingThemeOptions
} from "./service";

type WorkbenchTranslator = ReturnType<typeof createTranslator>;

export const useWorkbenchLabels = (t: WorkbenchTranslator) =>
  useMemo(
    () => ({
      terminal: {
        newTab: t("terminal.newTab"),
        splitHorizontal: t("terminal.splitHorizontal"),
        splitVertical: t("terminal.splitVertical"),
        moveTerminalToTop: t("panel.moveTerminalToTop"),
        moveTerminalToBottom: t("panel.moveTerminalToBottom"),
        closeTab: t("terminal.closeTab"),
        emptyDock: t("terminal.emptyDock"),
        unavailable: t("terminal.unavailable")
      },
      settingsOptions: {
        locale: createSettingLocaleOptions(t),
        theme: createSettingThemeOptions(t),
        uiStyle: createWorkbenchUiPackOptions(t),
        terminalTheme: createSettingTerminalThemeOptions(t),
        splitTriggerMode: createSettingSplitTriggerModeOptions(t),
        splitThreePaneLayout: createSettingSplitThreePaneLayoutOptions(t),
        splitOverflowPolicy: createSettingSplitOverflowPolicyOptions(t),
        searchScope: [
          {
            value: "home" as const,
            label: t("settings.searchScopeHomeLabel"),
            description: t("settings.searchScopeHomeDescription")
          },
          {
            value: "full_system" as const,
            label: t("settings.searchScopeFullSystemLabel"),
            description: t("settings.searchScopeFullSystemDescription")
          },
          {
            value: "workspace" as const,
            label: t("settings.searchScopeWorkspaceLabel"),
            description: t("settings.searchScopeWorkspaceDescription")
          },
          {
            value: "custom" as const,
            label: t("settings.searchScopeCustomLabel"),
            description: t("settings.searchScopeCustomDescription")
          }
        ],
        searchWebEngine: [
          { value: "bing", label: t("settings.searchWebEngineBing") },
          { value: "brave", label: t("settings.searchWebEngineBrave") },
          { value: "duckduckgo", label: t("settings.searchWebEngineDuckDuckGo") },
          { value: "searxng", label: t("settings.searchWebEngineSearxng") }
        ],
        deepSearchBudget: [
          { value: "low" as const, label: t("settings.deepSearchBudgetLowLabel") },
          { value: "medium" as const, label: t("settings.deepSearchBudgetMediumLabel") },
          { value: "high" as const, label: t("settings.deepSearchBudgetHighLabel") }
        ],
        deepSearchLocalOpenBehavior: [
          { value: "open_file" as const, label: t("settings.deepSearchOpenFileLabel") },
          { value: "reveal_in_manager" as const, label: t("settings.deepSearchRevealInManagerLabel") }
        ],
        deepSearchCrawlPolicy: [
          {
            value: "accessibility_only" as const,
            label: t("settings.deepSearchCrawlPolicyAccessibilityOnlyLabel")
          }
        ],
        omniboxNonBrowserSubmitTarget: [
          {
            value: "new_tab" as const,
            label: t("settings.omniboxNonBrowserSubmitTargetNewTabLabel")
          },
          {
            value: "replace_active_tab" as const,
            label: t("settings.omniboxNonBrowserSubmitTargetReplaceActiveLabel")
          }
        ]
      },
      settingsSurface: {
        title: t("settings.pageTitle"),
        aiCategoryLabel: t("settings.aiCategoryLabel"),
        languageLabel: t("settings.languageLabel"),
        themeLabel: t("settings.themeLabel"),
        uiStyleLabel: t("settings.uiStyleLabel"),
        uiStyleExternalReloadRequired: t("settings.uiStyleExternalReloadRequired"),
        uiStyleExternalUntrusted: t("settings.uiStyleExternalUntrusted"),
        terminalThemeLabel: t("settings.terminalThemeLabel"),
        splitTriggerModeLabel: t("settings.splitTriggerModeLabel"),
        splitThreePaneLayoutLabel: t("settings.splitThreePaneLayoutLabel"),
        splitOverflowPolicyLabel: t("settings.splitOverflowPolicyLabel"),
        aiRichRenderLabel: t("settings.aiRichRenderLabel"),
        aiRichRenderDescription: t("settings.aiRichRenderDescription"),
        aiRichRenderEnabledLabel: t("settings.aiRichRenderEnabled"),
        aiRichRenderDisabledLabel: t("settings.aiRichRenderDisabled"),
        aiStopBehaviorLabel: t("settings.aiStopBehaviorLabel"),
        aiStopBehaviorDescription: t("settings.aiStopBehaviorDescription"),
        aiStopBehaviorTurnOnlyLabel: t("settings.aiStopBehaviorTurnOnlyLabel"),
        aiStopBehaviorTurnOnlyDescription: t("settings.aiStopBehaviorTurnOnlyDescription"),
        aiStopBehaviorTurnAndBackgroundLabel: t("settings.aiStopBehaviorTurnAndBackgroundLabel"),
        aiStopBehaviorTurnAndBackgroundDescription: t("settings.aiStopBehaviorTurnAndBackgroundDescription"),
        preventSleepLabel: t("settings.preventSleepLabel"),
        preventSleepDescription: t("settings.preventSleepDescription"),
        preventSleepEnabledLabel: t("settings.preventSleepEnabled"),
        preventSleepDisabledLabel: t("settings.preventSleepDisabled"),
        jsReplLabel: t("settings.jsReplLabel"),
        jsReplDescription: t("settings.jsReplDescription"),
        jsReplEnabledLabel: t("settings.jsReplEnabled"),
        jsReplDisabledLabel: t("settings.jsReplDisabled"),
        forceWebPageThemingLabel: t("settings.forceWebPageThemingLabel"),
        forceWebPageThemingDescription: t("settings.forceWebPageThemingDescription"),
        forceWebPageThemingEnabledLabel: t("settings.forceWebPageThemingEnabled"),
        forceWebPageThemingDisabledLabel: t("settings.forceWebPageThemingDisabled"),
        searchCategoryLabel: t("settings.searchCategoryLabel"),
        searchScopeLabel: t("settings.searchScopeLabel"),
        searchCustomRootsLabel: t("settings.searchCustomRootsLabel"),
        searchCustomRootsPlaceholder: t("settings.searchCustomRootsPlaceholder"),
        searchWebEnginesLabel: t("settings.searchWebEnginesLabel"),
        searchSearxngEndpointLabel: t("settings.searchSearxngEndpointLabel"),
        searchDeepBudgetLabel: t("settings.deepSearchDefaultBudgetLabel"),
        deepSearchRestoreViewportLabel: t("settings.deepSearchRestoreViewportLabel"),
        deepSearchLocalOpenBehaviorLabel: t("settings.deepSearchLocalOpenBehaviorLabel"),
        deepSearchSiteExpansionLabel: t("settings.deepSearchSiteExpansionLabel"),
        deepSearchProactiveGuessLabel: t("settings.deepSearchProactiveGuessLabel"),
        deepSearchCrawlPolicyLabel: t("settings.deepSearchCrawlPolicyLabel"),
        searchEnableFuzzyLabel: t("settings.searchEnableFuzzyLabel"),
        searchEnableContentLabel: t("settings.searchEnableContentLabel"),
        searchIncludeHiddenLabel: t("settings.searchIncludeHiddenLabel"),
        searchAutoIndexLabel: t("settings.searchAutoIndexLabel"),
        searchIndexStatusLabel: t("settings.searchIndexStatusLabel"),
        searchRebuildIndexLabel: t("settings.searchRebuildIndexLabel"),
        omniboxNonBrowserSubmitTargetLabel: t("settings.omniboxNonBrowserSubmitTargetLabel")
      },
      settingsAi: {
        categoryLabel: t("settings.aiCategoryLabel"),
        profilesTitle: t("settings.aiProfilesTitle"),
        providerTitle: t("settings.aiProviderTitle"),
        connectionTitle: t("settings.aiConnectionTitle"),
        additionalFieldsTitle: t("settings.aiAdditionalFieldsTitle"),
        statusTitle: t("settings.aiStatusTitle"),
        addProfile: t("settings.aiAddProfile"),
        saveProfile: t("settings.aiSaveProfile"),
        deleteProfile: t("settings.aiDeleteProfile"),
        setDefaultProfile: t("settings.aiSetDefaultProfile"),
        clearApiKey: t("settings.aiClearApiKey"),
        testConnection: t("settings.aiTestConnection"),
        discoverModels: t("settings.aiDiscoverModels"),
        refreshModels: t("settings.aiRefreshModels"),
        authorizeChatGpt: t("settings.aiAuthorizeChatGpt"),
        authorizeChatGptDeviceCode: t("settings.aiAuthorizeChatGptDeviceCode"),
        profileNameLabel: t("settings.aiProfileNameLabel"),
        profileNamePlaceholder: t("settings.aiProfileNamePlaceholder"),
        urlLabel: t("settings.aiBaseUrlLabel"),
        urlPlaceholder: t("settings.aiBaseUrlPlaceholder"),
        keyLabel: t("settings.aiApiKeyLabel"),
        keyPlaceholder: t("settings.aiApiKeyPlaceholder"),
        modelLabel: t("settings.aiModelLabel"),
        modelPlaceholder: t("settings.aiModelPlaceholder"),
        modelsHelp: t("settings.aiModelsHelp"),
        headersLabel: t("settings.aiHeadersLabel"),
        headersPlaceholder: t("settings.aiHeadersPlaceholder"),
        defaultBadge: t("settings.aiDefaultBadge"),
        defaultProfileLabel: t("settings.aiDefaultProfileLabel"),
        statusIdle: t("settings.aiStatusIdle"),
        statusSaved: t("settings.aiStatusSaved"),
        statusDeleted: t("settings.aiStatusDeleted"),
        statusDefaultUpdated: t("settings.aiStatusDefaultUpdated"),
        statusChatGptAuthorized: t("settings.aiStatusChatGptAuthorized"),
        statusLastChecked: t("settings.aiStatusLastChecked"),
        emptyTitle: t("settings.aiEmptyTitle"),
        emptyDescription: t("settings.aiEmptyDescription"),
        recommendedSection: t("settings.aiRecommendedSection"),
        allSection: t("settings.aiAllSection"),
        customSection: t("settings.aiCustomSection"),
        secretConfigured: t("settings.aiSecretConfigured"),
        secretMissing: t("settings.aiSecretMissing"),
        noDiscoveredModels: t("settings.aiNoDiscoveredModels"),
        capabilityLabel: t("settings.aiCapabilityLabel"),
        capabilityFull: t("settings.aiCapabilityFull"),
        capabilityStatic: t("settings.aiCapabilityStatic"),
        capabilityPending: t("settings.aiCapabilityPending"),
        modelSourceDynamic: t("settings.aiModelSourceDynamic"),
        modelSourcePreset: t("settings.aiModelSourcePreset"),
        modelSourceCustom: t("settings.aiModelSourceCustom"),
        memoryConfigTitle: t("settings.aiMemoryConfigTitle"),
        memoryConfigDescription: t("settings.aiMemoryConfigDescription"),
        memoryConfigPlaceholder: t("settings.aiMemoryConfigPlaceholder"),
        memoryConfigLoad: t("settings.aiMemoryConfigLoad"),
        memoryConfigSave: t("settings.aiMemoryConfigSave"),
        memoryConfigStatusIdle: t("settings.aiMemoryConfigStatusIdle"),
        memoryConfigStatusLoaded: t("settings.aiMemoryConfigStatusLoaded"),
        memoryConfigStatusSaved: t("settings.aiMemoryConfigStatusSaved"),
        memoryConfigStatusInvalidJson: t("settings.aiMemoryConfigStatusInvalidJson"),
        browserAutomationTitle: t("settings.browserAutomationTitle"),
        browserAutomationDescription: t("settings.browserAutomationDescription"),
        browserAutomationOptionLyraDirect: t("settings.browserAutomationLyraDirectLabel"),
        browserAutomationOptionLyraDirectDescription: t("settings.browserAutomationLyraDirectDescription"),
        browserAutomationOptionBrowserUse: t("settings.browserAutomationBrowserUseLabel"),
        browserAutomationOptionBrowserUseDescription: t("settings.browserAutomationBrowserUseDescription"),
        browserAutomationOptionSmart: t("settings.browserAutomationSmartLabel"),
        browserAutomationOptionSmartDescription: t("settings.browserAutomationSmartDescription"),
        browserAutomationStatusChecking: t("settings.browserAutomationStatusChecking"),
        browserAutomationStatusHealthy: t("settings.browserAutomationStatusHealthy"),
        browserAutomationStatusUnavailable: t("settings.browserAutomationStatusUnavailable"),
        browserAutomationStatusReasonMissingBundle: t("settings.browserAutomationReasonMissingBundle"),
        browserAutomationStatusReasonIntegrityFailed: t("settings.browserAutomationReasonIntegrityFailed"),
        browserAutomationStatusReasonDaemonLaunchFailed: t("settings.browserAutomationReasonDaemonLaunchFailed"),
        browserAutomationStatusReasonBridgeUnavailable: t("settings.browserAutomationReasonBridgeUnavailable"),
        browserAutomationStatusReasonUnsupportedPlatform: t("settings.browserAutomationReasonUnsupportedPlatform"),
        lyraDirectAdvancedTitle: t("settings.lyraDirectAdvancedTitle"),
        lyraDirectAdvancedDescription: t("settings.lyraDirectAdvancedDescription"),
        lyraDirectMicroExecutorBudgetLabel: t("settings.lyraDirectMicroExecutorBudgetLabel"),
        lyraDirectMicroExecutorBudgetConservative: t("settings.lyraDirectMicroExecutorBudgetConservative"),
        lyraDirectMicroExecutorBudgetConservativeDescription: t("settings.lyraDirectMicroExecutorBudgetConservativeDescription"),
        lyraDirectMicroExecutorBudgetBalanced: t("settings.lyraDirectMicroExecutorBudgetBalanced"),
        lyraDirectMicroExecutorBudgetBalancedDescription: t("settings.lyraDirectMicroExecutorBudgetBalancedDescription"),
        lyraDirectMicroExecutorBudgetAggressive: t("settings.lyraDirectMicroExecutorBudgetAggressive"),
        lyraDirectMicroExecutorBudgetAggressiveDescription: t("settings.lyraDirectMicroExecutorBudgetAggressiveDescription")
      },
      fileManager: {
        title: t("files.title"),
        locationHome: t("files.locationHome"),
        locationDesktop: t("files.locationDesktop"),
        locationDocuments: t("files.locationDocuments"),
        locationDownloads: t("files.locationDownloads"),
        locationTrash: t("files.locationTrash"),
        homeSectionFavorites: t("files.homeSectionFavorites"),
        homeSectionLocations: t("files.homeSectionLocations"),
        homeSectionDevices: t("files.homeSectionDevices"),
        homeSectionRecent: t("files.homeSectionRecent"),
        navigationBack: t("files.navigationBack"),
        navigationForward: t("files.navigationForward"),
        navigationUp: t("files.navigationUp"),
        refresh: t("files.refresh"),
        addFavorite: t("files.addFavorite"),
        removeFavorite: t("files.removeFavorite"),
        newFolder: t("files.newFolder"),
        newFile: t("files.newFile"),
        delete: t("files.delete"),
        restore: t("files.restore"),
        emptyTrash: t("files.emptyTrash"),
        noRecentLocations: t("files.noRecentLocations"),
        emptyDirectory: t("files.emptyDirectory"),
        emptyTrashState: t("files.emptyTrashState"),
        loading: t("files.loading"),
        unavailable: t("files.unavailable"),
        diskAvailable: t("files.diskAvailable"),
        diskKindSystem: t("files.diskKindSystem"),
        diskKindLocal: t("files.diskKindLocal"),
        diskKindRemovable: t("files.diskKindRemovable"),
        diskKindExternal: t("files.diskKindExternal"),
        deviceUnmounted: t("files.deviceUnmounted"),
        nameColumn: t("files.nameColumn"),
        locationColumn: t("files.locationColumn"),
        originalLocationColumn: t("files.originalLocationColumn"),
        createPlaceholderFile: t("files.createPlaceholderFile"),
        createPlaceholderDirectory: t("files.createPlaceholderDirectory"),
        createConfirm: t("files.createConfirm"),
        createCancel: t("files.createCancel"),
        contextOpen: t("files.contextOpen"),
        contextMountDevice: t("files.contextMountDevice"),
        contextMoveToTrash: t("files.contextMoveToTrash"),
        contextRestore: t("files.contextRestore"),
        contextEmptyTrash: t("files.contextEmptyTrash"),
        contextEjectDevice: t("files.contextEjectDevice"),
        viewList: t("files.viewList"),
        viewLarge: t("files.viewLarge"),
        chooserBindProjectLabel: t("files.chooserBindProjectLabel")
      },
      fileEditor: {
        loading: t("editor.loading"),
        unsupported: t("editor.unsupported"),
        unavailable: t("editor.unavailable"),
        readOnly: t("editor.readOnly"),
        conflict: t("editor.conflict"),
        retry: t("editor.retry"),
        save: t("editor.save"),
        openDiff: t("editor.openDiff"),
        closeDiff: t("editor.closeDiff")
      },
      fileEditorReview: {
        accept: t("ai.editorWorkAccept"),
        reject: t("ai.editorWorkReject"),
        undo: t("ai.editorWorkUndo"),
        previous: t("ai.editorWorkPrevious"),
        next: t("ai.editorWorkNext"),
        acceptAll: t("ai.editorWorkAcceptAll")
      },
      notificationTopbar: {
        openCenter: t("notification.topbarOpenCenter"),
        openPreview: t("notification.topbarOpenPreview")
      },
      notificationCenter: {
        title: t("notification.centerTitle"),
        listTitle: t("notification.centerListTitle"),
        emptyState: t("notification.centerEmptyState"),
        detailEmpty: t("notification.centerDetailEmpty"),
        markAllRead: t("notification.centerMarkAllRead"),
        clearAll: t("notification.centerClearAll"),
        openSource: t("notification.centerOpenSource"),
        sourceFallback: t("notification.centerSourceFallback"),
        unread: t("notification.centerUnread")
      },
      workspaceI18n: {
        searchPlaceholder: t("browser.searchPlaceholder"),
        searchActionLabel: t("browser.searchAction"),
        resultsHeading: t("browser.resultsHeading"),
        resultsBlendTitle: t("browser.resultsBlendTitle"),
        resultsEngineOverview: t("browser.resultsEngineOverview"),
        resultsNoResults: t("browser.resultsNoResults"),
        resultsEngineError: t("browser.resultsEngineError"),
        resultsOfficial: t("browser.resultsOfficial"),
        resultsOfficialHomepage: t("browser.resultsOfficialHomepage"),
        resultsOfficialSubsite: t("browser.resultsOfficialSubsite"),
        resultsOfficialDocs: t("browser.resultsOfficialDocs"),
        resultsOfficialLogin: t("browser.resultsOfficialLogin"),
        resultsOfficialDownload: t("browser.resultsOfficialDownload"),
        resultsOfficialSupport: t("browser.resultsOfficialSupport"),
        resultsSourceFilter: t("browser.resultsSourceFilter"),
        resultsAllTab: t("browser.resultsAllTab"),
        resultsWebTab: t("browser.resultsWebTab"),
        resultsLocalTab: t("browser.resultsLocalTab"),
        resultsLocalTitle: t("browser.resultsLocalTitle"),
        resultsLocalPanelTitle: t("browser.resultsLocalPanelTitle"),
        resultsLocalNoMatches: t("browser.resultsLocalNoMatches"),
        resultsLocalSearchingMore: t("browser.resultsLocalSearchingMore"),
        resultsLocalScope: t("browser.resultsLocalScope"),
        resultsLocalScannedFiles: t("browser.resultsLocalScannedFiles"),
        resultsLocalScannedDirs: t("browser.resultsLocalScannedDirs"),
        resultsLocalContentScans: t("browser.resultsLocalContentScans"),
        resultsLocalMatched: t("browser.resultsLocalMatched"),
        resultsLocalIndex: t("browser.resultsLocalIndex"),
        resultsLocalScore: t("browser.resultsLocalScore"),
        resultsLocalLine: t("browser.resultsLocalLine"),
        channelIdle: t("browser.channelIdle"),
        channelLoading: t("browser.channelLoading"),
        channelReady: t("browser.channelReady"),
        channelError: t("browser.channelError"),
        deepSearchToggle: t("browser.deepSearchToggle"),
        deepSearchChip: t("browser.deepSearchChip"),
        deepSearchHeading: t("browser.deepSearchHeading"),
        deepSearchStop: t("browser.deepSearchStop"),
        deepSearchFitView: t("browser.deepSearchFitView"),
        deepSearchResetLayout: t("browser.deepSearchResetLayout"),
        deepSearchLoading: t("browser.deepSearchLoading"),
        deepSearchEmpty: t("browser.deepSearchEmpty"),
        deepSearchOverview: t("browser.deepSearchOverview"),
        deepSearchSelectedNode: t("browser.deepSearchSelectedNode"),
        deepSearchPhase: t("browser.deepSearchPhase"),
        deepSearchBudget: t("browser.deepSearchBudget"),
        deepSearchWebStatus: t("browser.deepSearchWebStatus"),
        deepSearchLocalStatus: t("browser.deepSearchLocalStatus"),
        deepSearchDeduped: t("browser.deepSearchDeduped"),
        deepSearchDerived: t("browser.deepSearchDerived"),
        deepSearchRounds: t("browser.deepSearchRounds"),
        deepSearchOpen: t("browser.deepSearchOpen"),
        deepSearchExpand: t("browser.deepSearchExpand"),
        deepSearchCenter: t("browser.deepSearchCenter"),
        deepSearchNoSelection: t("browser.deepSearchNoSelection"),
        deepSearchAll: t("browser.deepSearchAll"),
        deepSearchSnippet: t("browser.deepSearchSnippet"),
        deepSearchSource: t("browser.deepSearchSource"),
        deepSearchConnectedLinks: t("browser.deepSearchConnectedLinks"),
        deepSearchEdgeFilters: t("browser.deepSearchEdgeFilters"),
        deepSearchDirection: t("browser.deepSearchDirection"),
        deepSearchIncoming: t("browser.deepSearchIncoming"),
        deepSearchOutgoing: t("browser.deepSearchOutgoing"),
        deepSearchBoth: t("browser.deepSearchBoth"),
        deepSearchDiscovered: t("browser.deepSearchDiscovered"),
        deepSearchExpanded: t("browser.deepSearchExpanded"),
        deepSearchRelated: t("browser.deepSearchRelated"),
        deepSearchHostsSubdomain: t("browser.deepSearchHostsSubdomain"),
        deepSearchContainsPage: t("browser.deepSearchContainsPage"),
        deepSearchLineage: t("browser.deepSearchLineage"),
        deepSearchAlternateLinks: t("browser.deepSearchAlternateLinks"),
        deepSearchRevealInManager: t("browser.deepSearchRevealInManager"),
        deepSearchMatchKind: t("browser.deepSearchMatchKind"),
        deepSearchLine: t("browser.deepSearchLine"),
        deepSearchSharedTerms: t("browser.deepSearchSharedTerms"),
        deepSearchDomain: t("browser.deepSearchDomain"),
        deepSearchSubdomain: t("browser.deepSearchSubdomain"),
        deepSearchPage: t("browser.deepSearchPage"),
        deepSearchVerified: t("browser.deepSearchVerified"),
        deepSearchGuessed: t("browser.deepSearchGuessed"),
        deepSearchDiscoveredBy: t("browser.deepSearchDiscoveredBy"),
        deepSearchVerificationScore: t("browser.deepSearchVerificationScore"),
        deepSearchGuessedDomains: t("browser.deepSearchGuessedDomains"),
        deepSearchVerifiedDomains: t("browser.deepSearchVerifiedDomains"),
        deepSearchSubdomains: t("browser.deepSearchSubdomains"),
        deepSearchVisitedPages: t("browser.deepSearchVisitedPages"),
        deepSearchQueuedPages: t("browser.deepSearchQueuedPages"),
        deepSearchDroppedPages: t("browser.deepSearchDroppedPages"),
        deepSearchSiteExpansionStatus: t("browser.deepSearchSiteExpansionStatus")
      } satisfies WorkspaceSurfaceI18nProps,
      aiHistory: {
        title: t("ai.historyTitle"),
        newSessionTitle: t("ai.sessionDefaultTitle"),
        newConversationLabel: t("ai.newConversation"),
        openConversationLabel: t("ai.openConversation"),
        renameConversationLabel: t("ai.renameConversation"),
        deleteConversationLabel: t("ai.deleteConversation"),
        archiveConversationLabel: t("ai.archiveConversation"),
        archivedConversationLabel: t("ai.historyArchivedConversations"),
        archivedProjectLabel: t("ai.historyArchivedProjects"),
        deleteArchivedConversationTitle: t("ai.deleteArchivedConversationTitle"),
        deleteArchivedConversationDescription: t("ai.deleteArchivedConversationDescription"),
        deleteArchivedConversationConfirm: t("ai.deleteArchivedConversationConfirm"),
        deleteArchivedConversationCancel: t("ai.deleteArchivedConversationCancel"),
        profileLabel: t("ai.profileLabel"),
        sessionIdLabel: t("ai.historySessionIdLabel"),
        loadingSessionsLabel: t("ai.historyLoadingSessions"),
        emptyStateTitle: t("settings.aiEmptyTitle"),
        emptyStateDescription: t("settings.aiEmptyDescription"),
        scopeGlobalLabel: t("ai.historyScopeGlobal"),
        scopeProjectLabel: t("ai.historyScopeProject"),
        noProjectSessionsEmptyLabel: t("ai.historyNoProjectSessionsEmpty"),
        noProjectsEmptyLabel: t("ai.historyNoProjectsEmpty"),
        projectSessionCountLabel: t("ai.historyProjectSessionCount"),
        backToProjectsLabel: t("ai.historyBackToProjects"),
        projectPathLabel: t("ai.historyProjectPathLabel"),
        threadPreviewEmptyLabel: t("ai.historyThreadPreviewEmpty"),
        previewEmptyTitle: t("ai.historyPreviewEmptyTitle"),
        previewEmptyDescription: t("ai.historyPreviewEmptyDescription"),
        previewLoadingLabel: t("ai.historyPreviewLoading")
      },
      skillsCenter: {
        title: t("skills.title"),
        sidebarDescription: t("skills.sidebarDescription"),
        sidebarScope: t("skills.sidebarScope"),
        sidebarStatus: t("skills.sidebarStatus"),
        sidebarSources: t("skills.sidebarSources"),
        sidebarCategories: t("skills.sidebarCategories"),
        sidebarBuiltin: t("skills.sidebarBuiltin"),
        sidebarInstalledGlobal: t("skills.sidebarInstalledGlobal"),
        sidebarInstalledProject: t("skills.sidebarInstalledProject"),
        scopeGlobal: t("skills.scopeGlobal"),
        scopeProject: t("skills.scopeProject"),
        scopeProjectUnavailable: t("skills.scopeProjectUnavailable"),
        statusAll: t("skills.statusAll"),
        statusEnabled: t("skills.statusEnabled"),
        statusDisabled: t("skills.statusDisabled"),
        statusUntrusted: t("skills.statusUntrusted"),
        sourceAll: t("skills.sourceAll"),
        sourceBuiltin: t("skills.sourceBuiltin"),
        sourceLyra: t("skills.sourceLyra"),
        sourceClaude: t("skills.sourceClaude"),
        sourceContinue: t("skills.sourceContinue"),
        toolbarInstalled: t("skills.toolbarInstalled"),
        toolbarInstalledDescription: t("skills.toolbarInstalledDescription"),
        actionOpenCatalog: t("skills.actionOpenCatalog"),
        actionOpenImport: t("skills.actionOpenImport"),
        actionOpenCreate: t("skills.actionOpenCreate"),
        actionRefresh: t("skills.actionRefresh"),
        actionInstallBuiltin: t("skills.actionInstallBuiltin"),
        actionDiscoverImport: t("skills.actionDiscoverImport"),
        actionImportSelected: t("skills.actionImportSelected"),
        actionCreateSkill: t("skills.actionCreateSkill"),
        actionCancel: t("skills.actionCancel"),
        actionTrust: t("skills.actionTrust"),
        actionUntrust: t("skills.actionUntrust"),
        actionEnable: t("skills.actionEnable"),
        actionDisable: t("skills.actionDisable"),
        actionDelete: t("skills.actionDelete"),
        actionViewDetails: t("skills.actionViewDetails"),
        catalog: t("skills.catalog"),
        details: t("skills.details"),
        importTitle: t("skills.importTitle"),
        importDescription: t("skills.importDescription"),
        createTitle: t("skills.createTitle"),
        createDescription: t("skills.createDescription"),
        fieldName: t("skills.fieldName"),
        fieldDescription: t("skills.fieldDescription"),
        fieldCategory: t("skills.fieldCategory"),
        fieldAuthor: t("skills.fieldAuthor"),
        fieldSkillType: t("skills.fieldSkillType"),
        fieldTriggerSummary: t("skills.fieldTriggerSummary"),
        fieldContent: t("skills.fieldContent"),
        fieldSource: t("skills.fieldSource"),
        fieldVersion: t("skills.fieldVersion"),
        fieldTrust: t("skills.fieldTrust"),
        fieldEnable: t("skills.fieldEnable"),
        fieldFiles: t("skills.fieldFiles"),
        fieldScripts: t("skills.fieldScripts"),
        fieldCompatibility: t("skills.fieldCompatibility"),
        fieldEntry: t("skills.fieldEntry"),
        fieldPath: t("skills.fieldPath"),
        fieldLastError: t("skills.fieldLastError"),
        fieldPackagePath: t("skills.fieldPackagePath"),
        fieldOverride: t("skills.fieldOverride"),
        fieldContentPreview: t("skills.fieldContentPreview"),
        importPathLabel: t("skills.importPathLabel"),
        importPathPlaceholder: t("skills.importPathPlaceholder"),
        importPreviewTitle: t("skills.importPreviewTitle"),
        importPreviewEmpty: t("skills.importPreviewEmpty"),
        importPreviewScripts: t("skills.importPreviewScripts"),
        importPreviewResources: t("skills.importPreviewResources"),
        importPreviewErrors: t("skills.importPreviewErrors"),
        emptySelection: t("skills.emptySelection"),
        emptyInstalled: t("skills.emptyInstalled"),
        emptyCatalog: t("skills.emptyCatalog"),
        emptyImport: t("skills.emptyImport"),
        typePrompt: t("skills.typePrompt"),
        typeWorkflow: t("skills.typeWorkflow"),
        typeResource: t("skills.typeResource"),
        typeToolGuidance: t("skills.typeToolGuidance"),
        trustTrusted: t("skills.trustTrusted"),
        trustUntrusted: t("skills.trustUntrusted"),
        enableEnabled: t("skills.enableEnabled"),
        enableDisabled: t("skills.enableDisabled"),
        overrideInherited: t("skills.overrideInherited"),
        overrideProjectOnly: t("skills.overrideProjectOnly"),
        overrideGlobalOnly: t("skills.overrideGlobalOnly"),
        untrustedWarning: t("skills.untrustedWarning"),
        createDefaultContent: t("skills.createDefaultContent")
      },
      pluginsCenter: {
        title: t("plugins.title"),
        description: t("plugins.description"),
        statusAll: t("plugins.statusAll"),
        statusInstalled: t("plugins.statusInstalled"),
        statusEnabled: t("plugins.statusEnabled"),
        statusDisabled: t("plugins.statusDisabled"),
        statusAvailable: t("plugins.statusAvailable"),
        actionRefresh: t("plugins.actionRefresh"),
        actionInstall: t("plugins.actionInstall"),
        actionUninstall: t("plugins.actionUninstall"),
        actionEnable: t("plugins.actionEnable"),
        actionDisable: t("plugins.actionDisable"),
        details: t("plugins.details"),
        marketplace: t("plugins.marketplace"),
        fieldDescription: t("plugins.fieldDescription"),
        fieldSkills: t("plugins.fieldSkills"),
        fieldMcpServers: t("plugins.fieldMcpServers"),
        fieldApps: t("plugins.fieldApps"),
        fieldCapabilities: t("plugins.fieldCapabilities"),
        fieldPolicies: t("plugins.fieldPolicies"),
        fieldSource: t("plugins.fieldSource"),
        empty: t("plugins.empty"),
        emptySelection: t("plugins.emptySelection"),
        noDescription: t("plugins.noDescription"),
        noSkills: t("plugins.noSkills"),
        noMcpServers: t("plugins.noMcpServers"),
        noApps: t("plugins.noApps"),
        noCapabilities: t("plugins.noCapabilities"),
        installed: t("plugins.installed"),
        available: t("plugins.available"),
        enabled: t("plugins.enabled"),
        disabled: t("plugins.disabled"),
        loadErrors: t("plugins.loadErrors"),
        sourceLocal: t("plugins.sourceLocal"),
        sourceGit: t("plugins.sourceGit"),
        sourceRemote: t("plugins.sourceRemote"),
        installNotAvailable: t("plugins.installNotAvailable"),
        installAvailable: t("plugins.installAvailable"),
        installDefault: t("plugins.installDefault"),
        authOnInstall: t("plugins.authOnInstall"),
        authOnUse: t("plugins.authOnUse"),
        appNeedsAuth: t("plugins.appNeedsAuth")
      },
      mcpCenter: {
        title: t("mcp.title"),
        sidebarDescription: t("mcp.sidebarDescription"),
        sidebarScope: t("mcp.sidebarScope"),
        sidebarStatus: t("mcp.sidebarStatus"),
        sidebarSources: t("mcp.sidebarSources"),
        sidebarProjectRoot: t("mcp.sidebarProjectRoot"),
        sidebarGlobalCount: t("mcp.sidebarGlobalCount"),
        sidebarProjectCount: t("mcp.sidebarProjectCount"),
        sidebarOfficialCatalog: t("mcp.sidebarOfficialCatalog"),
        sidebarCustomServers: t("mcp.sidebarCustomServers"),
        scopeGlobal: t("mcp.scopeGlobal"),
        scopeProject: t("mcp.scopeProject"),
        scopeProjectUnavailable: t("mcp.scopeProjectUnavailable"),
        statusAll: t("mcp.statusAll"),
        statusRunning: t("mcp.statusRunning"),
        statusStopped: t("mcp.statusStopped"),
        statusError: t("mcp.statusError"),
        toolbarInstalled: t("mcp.toolbarInstalled"),
        toolbarInstalledDescription: t("mcp.toolbarInstalledDescription"),
        installed: t("mcp.installed"),
        details: t("mcp.details"),
        catalog: t("mcp.catalog"),
        catalogDescription: t("mcp.catalogDescription"),
        emptySelection: t("mcp.emptySelection"),
        emptyInstalled: t("mcp.emptyInstalled"),
        emptyCatalog: t("mcp.emptyCatalog"),
        fieldTitle: t("mcp.fieldTitle"),
        fieldTransport: t("mcp.fieldTransport"),
        fieldInstallKind: t("mcp.fieldInstallKind"),
        fieldCommand: t("mcp.fieldCommand"),
        fieldArguments: t("mcp.fieldArguments"),
        fieldCwd: t("mcp.fieldCwd"),
        fieldUrl: t("mcp.fieldUrl"),
        fieldConnection: t("mcp.fieldConnection"),
        fieldEnvironment: t("mcp.fieldEnvironment"),
        fieldPermissions: t("mcp.fieldPermissions"),
        fieldRuntime: t("mcp.fieldRuntime"),
        fieldOverride: t("mcp.fieldOverride"),
        fieldSource: t("mcp.fieldSource"),
        fieldValidation: t("mcp.fieldValidation"),
        fieldCapabilities: t("mcp.fieldCapabilities"),
        fieldTools: t("mcp.fieldTools"),
        fieldResources: t("mcp.fieldResources"),
        fieldPrompts: t("mcp.fieldPrompts"),
        fieldLastError: t("mcp.fieldLastError"),
        actionEdit: t("mcp.actionEdit"),
        actionStart: t("mcp.actionStart"),
        actionStop: t("mcp.actionStop"),
        actionRestart: t("mcp.actionRestart"),
        actionValidate: t("mcp.actionValidate"),
        actionDelete: t("mcp.actionDelete"),
        actionSave: t("mcp.actionSave"),
        actionCancel: t("mcp.actionCancel"),
        actionInstall: t("mcp.actionInstall"),
        actionRefresh: t("mcp.actionRefresh"),
        actionOpenCustom: t("mcp.actionOpenCustom"),
        actionAddEnvironment: t("mcp.actionAddEnvironment"),
        actionReadCapabilities: t("mcp.actionReadCapabilities"),
        toggleAdvanced: t("mcp.toggleAdvanced"),
        advancedInvalid: t("mcp.advancedInvalid"),
        validationOk: t("mcp.validationOk"),
        validationFailed: t("mcp.validationFailed"),
        validationIdle: t("mcp.validationIdle"),
        noIntrospection: t("mcp.noIntrospection"),
        noEnvironment: t("mcp.noEnvironment"),
        noPermissions: t("mcp.noPermissions"),
        sourceOfficial: t("mcp.sourceOfficial"),
        sourceCustom: t("mcp.sourceCustom"),
        recommendedScope: t("mcp.recommendedScope"),
        enabled: t("mcp.enabled"),
        autoStart: t("mcp.autoStart"),
        modePlain: t("mcp.modePlain"),
        modeSecret: t("mcp.modeSecret"),
        modeExternal: t("mcp.modeExternal"),
        transportStdio: t("mcp.transportStdio"),
        transportSse: t("mcp.transportSse"),
        transportHttp: t("mcp.transportHttp"),
        installKindNpm: t("mcp.installKindNpm"),
        installKindUv: t("mcp.installKindUv"),
        installKindDocker: t("mcp.installKindDocker"),
        installKindBinary: t("mcp.installKindBinary"),
        installKindManual: t("mcp.installKindManual"),
        runtimeStarting: t("mcp.runtimeStarting"),
        runtimeRunning: t("mcp.runtimeRunning"),
        runtimeStopped: t("mcp.runtimeStopped"),
        runtimeError: t("mcp.runtimeError"),
        runtimeValidating: t("mcp.runtimeValidating"),
        projectOverrideInactive: t("mcp.projectOverrideInactive"),
        inheritedFromGlobal: t("mcp.inheritedFromGlobal"),
        formNew: t("mcp.formNew"),
        formEdit: t("mcp.formEdit"),
        formSummary: t("mcp.formSummary"),
        formDescription: t("mcp.formDescription"),
        formIconKey: t("mcp.formIconKey"),
        formEnvironmentKey: t("mcp.formEnvironmentKey"),
        formEnvironmentValue: t("mcp.formEnvironmentValue"),
        formEnvironmentExternal: t("mcp.formEnvironmentExternal"),
        formEnvironmentSecret: t("mcp.formEnvironmentSecret"),
        formRaw: t("mcp.formRaw"),
        customDescription: t("mcp.customDescription"),
        fieldSummary: t("mcp.fieldSummary"),
        fieldDescription: t("mcp.fieldDescription"),
        fieldIconKey: t("mcp.fieldIconKey"),
        presetTitle: t("mcp.presetTitle"),
        presetDescription: t("mcp.presetDescription"),
        actionQuickSetup: t("mcp.actionQuickSetup"),
        presetFieldRootPath: t("mcp.presetFieldRootPath"),
        presetFieldRepoPath: t("mcp.presetFieldRepoPath"),
        presetFieldTimezone: t("mcp.presetFieldTimezone"),
        presetHintProjectDefault: t("mcp.presetHintProjectDefault"),
        presetPlaceholderPath: t("mcp.presetPlaceholderPath"),
        presetPlaceholderTimezone: t("mcp.presetPlaceholderTimezone")
      }
    }),
    [t]
  );

export type WorkbenchLabels = ReturnType<typeof useWorkbenchLabels>;
