// Shared browser-preview translations for the interactive shell and film.
// This is not an installable native language pack; film storage stays isolated.
export const filmChinese: Record<string, string> = {
  "browser.homeTabTitle": "首页",
  "navigation.titlebarPlaceholder": "搜索、输入网址或文件路径",
  "settings.open": "打开设置",
  "settings.tabTitle": "设置",
  "settings.pageTitle": "设置",
  "settings.generalCategoryLabel": "通用",
  "settings.appearanceCategoryLabel": "外观",
  "settings.workspaceCategoryLabel": "工作区",
  "settings.downloadsCategoryLabel": "下载",
  "settings.notificationsCategoryLabel": "通知",
  "settings.docsNavLabel": "文档",
  "settings.languageLabel": "语言",
  "settings.languageSearchPlaceholder": "搜索语言",
  "settings.languageStatusCurrent": "当前",
  "settings.languageStatusInstalled": "已安装",
  "settings.languageStatusAvailable": "安装",
  "settings.languageRemove": "移除",
  "settings.themeLabel": "主题",
  "settings.uiFontSizeLabel": "界面文字大小",
  "settings.windowMaterialLabel": "系统材质背景",
  "settings.windowMaterialDescription": "使用系统模糊和半透明窗口背景。",
  "settings.windowMaterialEnabled": "已启用",
  "settings.windowMaterialDisabled": "已关闭",
  "settings.preventSleepLabel": "保持唤醒",
  "settings.preventSleepDescription": "启用后，Lyra 运行时会保持系统唤醒。",
  "settings.importSettingsCategoryLabel": "导入设置",
  "ai.panelTitle": "会话",
  "ai.launchVerbDiscuss": "讨论",
  "ai.launchVerbCode": "编程",
  "ai.launchVerbThink": "思考",
  "ai.launchVerbExplore": "探索",
  "ai.launchVerbBuild": "构建",
  "ai.launchVerbDebug": "调试",
  "ai.launchVerbCollaborate": "协作",
  "ai.launchVerbChat": "聊天",
  "ai.sessionDefaultTitle": "新会话",
  "ai.modelLabel": "模型",
  "header.newSession": "新会话",
  "aiPanel.defaultSessionTitle": "新会话",
  "ai.movePanelToLeft": "将面板移到左侧",
  "ai.movePanelToRight": "将面板移到右侧",
  "header.more": "更多",
  "lyra-agents-empty.questionPrefix": "你想在 ",
  "lyra-agents-empty.questionSuffix": " 中做什么？",
  "lyra-agents-composer.placeholder": "向 Lyra 发送消息",
  "lyra-agents-composer.send": "发送",
  "lyra-agents-composer.pause": "暂停",
  "lyra-agents-composer.attach": "添加附件",
  "lyra-agents-composer.modelControls": "模型",
  "lyra-agents-composer.modelList": "模型列表",
  "lyra-agents-composer.permissionMode": "权限模式",
  "lyra-agents-composer.permissionModeList": "权限模式",
  "lyra-agents-composer.permissionModeApproval": "审批",
  "lyra-agents-composer.permissionModeFullAuto": "托管",
  "lyra-agents-composer.permissionModeAutonomous": "全自动",
  "lyra-agents-composer.permissionModeCustom": "自定义",
  "lyra-agents-composer.chooseProject": "选择项目",
  "lyra-agents-composer.newProject": "新建项目",
  "settings.theme.lyra-light": "Lyra 浅色",
  "settings.theme.lyra-dark": "Lyra 深色",
  "settings.theme.lyra-system": "跟随系统",
  "settings.experimentalCategoryLabel": "实验功能",
  "settings.searchCategoryLabel": "搜索",
  "settings.aiCategoryLabel": "Lyra Agents",
  "settings.modelsCategoryLabel": "模型",
  "settings.skillsCategoryLabel": "技能",
  "settings.mcpCategoryLabel": "MCP",
  "browser.goBack": "后退",
  "browser.goForward": "前进",
  "browser.openNewTab": "新标签页",
  "browser.closeTab": "关闭标签页",
  "browser.searchPlaceholder": "搜索或输入网址",
  "browser.resultsAutoTab": "自动",
  "browser.resultsWebTab": "网页",
  "navigation.titlebarAriaLabel": "地址栏",
  "navigation.reloadAction": "重新加载",
  "navigation.elementPickerEnable": "开启元素选择器",
  "navigation.elementPickerDisable": "关闭元素选择器",
  "navigation.elementPickerInspect": "检查",
  "panel.toggleLeft": "切换会话面板",
  "panel.toggleBottom": "切换终端",
  "panel.moveTerminalToTop": "将终端移到上方",
  "panel.moveTerminalToBottom": "将终端移到下方",
  "agentHistory.open": "打开历史记录",
  "files.open": "打开此电脑",
  "notifications.open": "打开通知",
  "terminal.title": "终端",
  "terminal.newTab": "新终端",
  "terminal.newTabWithProfile": "新终端",
  "terminal.splitHorizontal": "水平拆分",
  "terminal.splitVertical": "垂直拆分",
  "terminal.closeTab": "关闭标签页",
  "terminal.closePane": "关闭面板",
  "terminal.renameTab": "重命名",
  "docs.open": "打开文档",
  "docs.tabTitle": "文档",
  "menu.close": "关闭",
  "dialog.cancel": "取消",
  "dialog.copyAction": "复制",
  "dialog.copiedAction": "已复制",
  "lyra-agents-composer.workingDirHome": "首页",
  "tool.agentActivity": "Agent 操作",
  "tool.running": "正在运行…",
  "tool.events": "{count} 次工具调用",
  "tool.events_one": "{count} 次工具调用",
  "tool.events_other": "{count} 次工具调用",
  ...Object.fromEntries([ ["reads", "读取"], ["searches", "搜索"], ["edits", "编辑"], ["commands", "命令"], ["browses", "浏览"], ["asks", "提问"] ].flatMap(([key, label]) => ["", "_one", "_other"].map(suffix => [`tool.summary.${key}${suffix}`, `{count} 次${label}`]))),
};
