// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoApprovalReviewStatus } from "./AutoApprovalReviewStatus";
import type { AutoReviewRiskLevel } from "./AutoReviewRiskLevel";
import type { AutoReviewUserAuthorization } from "./AutoReviewUserAuthorization";

/**
 * [UNSTABLE] Temporary approval auto-review payload used by
 * `item/autoApprovalReview/*` notifications. This shape is expected to change
 * soon.
 */
export type AutoApprovalReview = { status: AutoApprovalReviewStatus, riskLevel: AutoReviewRiskLevel | null, userAuthorization: AutoReviewUserAuthorization | null, rationale: string | null, };
