// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandExecOutputStream } from "./CommandExecOutputStream";

export type CommandExecutionOutputDeltaNotification = { threadId: string, turnId: string, itemId: string, stream: CommandExecOutputStream, delta: string, };
