// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { DynamicToolSideEffects } from "./DynamicToolSideEffects";

export type DynamicToolSpec = { namespace: string | null, name: string, hostMethod?: string, description: string, inputSchema: JsonValue, deferLoading?: boolean, sideEffects: DynamicToolSideEffects | null, approvalMode: string | null, risk: JsonValue | null, modelInputCapabilities: Array<string> | null, };
