// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DynamicToolSideEffects = { level: string | null, mutatesWorkspace: boolean, mutatesMemory: boolean, mutatesExternalSystems: boolean, mutatesSessionState: boolean, opensInteractiveSession: boolean, readsNetwork: boolean, };
