// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyraAiProtocolBehaviorSummary = { reasoningReplayField: string | null, preserveEmptyReasoning: boolean | null, requireAssistantReasoning: boolean | null, toolLoopSupported: boolean | null, };
