// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyraAiModelRuntimeMetadata } from "./LyraAiModelRuntimeMetadata";

export type LyraAiProviderModelEntry = { id: string, name: string, description: string | null, contextWindow: bigint | null, supportsImages: boolean | null, supportsTools: boolean | null, runtimeMetadata: LyraAiModelRuntimeMetadata | null, source: string, };
