// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyraAiProviderFieldSchema } from "./LyraAiProviderFieldSchema";
import type { LyraAiProviderModelEntry } from "./LyraAiProviderModelEntry";

export type LyraAiProviderPreset = { id: string, providerId: string, protocolId: string, label: string, description: string, section: string, iconKey: string, defaultModel: string, discoveryMode: string, capability: string, modelDiscoverySupported: boolean, customHeadersSupported: boolean, customModelsSupported: boolean, runtimeSupported: boolean, simpleFields: Array<string>, connectionFields: Array<LyraAiProviderFieldSchema>, authFields: Array<LyraAiProviderFieldSchema>, defaultConnectionConfig: { [key in string]?: string }, defaultAuthConfig: { [key in string]?: string }, recommendedModels: Array<LyraAiProviderModelEntry>, };
