// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyraAiModelDiscoveryState } from "./LyraAiModelDiscoveryState";
import type { LyraAiProviderModelEntry } from "./LyraAiProviderModelEntry";

export type LyraAiProviderProfile = { id: string, name: string, providerId: string, protocolId: string, runtimeProviderId: string, runtimeSupported: boolean, secretStatus: string, presetId: string | null, connectionConfig: { [key in string]?: string }, authConfig: { [key in string]?: string }, configuredSecretFields: Array<string>, headers: { [key in string]?: string }, model: string, customModels: Array<LyraAiProviderModelEntry>, discoveryState: LyraAiModelDiscoveryState, isDefault: boolean, createdAt: bigint, updatedAt: bigint, };
