// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyraAiProviderCatalogItem } from "./LyraAiProviderCatalogItem";
import type { LyraAiProviderPreset } from "./LyraAiProviderPreset";

export type LyraConfigProvidersCatalogReadResponse = { providers: Array<LyraAiProviderCatalogItem>, presets: Array<LyraAiProviderPreset>, };
