// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyraAiModelRuntimeMetadata = { shellType: string | null, applyPatchToolType: string | null, supportsSearchTool: boolean | null, supportsParallelToolCalls: boolean | null, supportsReasoningSummaries: boolean | null, supportVerbosity: boolean | null, webSearchToolType: string | null, supportsImageDetailOriginal: boolean | null, inputModalities?: Array<string>, supportedTools?: Array<string>, contextWindow: bigint | null, maxContextWindow: bigint | null, effectiveContextWindowPercent: bigint | null, };
