// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanAnnotation } from "../PlanAnnotation";
import type { PlanArtifact } from "../PlanArtifact";
import type { PlanReviewTurnAction } from "./PlanReviewTurnAction";

export type PlanReviewTurnContext = { action: PlanReviewTurnAction, planTurnId: string, planId: string, annotations: Array<PlanAnnotation>, overallFeedback?: string | null, artifactSnapshot: PlanArtifact, };
