// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";

export type ThreadRollbackResponse = {
/**
 * The updated thread after applying the rollback, with `turns` populated.
 */
thread: Thread,
/**
 * The user text from the rolled-back turn, when available.
 */
restoredInput: string | null,
/**
 * Paths that were covered by the rollback file-restore operation.
 */
revertedFiles: Array<string>, };
