// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAiPanelMessageContentPart } from "./ThreadAiPanelMessageContentPart";
import type { ThreadAiPanelMessageRole } from "./ThreadAiPanelMessageRole";

export type ThreadAiPanelMessage = { id: string, sessionId: string, turnId?: string, role: ThreadAiPanelMessageRole, content: string, displayContent?: string, contentParts?: Array<ThreadAiPanelMessageContentPart>, createdAtMs: number, };
