// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRollbackParams = { threadId: string,
/**
 * The turn to roll back from. This turn and all newer turns are removed.
 */
turnId: string,
/**
 * Restore local file changes to the checkpoint captured before `turn_id`.
 *
 * When true, rollback fails before mutating history if Lyra cannot prove the
 * file state can be restored safely.
 */
restoreFiles: boolean, };
