// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ThreadAiPanelToolCallStatus } from "./ThreadAiPanelToolCallStatus";

export type ThreadAiPanelToolCall = { id: string, sessionId: string, turnId: string, toolName: string, input: JsonValue, output?: JsonValue, status: ThreadAiPanelToolCallStatus, startedAtMs: number, finishedAtMs?: number, errorCode?: string, errorMessage?: string, };
