// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeKind } from "../ModeKind";
import type { ThreadAiPanelTurnStatus } from "./ThreadAiPanelTurnStatus";

export type ThreadAiPanelTurn = { id: string, sessionId: string, status: ThreadAiPanelTurnStatus, collaborationMode: ModeKind, createdAtMs: number, updatedAtMs: number, durationMs?: number, errorCode?: string, errorMessage?: string, };
