// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAiPanelTimelineEntryKind } from "./ThreadAiPanelTimelineEntryKind";

export type ThreadAiPanelTimelineEntry = { id: string, sessionId: string, turnId: string, kind: ThreadAiPanelTimelineEntryKind, refId: string, createdAtMs: number, };
