// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAiPanelMessage } from "./ThreadAiPanelMessage";
import type { ThreadAiPanelPendingInteraction } from "./ThreadAiPanelPendingInteraction";
import type { ThreadAiPanelPlan } from "./ThreadAiPanelPlan";
import type { ThreadAiPanelToolCall } from "./ThreadAiPanelToolCall";
import type { ThreadAiPanelTurn } from "./ThreadAiPanelTurn";
import type { ThreadAiPanelTurnMeta } from "./ThreadAiPanelTurnMeta";

export type ThreadAiPanelViewModel = { messages: Array<ThreadAiPanelMessage>, turns: Array<ThreadAiPanelTurn>, toolCalls: Array<ThreadAiPanelToolCall>, plans: Array<ThreadAiPanelPlan>, pendingInteractions?: Array<ThreadAiPanelPendingInteraction>, turnMeta: Array<ThreadAiPanelTurnMeta>, };
