// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAiPanelPlanStep } from "./ThreadAiPanelPlanStep";

export type ThreadAiPanelPlan = { turnId: string, draftText: string, finalText?: string, explanation?: string, steps?: Array<ThreadAiPanelPlanStep>, updatedAtMs: number, };
