// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadReadViewModelParams } from "./ThreadReadViewModelParams";

export type ThreadReadParams = { threadId: string,
/**
 * When true, include turns and their items from rollout history.
 */
includeTurns: boolean,
/**
 * Optional view model projection to build alongside the thread metadata.
 */
viewModel?: ThreadReadViewModelParams, };
