// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ThreadAiPanelPendingInteractionKind } from "./ThreadAiPanelPendingInteractionKind";
import type { ThreadAiPanelPendingInteractionStatus } from "./ThreadAiPanelPendingInteractionStatus";

export type ThreadAiPanelPendingInteraction = { id: string, sessionId: string, turnId: string, kind: ThreadAiPanelPendingInteractionKind, status: ThreadAiPanelPendingInteractionStatus, payload: JsonValue, createdAtMs: number, updatedAtMs: number, };
