// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadAiPanelAttachmentKind } from "./ThreadAiPanelAttachmentKind";

export type ThreadAiPanelMessageContentPart = { "type": "text", text: string, } | { "type": "attachment", name: string, path: string, kind?: ThreadAiPanelAttachmentKind, };
