// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * response for appending realtime text input.
 */
export type ThreadRealtimeAppendTextResponse = Record<string, never>;
