// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies the agent thread that requested input.
 */
export type ToolRequestUserInputSource = { agentThreadId?: string, agentNickname?: string, agentRole?: string, };
