// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolRequestUserInputQuestion } from "./ToolRequestUserInputQuestion";
import type { ToolRequestUserInputSource } from "./ToolRequestUserInputSource";

/**
 * Params sent with an agent_question/request_user_input event.
 */
export type ToolRequestUserInputParams = { threadId: string, turnId: string, itemId: string, reason?: string, source: ToolRequestUserInputSource, questions: Array<ToolRequestUserInputQuestion>, };
