// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanAnnotation } from "../PlanAnnotation";
import type { PlanArtifact } from "../PlanArtifact";
import type { PlanApprovalDecision } from "./PlanApprovalDecision";

export type TurnPlanApprovalResolveParams = { threadId: string, planTurnId: string, planId: string, decision: PlanApprovalDecision, annotations: Array<PlanAnnotation>, feedback?: string | null, artifactSnapshot?: PlanArtifact | null, };
