// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanApprovalDecision } from "./PlanApprovalDecision";

export type TurnPlanApprovalResolveParams = { threadId: string, planTurnId: string, requestId: string, decision: PlanApprovalDecision, feedback?: string | null, proposedMarkdown?: string | null, };
