"use client";

import AlertCircle from "reicon-react/icons/AlertCircle";
import AlertTriangle from "reicon-react/icons/AlertTriangle";
import Archive from "reicon-react/icons/Archive";
import ArrowDown from "reicon-react/icons/ArrowDown";
import ArrowLeft from "reicon-react/icons/ArrowLeft";
import ArrowRight from "reicon-react/icons/ArrowRight";
import ArrowUp from "reicon-react/icons/ArrowUp";
import ArrowUpRight from "reicon-react/icons/ArrowUpRight";
import ArrowUpRightSquare from "reicon-react/icons/ArrowUpRightSquare";
import Bell from "reicon-react/icons/Bell";
import Book from "reicon-react/icons/Book";
import BookOpen from "reicon-react/icons/BookOpen";
import Box from "reicon-react/icons/Box";
import Bug from "reicon-react/icons/Bug";
import Building from "reicon-react/icons/Building";
import Calendar from "reicon-react/icons/Calendar";
import Camera from "reicon-react/icons/Camera";
import Check from "reicon-react/icons/Check";
import CheckCircle from "reicon-react/icons/CheckCircle";
import ChevronDown from "reicon-react/icons/ChevronDown";
import ChevronLeft from "reicon-react/icons/ChevronLeft";
import ChevronRight from "reicon-react/icons/ChevronRight";
import ChevronUp from "reicon-react/icons/ChevronUp";
import Clipboard from "reicon-react/icons/Clipboard";
import Clock from "reicon-react/icons/Clock";
import Code from "reicon-react/icons/Code";
import Command from "reicon-react/icons/Command";
import Cookie from "reicon-react/icons/Cookie";
import Copy from "reicon-react/icons/Copy";
import Cpu from "reicon-react/icons/Cpu";
import Crosshairs from "reicon-react/icons/Crosshairs";
import Database from "reicon-react/icons/Database";
import Download from "reicon-react/icons/Download";
import Edit from "reicon-react/icons/Edit";
import Envelope from "reicon-react/icons/Envelope";
import Eye from "reicon-react/icons/Eye";
import File from "reicon-react/icons/File";
import FilePlus from "reicon-react/icons/FilePlus";
import FileText from "reicon-react/icons/FileText";
import FileZip from "reicon-react/icons/FileZip";
import Fingerprint from "reicon-react/icons/Fingerprint";
import Flask from "reicon-react/icons/Flask";
import Floppy from "reicon-react/icons/Floppy";
import Folder from "reicon-react/icons/Folder";
import FolderOpen from "reicon-react/icons/FolderOpen";
import FolderPlus from "reicon-react/icons/FolderPlus";
import FolderUp from "reicon-react/icons/FolderUp";
import Gear from "reicon-react/icons/Gear";
import Globe from "reicon-react/icons/Globe";
import Grid from "reicon-react/icons/Grid";
import HardDrive from "reicon-react/icons/HardDrive";
import Hashtag from "reicon-react/icons/Hashtag";
import HelpCircle from "reicon-react/icons/HelpCircle";
import Hierarchy from "reicon-react/icons/Hierarchy";
import History from "reicon-react/icons/History";
import Home from "reicon-react/icons/Home";
import Image from "reicon-react/icons/Image";
import Import from "reicon-react/icons/Import";
import InfoCircle from "reicon-react/icons/InfoCircle";
import Key from "reicon-react/icons/Key";
import Layers from "reicon-react/icons/Layers";
import Layout from "reicon-react/icons/Layout";
import Link from "reicon-react/icons/Link";
import List from "reicon-react/icons/List";
import ListCheck from "reicon-react/icons/ListCheck";
import Loader from "reicon-react/icons/Loader";
import Location from "reicon-react/icons/Location";
import Lock from "reicon-react/icons/Lock";
import Login from "reicon-react/icons/Login";
import Logout from "reicon-react/icons/Logout";
import Maximize from "reicon-react/icons/Maximize";
import MessageSquare from "reicon-react/icons/MessageSquare";
import Minimize from "reicon-react/icons/Minimize";
import Minus from "reicon-react/icons/Minus";
import Mobile from "reicon-react/icons/Mobile";
import Monitor from "reicon-react/icons/Monitor";
import Moon from "reicon-react/icons/Moon";
import MoreH from "reicon-react/icons/MoreH";
import Package from "reicon-react/icons/Package";
import Paintbucket from "reicon-react/icons/Paintbucket";
import Palette from "reicon-react/icons/Palette";
import Pause from "reicon-react/icons/Pause";
import Pin from "reicon-react/icons/Pin";
import Play from "reicon-react/icons/Play";
import Plug from "reicon-react/icons/Plug";
import Plus from "reicon-react/icons/Plus";
import Puzzle from "reicon-react/icons/Puzzle";
import Refresh from "reicon-react/icons/Refresh";
import RotateLeft from "reicon-react/icons/RotateLeft";
import RotateRight from "reicon-react/icons/RotateRight";
import Scroll from "reicon-react/icons/Scroll";
import Search from "reicon-react/icons/Search";
import SearchMinus from "reicon-react/icons/SearchMinus";
import SearchPlus from "reicon-react/icons/SearchPlus";
import Settings2 from "reicon-react/icons/Settings2";
import Share from "reicon-react/icons/Share";
import Shield from "reicon-react/icons/Shield";
import ShieldAlert from "reicon-react/icons/ShieldAlert";
import ShieldCheck from "reicon-react/icons/ShieldCheck";
import ShieldOffGlyph from "reicon-react/icons/ShieldOff";
import Sidebar from "reicon-react/icons/Sidebar";
import SidebarBottom from "reicon-react/icons/SidebarBottom";
import SidebarTop from "reicon-react/icons/SidebarTop";
import SliderHorizontal from "reicon-react/icons/SliderHorizontal";
import Sledgehammer from "reicon-react/icons/Sledgehammer";
import Sparkles from "reicon-react/icons/Sparkles";
import SquareTransferH from "reicon-react/icons/SquareTransferH";
import SquareTransferV from "reicon-react/icons/SquareTransferV";
import Star from "reicon-react/icons/Star";
import StarOff from "reicon-react/icons/StarOff";
import Store from "reicon-react/icons/Store";
import Sun from "reicon-react/icons/Sun";
import Target from "reicon-react/icons/Target";
import TerminalSquare from "reicon-react/icons/TerminalSquare";
import TextTool from "reicon-react/icons/TextTool";
import Timer from "reicon-react/icons/Timer";
import TransferH from "reicon-react/icons/TransferH";
import Trash from "reicon-react/icons/Trash";
import Undo from "reicon-react/icons/Undo";
import User from "reicon-react/icons/User";
import UserCircle from "reicon-react/icons/UserCircle";
import VolumeHigh from "reicon-react/icons/VolumeHigh";
import VolumeX from "reicon-react/icons/VolumeX";
import Wifi from "reicon-react/icons/Wifi";
import Window from "reicon-react/icons/Window";
import X from "reicon-react/icons/X";
import XCircle from "reicon-react/icons/XCircle";

import { CirclePrimitive, GitBranchPrimitive, SquarePrimitive } from "./primitives";
import { wrapReicon } from "./wrap";

export const AlertTriangleIcon = wrapReicon(AlertTriangle, "AlertTriangle");
export { AlertTriangleIcon as AlertTriangle };
export const AppWindow = wrapReicon(Window, "AppWindow");
export const ArchiveIcon = wrapReicon(Archive, "Archive");
export { ArchiveIcon as Archive };
export const ArrowDownIcon = wrapReicon(ArrowDown, "ArrowDown");
export { ArrowDownIcon as ArrowDown };
export const ArrowLeftToLine = wrapReicon(ArrowLeft, "ArrowLeftToLine");
export const ArrowRightIcon = wrapReicon(ArrowRight, "ArrowRight");
export { ArrowRightIcon as ArrowRight };
export const ArrowRightLeft = wrapReicon(TransferH, "ArrowRightLeft");
export const ArrowRightToLine = wrapReicon(ArrowRight, "ArrowRightToLine");
export const ArrowUpIcon = wrapReicon(ArrowUp, "ArrowUp");
export { ArrowUpIcon as ArrowUp };
export const ArrowUpRightIcon = wrapReicon(ArrowUpRight, "ArrowUpRight");
export { ArrowUpRightIcon as ArrowUpRight };
export const BadgeCheck = wrapReicon(CheckCircle, "BadgeCheck");
export const BellIcon = wrapReicon(Bell, "Bell");
export { BellIcon as Bell };
export const BinaryIcon = wrapReicon(Code, "Binary");
export { BinaryIcon as Binary };
export const BookOpenIcon = wrapReicon(BookOpen, "BookOpen");
export { BookOpenIcon as BookOpen };
export const BookText = wrapReicon(Book, "BookText");
export const Bot = wrapReicon(Cpu, "Bot");
export const BoxIcon = wrapReicon(Box, "Box");
export { BoxIcon as Box };
export const Boxes = wrapReicon(Box, "Boxes");
export const Braces = wrapReicon(Code, "Braces");
export const BugIcon = wrapReicon(Bug, "Bug");
export { BugIcon as Bug };
export const Building2 = wrapReicon(Building, "Building2");
export const CalendarIcon = wrapReicon(Calendar, "Calendar");
export { CalendarIcon as Calendar };
export const CalendarClock = wrapReicon(Calendar, "CalendarClock");
export const CameraIcon = wrapReicon(Camera, "Camera");
export { CameraIcon as Camera };
export const CheckIcon = wrapReicon(Check, "Check");
export { CheckIcon as Check };
export const CheckCheck = wrapReicon(ListCheck, "CheckCheck");
export const CheckCircleIcon = wrapReicon(CheckCircle, "CheckCircle");
export { CheckCircleIcon as CheckCircle };
export const CheckCircle2 = wrapReicon(CheckCircle, "CheckCircle2");
export const ChevronDownIcon = wrapReicon(ChevronDown, "ChevronDown");
export { ChevronDownIcon as ChevronDown };
export const ChevronLeftIcon = wrapReicon(ChevronLeft, "ChevronLeft");
export { ChevronLeftIcon as ChevronLeft };
export const ChevronRightIcon = wrapReicon(ChevronRight, "ChevronRight");
export { ChevronRightIcon as ChevronRight };
export const ChevronUpIcon = wrapReicon(ChevronUp, "ChevronUp");
export { ChevronUpIcon as ChevronUp };
export const CircleIcon = wrapReicon(CirclePrimitive, "Circle");
export { CircleIcon as Circle };
export const CircleAlert = wrapReicon(AlertCircle, "CircleAlert");
export const CircleUserRound = wrapReicon(UserCircle, "CircleUserRound");
export const ClipboardPaste = wrapReicon(Clipboard, "ClipboardPaste");
export const ClockIcon = wrapReicon(Clock, "Clock");
export { ClockIcon as Clock };
export const Clock3 = wrapReicon(Clock, "Clock3");
export const Cog = wrapReicon(Gear, "Cog");
export const CommandIcon = wrapReicon(Command, "Command");
export { CommandIcon as Command };
export const Container = wrapReicon(Box, "Container");
export const CookieIcon = wrapReicon(Cookie, "Cookie");
export { CookieIcon as Cookie };
export const CopyIcon = wrapReicon(Copy, "Copy");
export { CopyIcon as Copy };
export const CopyPlus = wrapReicon(Copy, "CopyPlus");
export const CornerUpLeft = wrapReicon(Undo, "CornerUpLeft");
export const CrosshairIcon = wrapReicon(Crosshairs, "Crosshair");
export { CrosshairIcon as Crosshair };
export const DatabaseIcon = wrapReicon(Database, "Database");
export { DatabaseIcon as Database };
export const Diff = wrapReicon(TransferH, "Diff");
export const DownloadIcon = wrapReicon(Download, "Download");
export { DownloadIcon as Download };
export const ExternalLink = wrapReicon(ArrowUpRightSquare, "ExternalLink");
export const EyeIcon = wrapReicon(Eye, "Eye");
export { EyeIcon as Eye };
export const FileIcon = wrapReicon(File, "File");
export { FileIcon as File };
export const FileArchiveIcon = wrapReicon(FileZip, "FileArchive");
export { FileArchiveIcon as FileArchive };
export const FileAudio2 = wrapReicon(File, "FileAudio2");
export const FileCodeIcon = wrapReicon(Code, "FileCode");
export { FileCodeIcon as FileCode };
export const FileCode2 = wrapReicon(Code, "FileCode2");
export const FileCog = wrapReicon(Gear, "FileCog");
export const FileDiff = wrapReicon(File, "FileDiff");
export const FileImageIcon = wrapReicon(Image, "FileImage");
export { FileImageIcon as FileImage };
export const FileJson = wrapReicon(Code, "FileJson");
export const FileJson2 = wrapReicon(Code, "FileJson2");
export const FileLock2 = wrapReicon(Lock, "FileLock2");
export const FilePenLine = wrapReicon(Edit, "FilePenLine");
export const FilePlusIcon = wrapReicon(FilePlus, "FilePlus");
export { FilePlusIcon as FilePlus };
export const FilePlus2 = wrapReicon(FilePlus, "FilePlus2");
export const FileSpreadsheet = wrapReicon(Grid, "FileSpreadsheet");
export const FileTextIcon = wrapReicon(FileText, "FileText");
export { FileTextIcon as FileText };
export const FileType = wrapReicon(TextTool, "FileType");
export const FileType2 = wrapReicon(TextTool, "FileType2");
export const FileVideo2 = wrapReicon(File, "FileVideo2");
export const FingerprintIcon = wrapReicon(Fingerprint, "Fingerprint");
export { FingerprintIcon as Fingerprint };
export const FlaskConical = wrapReicon(Flask, "FlaskConical");
export const FolderIcon = wrapReicon(Folder, "Folder");
export { FolderIcon as Folder };
export const FolderGit2 = wrapReicon(Folder, "FolderGit2");
export const FolderOpenIcon = wrapReicon(FolderOpen, "FolderOpen");
export { FolderOpenIcon as FolderOpen };
export const FolderPlusIcon = wrapReicon(FolderPlus, "FolderPlus");
export { FolderPlusIcon as FolderPlus };
export const FolderTree = wrapReicon(Hierarchy, "FolderTree");
export const FolderUpIcon = wrapReicon(FolderUp, "FolderUp");
export { FolderUpIcon as FolderUp };
export const FoldersIcon = wrapReicon(Folder, "Folders");
export { FoldersIcon as Folders };
export const GitBranchIcon = wrapReicon(GitBranchPrimitive, "GitBranch");
export { GitBranchIcon as GitBranch };
export const GitCommitHorizontal = wrapReicon(CirclePrimitive, "GitCommitHorizontal");
export const GitCompareArrows = wrapReicon(TransferH, "GitCompareArrows");
export const GlobeIcon = wrapReicon(Globe, "Globe");
export { GlobeIcon as Globe };
export const HammerIcon = wrapReicon(Sledgehammer, "Hammer");
export { HammerIcon as Hammer };
export const HardDriveIcon = wrapReicon(HardDrive, "HardDrive");
export { HardDriveIcon as HardDrive };
export const HardDriveDownload = wrapReicon(Download, "HardDriveDownload");
export const HashIcon = wrapReicon(Hashtag, "Hash");
export { HashIcon as Hash };
export const HelpCircleIcon = wrapReicon(HelpCircle, "HelpCircle");
export { HelpCircleIcon as HelpCircle };
export const HistoryIcon = wrapReicon(History, "History");
export { HistoryIcon as History };
export const HouseIcon = wrapReicon(Home, "House");
export { HouseIcon as House };
export const ImageIcon = wrapReicon(Image, "Image");
export { ImageIcon as Image };
export const ImportIcon = wrapReicon(Import, "Import");
export { ImportIcon as Import };
export const InfoIcon = wrapReicon(InfoCircle, "Info");
export { InfoIcon as Info };
export const KeyRound = wrapReicon(Key, "KeyRound");
export const Layers3 = wrapReicon(Layers, "Layers3");
export const LayoutGrid = wrapReicon(Grid, "LayoutGrid");
export const Link2 = wrapReicon(Link, "Link2");
export const ListIcon = wrapReicon(List, "List");
export { ListIcon as List };
export const ListChecksIcon = wrapReicon(ListCheck, "ListChecks");
export { ListChecksIcon as ListChecks };
export const Loader2 = wrapReicon(Loader, "Loader2");
export const LockIcon = wrapReicon(Lock, "Lock");
export { LockIcon as Lock };
export const LogIn = wrapReicon(Login, "LogIn");
export const LogOut = wrapReicon(Logout, "LogOut");
export const Mail = wrapReicon(Envelope, "Mail");
export const MapPinIcon = wrapReicon(Location, "MapPin");
export { MapPinIcon as MapPin };
export const Maximize2 = wrapReicon(Maximize, "Maximize2");
export const MessageSquareIcon = wrapReicon(MessageSquare, "MessageSquare");
export { MessageSquareIcon as MessageSquare };
export const Minimize2 = wrapReicon(Minimize, "Minimize2");
export const MinusIcon = wrapReicon(Minus, "Minus");
export { MinusIcon as Minus };
export const MonitorIcon = wrapReicon(Monitor, "Monitor");
export { MonitorIcon as Monitor };
export const MoonIcon = wrapReicon(Moon, "Moon");
export { MoonIcon as Moon };
export const MoreHorizontal = wrapReicon(MoreH, "MoreHorizontal");
export const PackageIcon = wrapReicon(Package, "Package");
export { PackageIcon as Package };
export const PackageOpen = wrapReicon(Package, "PackageOpen");
export const PaintBucketIcon = wrapReicon(Paintbucket, "PaintBucket");
export { PaintBucketIcon as PaintBucket };
export const PaletteIcon = wrapReicon(Palette, "Palette");
export { PaletteIcon as Palette };
export const PanelBottom = wrapReicon(SidebarBottom, "PanelBottom");
export const PanelBottomOpen = wrapReicon(SidebarBottom, "PanelBottomOpen");
export const PanelLeft = wrapReicon(Sidebar, "PanelLeft");
export const PanelLeftOpen = wrapReicon(Sidebar, "PanelLeftOpen");
export const PanelTop = wrapReicon(SidebarTop, "PanelTop");
export const PanelTopOpen = wrapReicon(SidebarTop, "PanelTopOpen");
export const PanelsTopLeft = wrapReicon(Layout, "PanelsTopLeft");
export const PauseIcon = wrapReicon(Pause, "Pause");
export { PauseIcon as Pause };
export const Pencil = wrapReicon(Edit, "Pencil");
export const PinIcon = wrapReicon(Pin, "Pin");
export { PinIcon as Pin };
export const PlayIcon = wrapReicon(Play, "Play");
export { PlayIcon as Play };
export const PlusIcon = wrapReicon(Plus, "Plus");
export { PlusIcon as Plus };
export const PuzzleIcon = wrapReicon(Puzzle, "Puzzle");
export { PuzzleIcon as Puzzle };
export const RadioTower = wrapReicon(Wifi, "RadioTower");
export const RefreshCcw = wrapReicon(Refresh, "RefreshCcw");
export const RefreshCw = wrapReicon(Refresh, "RefreshCw");
export const RotateCcw = wrapReicon(RotateLeft, "RotateCcw");
export const RotateCw = wrapReicon(RotateRight, "RotateCw");
export const Save = wrapReicon(Floppy, "Save");
export const ScrollText = wrapReicon(Scroll, "ScrollText");
export const SearchIcon = wrapReicon(Search, "Search");
export { SearchIcon as Search };
export const Settings2Icon = wrapReicon(Settings2, "Settings2");
export { Settings2Icon as Settings2 };
export const Sheet = wrapReicon(Grid, "Sheet");
export const ShieldIcon = wrapReicon(Shield, "Shield");
export { ShieldIcon as Shield };
export const ShieldAlertIcon = wrapReicon(ShieldAlert, "ShieldAlert");
export { ShieldAlertIcon as ShieldAlert };
export const ShieldCheckIcon = wrapReicon(ShieldCheck, "ShieldCheck");
export { ShieldCheckIcon as ShieldCheck };
export const ShieldOff = wrapReicon(ShieldOffGlyph, "ShieldOff");
export const SlidersHorizontal = wrapReicon(SliderHorizontal, "SlidersHorizontal");
export const Smartphone = wrapReicon(Mobile, "Smartphone");
export const SparklesIcon = wrapReicon(Sparkles, "Sparkles");
export { SparklesIcon as Sparkles };
export const SplitSquareHorizontal = wrapReicon(SquareTransferH, "SplitSquareHorizontal");
export const SplitSquareVertical = wrapReicon(SquareTransferV, "SplitSquareVertical");
export const SquareIcon = wrapReicon(SquarePrimitive, "Square");
export { SquareIcon as Square };
export const SquarePen = wrapReicon(Edit, "SquarePen");
export const SquareTerminal = wrapReicon(TerminalSquare, "SquareTerminal");
export const StarIcon = wrapReicon(Star, "Star");
export { StarIcon as Star };
export const StarOffIcon = wrapReicon(StarOff, "StarOff");
export { StarOffIcon as StarOff };
export const StoreIcon = wrapReicon(Store, "Store");
export { StoreIcon as Store };
export const SunIcon = wrapReicon(Sun, "Sun");
export { SunIcon as Sun };
export const TargetIcon = wrapReicon(Target, "Target");
export { TargetIcon as Target };
export const TerminalIcon = wrapReicon(TerminalSquare, "Terminal");
export { TerminalIcon as Terminal };
export const TerminalSquareIcon = wrapReicon(TerminalSquare, "TerminalSquare");
export { TerminalSquareIcon as TerminalSquare };
export const TimerIcon = wrapReicon(Timer, "Timer");
export { TimerIcon as Timer };
export const Trash2 = wrapReicon(Trash, "Trash2");
export const Undo2 = wrapReicon(Undo, "Undo2");
export const Unplug = wrapReicon(Plug, "Unplug");
export const UserRound = wrapReicon(User, "UserRound");
export const Volume2 = wrapReicon(VolumeHigh, "Volume2");
export const VolumeXIcon = wrapReicon(VolumeX, "VolumeX");
export { VolumeXIcon as VolumeX };
export const Webhook = wrapReicon(Share, "Webhook");
export const Workflow = wrapReicon(Hierarchy, "Workflow");
export const XIcon = wrapReicon(X, "X");
export { XIcon as X };
export const XCircleIcon = wrapReicon(XCircle, "XCircle");
export { XCircleIcon as XCircle };
export const ZoomIn = wrapReicon(SearchPlus, "ZoomIn");
export const ZoomOut = wrapReicon(SearchMinus, "ZoomOut");
