export const AGENT_HOST_CAPABILITY_METHODS = [
  "lyraLumen.map",
  "lyraLumen.act",
  "lyraLumen.vact",
  "lyraLumen.reveal",
  "lyraLumen.type",
  "lyraLumen.press",
  "lyraLumen.scroll",
  "lyraLumen.focusScan",
  "lyraLumen.followAudit",
  "lyraLumen.explainTarget",
  "lyraLumen.audit",
  "lyraLumen.elevate",
  "lyraLumen.completeElevation",
  "lyraLumen.resolveControlHandoff",
  "lyraLumen.navigate",
  "lyraLumen.reload",
  "lyraLumen.read",
  "lyraLumen.see",
  "lyraLumen.detectQr",
  "lyraLumen.wait",
  "lyraAx.map",
  "lyraAx.query",
  "lyraAx.act",
  "lyraAx.focus",
  "lyraAx.press",
  "lyraAx.explain",
  "lyraComputer.listApps",
  "lyraComputer.observe",
  "lyraComputer.focus",
  "lyraComputer.map",
  "lyraComputer.find",
  "lyraComputer.act",
  "lyraComputer.diff",
  "lyraComputer.explain",
  "lyraComputer.see",
  "workbench.listTabs",
  "workbench.readTab",
  "workbench.activateTab",
  "workbench.closeTab",
  "workbench.reorderTab",
  "workbench.splitTabs",
  "workbench.detachSplit",
  "workbench.listTerminals",
  "workbench.openTerminal",
  "workbench.focusTerminal",
  "workbench.closeTerminal",
  "workbench.moveTerminal",
  "workbench.readWorkspace",
  "workbench.captureVisualEvidence",
  "workbench.extractTabText",
  "workbench.listFavorites",
  "workbench.removeFavorite",
  "workbench.browser.readSessionSnapshot",
  "workbench.browser.readRenderedSnapshot",
  "workbench.browser.readStorageState",
  "workbench.browser.clearSiteData",
  "terminal.list",
  "terminal.read",
  "terminal.write",
  "software.listCapabilities",
  "software.inspectCapability",
  "software.readState",
  "software.invokeCapability",
  "agent.readHostPersonaContext",
  "agent.readLocalSignals",
  "agent.readPersonaConsent",
  "agent.readSpatiotemporalContext",
  "mcp.oauth.openAuthorizationUrl",
  "sensitiveValues.storeForAgentUse",
  "sensitiveValues.resolveForAgentUse"
] as const;

export type AgentHostCapabilityMethod = (typeof AGENT_HOST_CAPABILITY_METHODS)[number];

const AGENT_HOST_CAPABILITY_METHOD_SET: ReadonlySet<string> = new Set(
  AGENT_HOST_CAPABILITY_METHODS
);

export const isAgentHostCapabilityMethod = (
  method: string
): method is AgentHostCapabilityMethod => AGENT_HOST_CAPABILITY_METHOD_SET.has(method);
