use super::retention::{effective_tool_output_budget, trim_tool_output};
use super::*;

pub(super) fn provider_messages_from_agent_message(
    message: &Value,
    message_index: usize,
    all_messages: &[Value],
    options: &ProviderContextOptions,
    output: &mut ProviderContext,
) -> Vec<Value> {
    let Some(role) = message.get("role").and_then(Value::as_str) else {
        return Vec::new();
    };
    if excludes_provider_context(message) {
        return Vec::new();
    }
    if role == "assistant"
        && let Some(messages) = provider_protocol_v2_messages(message, message_index, options)
    {
        return messages;
    }
    if options.openai_responses_replay
        && role == "assistant"
        && legacy_openai_responses_replay_matches_origin(message, options)
        && let Some(items) = message
            .pointer("/metadata/openaiResponsesReplay")
            .and_then(Value::as_array)
            .filter(|items| !items.is_empty())
    {
        return items
            .iter()
            .cloned()
            .map(|mut item| {
                if let Some(object) = item.as_object_mut() {
                    object.insert(
                        OPENAI_RESPONSES_REPLAY_GROUP_KEY.to_string(),
                        json!(message_index),
                    );
                }
                item
            })
            .collect();
    }
    let text = message
        .get("text")
        .and_then(Value::as_str)
        .unwrap_or_default();

    // Compressed-context-block: role=system message produced by memory_compress.
    // Wrap its JSON payload with a framing prefix so the provider treats it as a
    // summary of prior conversation, not a generic system instruction.
    if role == "system"
        && message.pointer("/metadata/kind").and_then(Value::as_str)
            == Some("compressed-context-block")
    {
        if text.trim().is_empty() {
            return Vec::new();
        }
        return vec![json!({
            "role": "system",
            "content": format!(
                "The following is a compressed context summary of earlier conversation in this session, generated by Lyra. Treat it as authoritative context about prior exchanges; prefer newer messages for current intent.\n\n{text}"
            ),
        })];
    }

    if role == "tool" {
        let (content, evidence_ref) = trim_tool_output(
            text,
            effective_tool_output_budget(options, message.get("id")),
            message.get("id"),
        );
        if let Some(evidence_ref) = evidence_ref {
            output.evidence_refs.push(evidence_ref);
        }
        return if content.trim().is_empty() {
            Vec::new()
        } else {
            vec![json!({
                "role": "tool",
                "tool_call_id": message.get("toolCallId").or_else(|| message.get("tool_call_id")).cloned().unwrap_or_else(|| Value::String("tool-result".to_string())),
                "content": content,
            })]
        };
    }

    // Any assistant message with tool blocks but no providerTranscript is an
    // intermediate tool-call message from a multi-round turn. The complete
    // provider-side view (tool_calls + role:"tool" pairs) is carried by the
    // final assistant message's providerTranscript. Without that transcript,
    // tool blocks can only be emitted as plain text — which strips tool
    // identity and duplicates/confuses the provider. Skip unconditionally.
    // This also covers the interrupted-turn case: if no final message ever
    // received a transcript, the tool calls are incomplete and must not leak
    // as text into the next turn's provider context.
    if role == "assistant"
        && !message_has_provider_transcript(message)
        && message
            .get("blocks")
            .and_then(Value::as_array)
            .is_some_and(|blocks| {
                blocks
                    .iter()
                    .any(|b| b.get("type").and_then(Value::as_str) == Some("tool"))
            })
    {
        return Vec::new();
    }

    let mut transcript = provider_transcript_from_agent_message(message);
    let blocks = message
        .get("blocks")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let content = if blocks.is_empty() {
        text_content_or_none(text)
    } else {
        content_from_blocks(message, &blocks, text, options, output)
    };

    if content.is_some()
        || (role == "user"
            && message
                .pointer("/metadata/providerContext/renderedTail")
                .and_then(Value::as_str)
                .is_some_and(|tail| !tail.trim().is_empty()))
    {
        let content = content.unwrap_or_else(|| Value::String(String::new()));
        let merged = merge_user_content_with_transcript_citations(message, role, content);
        let merged = merge_user_content_with_page_citations(message, role, merged);
        let merged = merge_user_content_with_file_citations(message, role, merged);
        let inline_images = message
            .pointer("/metadata/inlineImages")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();
        let (effective_inline_images, inherited_session_inline_images) =
            effective_inline_images_for_user_turn(
                role,
                &inline_images,
                text,
                all_messages,
                message_index,
            );
        let provider_inline_images = enrich_inline_images_for_provider(&effective_inline_images);
        let merged = merge_user_content_with_inline_images(role, merged, &provider_inline_images);
        let merged = if role == "user" && !provider_inline_images.is_empty() {
            if text_has_inline_image_markers(text) {
                expand_inline_image_markers_in_content(
                    merged,
                    &provider_inline_images,
                    options,
                    output,
                )
            } else if inherited_session_inline_images {
                prepend_inline_images_vision_to_content(
                    merged,
                    &provider_inline_images,
                    options,
                    output,
                )
            } else {
                merged
            }
        } else {
            merged
        };
        let (merged, cache_boundary) =
            merge_user_content_with_provider_context(message, role, merged);
        let mut provider_message = json!({
            "role": role,
            "content": merged,
        });
        if cache_boundary {
            provider_message["lyraCacheBoundary"] = json!("turnTail");
        }
        transcript.push(provider_message);
    }

    transcript
}

fn provider_protocol_v2_messages(
    message: &Value,
    message_index: usize,
    options: &ProviderContextOptions,
) -> Option<Vec<Value>> {
    let protocol = message.pointer("/metadata/providerProtocol")?;
    if protocol.get("version").and_then(Value::as_u64) != Some(2) {
        return None;
    }
    let mut output = Vec::new();
    for prior in protocol
        .get("priorSteps")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter(|step| step.get("version").and_then(Value::as_u64) == Some(2))
    {
        output.extend(provider_protocol_v2_step_messages(
            prior,
            message_index,
            options,
        ));
    }
    output.extend(provider_protocol_v2_step_messages(
        protocol,
        message_index,
        options,
    ));
    Some(output)
}

fn provider_protocol_v2_step_messages(
    protocol: &Value,
    message_index: usize,
    options: &ProviderContextOptions,
) -> Vec<Value> {
    if protocol.get("status").and_then(Value::as_str) != Some("complete") {
        return Vec::new();
    }
    let Some(assistant) = protocol.get("assistant") else {
        return Vec::new();
    };
    let content = assistant
        .get("content")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let tool_calls = assistant
        .get("toolCalls")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut assistant_message = json!({
        "role": "assistant",
        "content": content,
        "tool_calls": tool_calls.iter().filter_map(|call| {
            let id = call.get("id").and_then(Value::as_str)?;
            let name = call.get("name").and_then(Value::as_str)?;
            let arguments = call.get("arguments").cloned().unwrap_or_else(|| json!({}));
            Some(json!({
                "id": id,
                "type": "function",
                "function": {
                    "name": name,
                    "arguments": if let Some(text) = arguments.as_str() {
                        text.to_string()
                    } else {
                        serde_json::to_string(&arguments).unwrap_or_else(|_| "{}".to_string())
                    },
                }
            }))
        }).collect::<Vec<_>>(),
    });
    let tool_results = protocol
        .get("toolResults")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let same_origin = [
        (
            protocol
                .pointer("/origin/providerId")
                .and_then(Value::as_str),
            options.provider_id.as_deref(),
        ),
        (
            protocol.pointer("/origin/routeId").and_then(Value::as_str),
            options.route_id.as_deref(),
        ),
        (
            protocol
                .pointer("/origin/protocolId")
                .and_then(Value::as_str),
            options.protocol_id.as_deref(),
        ),
        (
            protocol.pointer("/origin/model").and_then(Value::as_str),
            options.model.as_deref(),
        ),
    ]
    .into_iter()
    .all(|(stored, active)| stored.is_some() && stored == active);
    let replay_protocol = protocol.pointer("/replay/protocol").and_then(Value::as_str);
    let replay_items = protocol
        .pointer("/replay/items")
        .and_then(Value::as_array)
        .filter(|items| !items.is_empty());
    let auxiliary_before =
        provider_protocol_auxiliary_messages(protocol, "auxiliaryMessagesBeforeAssistant");
    let auxiliary_after =
        provider_protocol_auxiliary_messages(protocol, "auxiliaryMessagesAfterToolResults");

    if same_origin
        && replay_protocol == Some("openai_responses")
        && let Some(items) = replay_items
    {
        let mut output = auxiliary_before;
        output.extend(items.iter().cloned().map(|mut item| {
            if let Some(object) = item.as_object_mut() {
                object.insert(
                    OPENAI_RESPONSES_REPLAY_GROUP_KEY.to_string(),
                    json!(message_index),
                );
            }
            item
        }));
        output.extend(tool_results.iter().filter_map(|result| {
            let call_id = result.get("toolCallId").and_then(Value::as_str)?;
            let mut item = json!({
                "type": "function_call_output",
                "call_id": call_id,
                "output": result.get("content").and_then(Value::as_str).unwrap_or_default(),
            });
            item[OPENAI_RESPONSES_REPLAY_GROUP_KEY] = json!(message_index);
            Some(item)
        }));
        output.extend(auxiliary_after);
        return output;
    }

    if same_origin && let (Some(replay_protocol), Some(items)) = (replay_protocol, replay_items) {
        assistant_message["lyraProviderReplay"] = json!({
            "protocol": replay_protocol,
            "items": items,
        });
        if replay_protocol == "openai_chat_completions"
            && let Some(field) = items
                .first()
                .and_then(|item| item.get("field"))
                .and_then(Value::as_str)
            && matches!(
                field,
                "reasoning" | "reasoning_content" | "reasoning_details"
            )
            && let Some(value) = items.first().and_then(|item| item.get("value"))
        {
            assistant_message[field] = value.clone();
        }
    }

    let mut output = auxiliary_before;
    output.push(assistant_message);
    output.extend(tool_results.iter().filter_map(|result| {
        let call_id = result.get("toolCallId").and_then(Value::as_str)?;
        Some(json!({
            "role": "tool",
            "tool_call_id": call_id,
            "content": result.get("content").and_then(Value::as_str).unwrap_or_default(),
        }))
    }));
    output.extend(auxiliary_after);
    output
}

fn provider_protocol_auxiliary_messages(protocol: &Value, field: &str) -> Vec<Value> {
    protocol
        .get(field)
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(|message| {
            let role = message.get("role").and_then(Value::as_str)?;
            if !matches!(role, "user" | "system" | "developer") {
                return None;
            }
            Some(json!({
                "role": role,
                "content": message.get("content").cloned().unwrap_or(Value::Null),
            }))
        })
        .collect()
}

fn merge_user_content_with_provider_context(
    message: &Value,
    role: &str,
    content: Value,
) -> (Value, bool) {
    if role != "user" {
        return (content, false);
    }
    let Some(rendered_tail) = message
        .pointer("/metadata/providerContext/renderedTail")
        .and_then(Value::as_str)
        .filter(|tail| !tail.trim().is_empty())
    else {
        return (content, false);
    };
    let version = message
        .pointer("/metadata/providerContext/version")
        .and_then(Value::as_u64)
        .unwrap_or(PROVIDER_CONTEXT_METADATA_VERSION);
    let rendered_tail = rendered_tail.trim().replace("</", "&lt;/");
    let block = format!(
        "<lyra-context-update version=\"{version}\" trusted=\"true\">\n{}\n</lyra-context-update>",
        rendered_tail
    );
    let content = match content {
        Value::String(text) if text.trim().is_empty() => Value::String(block),
        Value::String(text) => Value::String(format!("{text}\n\n{block}")),
        Value::Array(mut parts) => {
            parts.push(json!({ "type": "text", "text": block }));
            Value::Array(parts)
        }
        other => other,
    };
    (content, true)
}

fn merge_user_content_with_transcript_citations(
    message: &Value,
    role: &str,
    content: Value,
) -> Value {
    if role != "user" {
        return content;
    }
    let citations = message
        .pointer("/metadata/transcriptCitations")
        .and_then(Value::as_array)
        .filter(|items| !items.is_empty());
    let Some(citations) = citations else {
        return content;
    };
    let cite_blocks = citations
        .iter()
        .filter_map(format_transcript_cite_xml)
        .collect::<Vec<_>>()
        .join("\n");
    if cite_blocks.is_empty() {
        return content;
    }
    let user_text = match &content {
        Value::String(text) => text.clone(),
        Value::Array(parts) => parts
            .iter()
            .filter_map(|part| part.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => String::new(),
    };
    let merged = if user_text.trim().is_empty() {
        format!(
            "The user referenced prior transcript excerpts. Treat every <lyra-transcript-cite> block as a canonical anchor to a message that definitely occurred in this session, even if it is outside the current working context.\n\n{cite_blocks}"
        )
    } else {
        format!(
            "The user referenced prior transcript excerpts. Treat every <lyra-transcript-cite> block as a canonical anchor to a message that definitely occurred in this session, even if it is outside the current working context. When truncated=\"true\", call lyra_session_read_message with messageId (and offsets when present) before relying on the excerpt alone.\n\n{cite_blocks}\n\nUser message:\n{user_text}"
        )
    };
    Value::String(merged)
}

fn merged_content_text(content: &Value) -> String {
    match content {
        Value::String(text) => text.clone(),
        Value::Array(parts) => parts
            .iter()
            .filter_map(|part| part.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => String::new(),
    }
}

fn merge_user_content_with_inline_images(role: &str, content: Value, images: &[Value]) -> Value {
    if role != "user" || images.is_empty() {
        return content;
    }
    let image_blocks = images
        .iter()
        .filter_map(crate::native_backend::inline_images::format_inline_image_xml)
        .collect::<Vec<_>>()
        .join("\n");
    if image_blocks.is_empty() {
        return content;
    }
    let user_text = match &content {
        Value::String(text) => text.clone(),
        Value::Array(parts) => parts
            .iter()
            .filter_map(|part| part.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => String::new(),
    };
    let transcript_marker = "The user referenced prior transcript excerpts.";
    let page_marker = "The user referenced Workbench browser pages.";
    let image_anchor_hint = "Treat every <lyra-image-attach> block as a canonical inline image anchor for the member's inline image attachment. Attachment ids are session-local and are not artifact ids—never pass them to artifact_read. Use the source path on <lyra-image-attach> or image-viewer tools on that file path. Describe image content from vision input; describe transparency/alpha/format from lyra-image-attach traits (hasAlpha, transparentBackground, transparentPixelPercent, colorMode, visionComposited). When visionComposited=true, vision shows a white-backed composite for visibility—the original file at source may still be transparent.";
    let merged = if user_text.trim().is_empty() {
        format!("{image_anchor_hint}\n\n{image_blocks}")
    } else if user_text.contains(transcript_marker) || user_text.contains(page_marker) {
        format!("{user_text}\n\n{image_blocks}")
    } else {
        format!("{image_anchor_hint}\n\n{image_blocks}\n\nUser message:\n{user_text}")
    };
    Value::String(merged)
}

fn merge_user_content_with_page_citations(message: &Value, role: &str, content: Value) -> Value {
    if role != "user" {
        return content;
    }
    let citations = message
        .pointer("/metadata/pageCitations")
        .and_then(Value::as_array)
        .filter(|items| !items.is_empty());
    let Some(citations) = citations else {
        return content;
    };
    let cite_blocks = citations
        .iter()
        .filter_map(crate::native_backend::page_citations::format_page_cite_xml)
        .collect::<Vec<_>>()
        .join("\n");
    if cite_blocks.is_empty() {
        return content;
    }
    let user_text = match &content {
        Value::String(text) => text.clone(),
        Value::Array(parts) => parts
            .iter()
            .filter_map(|part| part.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => String::new(),
    };
    let transcript_marker = "The user referenced prior transcript excerpts.";
    let merged = if user_text.trim().is_empty() {
        format!(
            "The user referenced Workbench browser pages. Treat every <lyra-page-cite> block as a canonical anchor to a tab/page the user was viewing.\n\n{cite_blocks}"
        )
    } else if user_text.contains(transcript_marker) {
        format!("{user_text}\n\n{cite_blocks}")
    } else {
        format!(
            "The user referenced Workbench browser pages. Treat every <lyra-page-cite> block as a canonical anchor to a tab/page the user was viewing.\n\n{cite_blocks}\n\nUser message:\n{user_text}"
        )
    };
    Value::String(merged)
}

fn merge_user_content_with_file_citations(message: &Value, role: &str, content: Value) -> Value {
    if role != "user" {
        return content;
    }
    let citations = message
        .pointer("/metadata/fileAttachments")
        .and_then(Value::as_array)
        .filter(|items| !items.is_empty());
    let Some(citations) = citations else {
        return content;
    };
    let cite_blocks = citations
        .iter()
        .filter_map(crate::native_backend::file_citations::format_file_cite_xml)
        .collect::<Vec<_>>()
        .join("\n");
    if cite_blocks.is_empty() {
        return content;
    }
    let user_text = match &content {
        Value::String(text) => text.clone(),
        Value::Array(parts) => parts
            .iter()
            .filter_map(|part| part.get("text").and_then(Value::as_str))
            .collect::<Vec<_>>()
            .join("\n"),
        _ => String::new(),
    };
    let merged = if user_text.trim().is_empty() {
        format!(
            "The user attached local files from the Lyra file manager. Treat every <lyra-file-cite> block as a canonical anchor to a file path the user referenced.\n\n{cite_blocks}"
        )
    } else {
        format!(
            "The user attached local files from the Lyra file manager. Treat every <lyra-file-cite> block as a canonical anchor to a file path the user referenced.\n\n{cite_blocks}\n\nUser message:\n{user_text}"
        )
    };
    Value::String(merged)
}

fn format_transcript_cite_xml(citation: &Value) -> Option<String> {
    let id = citation.get("id").and_then(Value::as_str)?;
    let message_id = citation.get("messageId").and_then(Value::as_str)?;
    let role = citation
        .get("role")
        .and_then(Value::as_str)
        .unwrap_or("assistant");
    let truncated = citation
        .get("truncated")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let block_id = citation
        .get("blockId")
        .and_then(Value::as_str)
        .map(|value| format!(" blockId=\"{value}\""))
        .unwrap_or_default();
    let start = citation
        .get("startOffset")
        .and_then(Value::as_u64)
        .map(|value| format!(" start=\"{value}\""))
        .unwrap_or_default();
    let end = citation
        .get("endOffset")
        .and_then(Value::as_u64)
        .map(|value| format!(" end=\"{value}\""))
        .unwrap_or_default();
    let quoted = citation
        .get("quotedText")
        .and_then(Value::as_str)
        .unwrap_or_default();
    Some(format!(
        "<lyra-transcript-cite id=\"{id}\" messageId=\"{message_id}\" role=\"{role}\" authentic=\"true\" truncated=\"{truncated}\"{block_id}{start}{end}>\n{quoted}\n</lyra-transcript-cite>"
    ))
}

fn provider_transcript_from_agent_message(message: &Value) -> Vec<Value> {
    message
        .pointer("/metadata/providerTranscript")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(sanitize_provider_transcript_message)
        .collect()
}

fn sanitize_provider_transcript_message(message: &Value) -> Option<Value> {
    let role = message.get("role").and_then(Value::as_str)?;
    match role {
        "assistant" => {
            let mut output = json!({
                "role": "assistant",
                "content": message.get("content").cloned().unwrap_or(Value::String(String::new())),
            });
            if let Some(tool_calls) = message.get("tool_calls").filter(|value| value.is_array()) {
                output["tool_calls"] = tool_calls.clone();
            }
            Some(output)
        }
        "tool" => {
            let tool_call_id = message
                .get("tool_call_id")
                .or_else(|| message.get("toolCallId"))
                .cloned()
                .unwrap_or_else(|| Value::String("tool-result".to_string()));
            Some(json!({
                "role": "tool",
                "tool_call_id": tool_call_id,
                "content": message.get("content").cloned().unwrap_or(Value::String(String::new())),
            }))
        }
        "user" | "system" => message.get("content").map(|content| {
            json!({
                "role": role,
                "content": content,
            })
        }),
        _ => None,
    }
}

fn legacy_openai_responses_replay_matches_origin(
    message: &Value,
    options: &ProviderContextOptions,
) -> bool {
    if options.protocol_id.as_deref() != Some("openai_responses") {
        return false;
    }
    let Some(origin) = message.pointer("/metadata/openaiResponsesState") else {
        return false;
    };
    [
        (
            origin.get("providerId").and_then(Value::as_str),
            options.provider_id.as_deref(),
        ),
        (
            origin.get("routeId").and_then(Value::as_str),
            options.route_id.as_deref(),
        ),
        (
            origin.get("model").and_then(Value::as_str),
            options.model.as_deref(),
        ),
    ]
    .into_iter()
    .all(|(stored, active)| stored.is_some() && stored == active)
}

fn text_content_or_none(text: &str) -> Option<Value> {
    (!text.trim().is_empty()).then(|| Value::String(text.to_string()))
}

fn content_from_blocks(
    message: &Value,
    blocks: &[Value],
    fallback_text: &str,
    options: &ProviderContextOptions,
    output: &mut ProviderContext,
) -> Option<Value> {
    let mut parts = Vec::new();
    for block in blocks {
        match block.get("type").and_then(Value::as_str) {
            Some("text") => {
                if let Some(text) = block.get("text").and_then(Value::as_str)
                    && !text.trim().is_empty()
                {
                    parts.push(json!({ "type": "text", "text": text }));
                }
            }
            Some("image") => {
                if options.supports_image_input {
                    match provider_image_url(block) {
                        Some(url) => {
                            parts.push(json!({
                                "type": "image_url",
                                "image_url": { "url": url },
                            }));
                        }
                        None => {
                            let downgrade =
                                image_downgrade(message, block, "image_data_unavailable");
                            output.input_downgrades.push(downgrade.clone());
                            parts.push(json!({
                                "type": "text",
                                "text": format!(
                                    "[Image omitted: {}]",
                                    downgrade["reason"].as_str().unwrap_or("image unavailable")
                                )
                            }));
                        }
                    }
                } else {
                    let downgrade =
                        image_downgrade(message, block, "model_does_not_support_image_input");
                    output.input_downgrades.push(downgrade.clone());
                    parts.push(json!({
                        "type": "text",
                        "text": format!(
                            "[Image omitted: {}]",
                            downgrade["reason"].as_str().unwrap_or("image input unsupported")
                        )
                    }));
                }
            }
            Some("tool") => {
                if message_has_provider_transcript(message) {
                    continue;
                }
                let tool_id = block
                    .get("toolId")
                    .or_else(|| block.get("tool_id"))
                    .and_then(Value::as_str)
                    .unwrap_or("tool");
                let evidence_ref = json!({
                    "kind": "tool_result_ref",
                    "toolId": tool_id,
                    "messageId": message.get("id").cloned().unwrap_or(Value::Null),
                });
                output.evidence_refs.push(evidence_ref);
                let summary = options
                    .tool_outputs_by_id
                    .get(tool_id)
                    .cloned()
                    .filter(|text| !text.trim().is_empty())
                    .unwrap_or_else(|| TOOL_OUTPUT_OMITTED_SUMMARY.to_string());
                let tool_budget = effective_tool_output_budget(options, message.get("id"));
                let (summary, maybe_ref) = if tool_budget == 0 {
                    (TOOL_OUTPUT_CLEARED_SUMMARY.to_string(), None)
                } else if summary.chars().count() > tool_budget {
                    let trimmed =
                        tool_activity_output_summary(&json!({ "content": summary }), tool_budget);
                    let evidence_ref = json!({
                        "kind": "truncated_tool_output",
                        "toolId": tool_id,
                        "messageId": message.get("id").cloned().unwrap_or(Value::Null),
                        "originalChars": summary.chars().count(),
                        "keptChars": tool_budget,
                    });
                    (trimmed, Some(evidence_ref))
                } else {
                    (summary, None)
                };
                if let Some(evidence_ref) = maybe_ref {
                    output.evidence_refs.push(evidence_ref);
                }
                parts.push(json!({
                    "type": "text",
                    "text": summary,
                }));
            }
            _ => {}
        }
    }

    if parts.is_empty() {
        return text_content_or_none(fallback_text);
    }

    if parts.len() == 1
        && let Some(text) = parts[0].get("text").and_then(Value::as_str)
    {
        return Some(Value::String(text.to_string()));
    }

    Some(Value::Array(parts))
}

fn provider_image_url(block: &Value) -> Option<String> {
    provider_image_url_from_value(block)
}

fn image_downgrade(message: &Value, block: &Value, reason: &str) -> Value {
    json!({
        "kind": "image_input_downgrade",
        "reason": reason,
        "messageId": message.get("id").cloned().unwrap_or(Value::Null),
        "blockId": block.get("id").cloned().unwrap_or(Value::Null),
        "mediaType": block.get("mediaType").or_else(|| block.get("media_type")).cloned().unwrap_or(Value::Null),
        "label": block.get("label").cloned().unwrap_or(Value::Null),
        "source": block.get("source").cloned().unwrap_or(Value::Null),
    })
}
