import type { BrowserSettingsSurfaceProps } from "../settings-surface";

const noop = (): void => undefined;

export const createBrowserSettingsSurfaceProps = (
  overrides: Partial<BrowserSettingsSurfaceProps> = {}
): BrowserSettingsSurfaceProps => ({
  title: "Settings",
  desktopApi: null,
  generalCategoryLabel: "General",
  appearanceCategoryLabel: "Appearance",
  workspaceCategoryLabel: "Workspace",
  aiCategoryLabel: "Lyra Agents",
  modelsCategoryLabel: "Models",
  skillsCategoryLabel: "Skills",
  mcpCategoryLabel: "MCP",
  notificationsCategoryLabel: "Notifications",
  loginManagerCategoryLabel: "Login Manager",
  softwareStoreCategoryLabel: "Lyra Software",
  linuxCategoryLabel: "Linux",
  experimentalCategoryLabel: "Experimental",
  legalCategoryLabel: "Legal",
  docsNavLabel: "Docs",
  languageLabel: "Language",
  languagePickerLabels: {
    searchPlaceholder: "Search languages",
    installing: "Installing",
    removing: "Removing",
    download: "Download",
    remove: "Remove",
    noResults: "No languages found"
  },
  themeLabel: "Theme",
  windowMaterialLabel: "Window material",
  windowMaterialDescription: "Use the system blur and translucent window background.",
  windowMaterialEnabledLabel: "Enabled",
  windowMaterialDisabledLabel: "Disabled",
  uiStyleLabel: "UI style",
  uiStyleExternalReloadRequired: "Reload required",
  uiStyleExternalUntrusted: "Untrusted",
  splitTriggerModeLabel: "Split trigger",
  splitThreePaneLayoutLabel: "Split layout",
  splitOverflowPolicyLabel: "Split overflow",
  aiRichRenderLabel: "Rich rendering",
  aiRichRenderDescription: "Render rich AI content.",
  aiRichRenderEnabledLabel: "Enabled",
  aiRichRenderDisabledLabel: "Disabled",
  aiStopBehaviorLabel: "Stop behavior",
  aiStopBehaviorDescription: "Choose how stop behaves.",
  aiStopBehaviorTurnOnlyLabel: "Turn only",
  aiStopBehaviorTurnOnlyDescription: "Stop the current turn.",
  aiStopBehaviorTurnAndBackgroundLabel: "Turn and background",
  aiStopBehaviorTurnAndBackgroundDescription: "Stop all background work.",
  preventSleepLabel: "Prevent sleep",
  preventSleepDescription: "Keep the machine awake.",
  preventSleepEnabledLabel: "Enabled",
  preventSleepDisabledLabel: "Disabled",
  jsReplLabel: "JS REPL",
  jsReplDescription: "Enable JavaScript REPL.",
  jsReplEnabledLabel: "Enabled",
  jsReplDisabledLabel: "Disabled",
  actCacheLabel: "ActCache Replay",
  actCacheDescription: "Cache successful browser actions.",
  actCacheEnabledLabel: "Enabled",
  actCacheDisabledLabel: "Disabled",
  codeGraphEmbeddingLabel: "CodeGraph Semantic Search",
  codeGraphEmbeddingDescription: "Enable semantic symbol search.",
  codeGraphEmbeddingEnabledLabel: "Enabled",
  codeGraphEmbeddingDisabledLabel: "Disabled",
  leanPromptDeliveryLabel: "Lean prompt delivery",
  leanPromptDeliveryDescription: "Experimental prompt token controls.",
  leanPromptDeliveryEnabledLabel: "Enabled",
  leanPromptDeliveryDisabledLabel: "Disabled",
  statefulPromptContractLabel: "OpenAI Responses stateful prompt contract",
  statefulPromptContractDescription: "Experimental prompt token controls.",
  statefulPromptContractEnabledLabel: "Enabled",
  statefulPromptContractDisabledLabel: "Disabled",
  searchCategoryLabel: "Search",
  searchWebEnginesLabel: "Web engines",
  searchSearxngEndpointLabel: "SearXNG endpoint",
  omniboxNonBrowserSubmitTargetLabel: "Omnibox target",
  systemNotificationModeLabel: "System notifications",
  systemNotificationModeOffLabel: "Off",
  systemNotificationModeBackgroundLabel: "When Lyra is in background",
  systemNotificationModeAllLabel: "Every notification",
  systemNotificationClickBehaviorLabel: "Click behavior",
  systemNotificationClickOpenCenterLabel: "Open notification center",
  systemNotificationClickOpenSourceLabel: "Open source",
  systemNotificationActionsLabel: "System notification buttons",
  systemNotificationActionsDescription: "Show supported OS action buttons.",
  systemNotificationActionsEnabled: "Enabled",
  systemNotificationActionsDisabled: "Disabled",
  linuxCompatProfileLabel: "Linux startup profile",
  linuxCompatProfileDescription: "Controls the next Linux startup.",
  linuxCompatProfileReliableLabel: "Reliable startup",
  linuxCompatProfileReliableDescription: "Prefer the safest launch.",
  linuxCompatProfileNativeLabel: "Native experience",
  linuxCompatProfileNativeDescription: "Prefer the session backend.",
  linuxCompatProfilePerformanceLabel: "Performance",
  linuxCompatProfilePerformanceDescription: "Prefer acceleration.",
  linuxCompatStatusLabel: "Linux compatibility status",
  linuxCompatCurrentStatusLabel: "Current launch",
  linuxCompatSystemLabel: "System",
  linuxCompatDesktopLabel: "Desktop",
  linuxCompatGpuLabel: "GPU",
  linuxCompatSwitchesLabel: "Switches",
  linuxCompatWarningsLabel: "Warnings",
  linuxCompatRestartLabel: "Restart Lyra",
  linuxCompatRestartDescription: "Restart to apply Linux startup changes.",
  linuxCompatRestartNowLabel: "Restart Now",
  linuxCompatRestartDialogTitle: "Restart Lyra?",
  linuxCompatRestartDialogDescription: "Restart to apply Linux startup changes.",
  linuxCompatRestartDialogCancel: "Later",
  linuxCompatRecoveryTitle: "Linux startup recovered",
  linuxCompatRecoveryDescription: "Lyra switched to a safer launch strategy.",
  linuxCompatRequestFailed: "Linux compatibility request failed.",
  legalNoticesLabel: "Open Source Notices",
  legalNoticesIntro: "The following lists open source components.",
  legalLastUpdatedPrefix: "Last updated",
  legalNoticesLoadingLabel: "Loading notices",
  legalNoticesEmptyLabel: "No notices generated",
  legalNoticesErrorLabel: "Open source notices are unavailable.",
  legalGeneratedAtLabel: "Generated",
  legalPackageCountLabel: "Packages",
  legalLicenseLabel: "License",
  legalSourceLabel: "Source",
  legalRepositoryLabel: "Repository",
  legalHomepageLabel: "Homepage",
  legalNoticeTextLabel: "Notice",
  legalLicenseTextLabel: "License text",
  localeValue: "en-US",
  themeValue: "lyra-light",
  windowMaterialValue: true,
  uiStyleValue: "classic",
  splitTriggerModeValue: "ctrl_left_drag",
  splitThreePaneLayoutValue: "adaptive",
  splitOverflowPolicyValue: "block_with_notice",
  aiRichRenderValue: true,
  aiStopBehaviorValue: "turn_only",
  preventSleepValue: true,
  jsReplValue: false,
  actCacheValue: false,
  codeGraphEmbeddingValue: false,
  leanPromptDeliveryValue: false,
  statefulPromptContractValue: false,
  searchWebEngineIds: ["google"],
  searchSearxngEndpointValue: "",
  omniboxNonBrowserSubmitTargetValue: "new_tab",
  systemNotificationModeValue: "background",
  systemNotificationClickBehaviorValue: "open_center",
  systemNotificationActionsValue: true,
  linuxCompatVisible: false,
  linuxCompatStatus: null,
  linuxCompatConfig: null,
  linuxCompatProfileValue: "reliable",
  localeOptions: [
    { value: "en-US", label: "English" },
    { value: "zh-CN", label: "Chinese" }
  ],
  themeOptions: [
    { value: "lyra-light", label: "Light" },
    { value: "lyra-dark", label: "Dark" },
    { value: "lyra-system", label: "System" }
  ],
  uiStyleOptions: [{ value: "classic", label: "Classic" }],
  splitTriggerModeOptions: [
    { value: "ctrl_left_drag", label: "Ctrl left drag" },
    { value: "right_drag", label: "Right drag" }
  ],
  splitThreePaneLayoutOptions: [
    { value: "adaptive", label: "Adaptive" },
    { value: "left_two_right_one", label: "Left split" }
  ],
  splitOverflowPolicyOptions: [
    { value: "block_with_notice", label: "Block" },
    { value: "replace_oldest", label: "Replace oldest" }
  ],
  searchWebEngineOptions: [
    { value: "google", label: "Google" },
    { value: "bing", label: "Bing" }
  ],
  omniboxNonBrowserSubmitTargetOptions: [
    { value: "new_tab", label: "New tab" },
    { value: "replace_active_tab", label: "Replace active tab" }
  ],
  systemNotificationModeOptions: [
    { value: "off", label: "Off" },
    { value: "background", label: "Background" },
    { value: "all", label: "All" }
  ],
  systemNotificationClickBehaviorOptions: [
    { value: "open_center", label: "Open center" },
    { value: "open_source", label: "Open source" }
  ],
  linuxCompatProfileOptions: [
    { value: "reliable", label: "Reliable startup" },
    { value: "native", label: "Native experience" },
    { value: "performance", label: "Performance" }
  ],
  aiLabels: { categoryLabel: "Lyra Agents" } as BrowserSettingsSurfaceProps["aiLabels"],
  aiModel: {} as BrowserSettingsSurfaceProps["aiModel"],
  openDialog: noop,
  loginManager: {
    desktopApi: null,
    labels: {
      title: "Login Manager",
      open: "Open Login Manager",
      tabTitle: "Login Manager",
      searchPlaceholder: "Search logins",
      refresh: "Refresh",
      sessionsTab: "Sessions",
      credentialsTab: "Passwords",
      reviewTab: "Review",
      passwordsUnavailable: "Passwords unavailable",
      emptySessionsTitle: "No sessions",
      emptyCredentialsTitle: "No passwords",
      openSite: "Open site",
      logoutSite: "Log out site",
      deleteCredential: "Delete",
      reveal: "Reveal",
      copy: "Copy",
      copied: "Copied",
      fill: "Fill",
      edit: "Edit",
      save: "Save",
      cancel: "Cancel",
      accountLabel: "Account",
      authMethodLabel: "Login method",
      notesLabel: "Notes",
      statusObserved: "Observed",
      statusPossible: "Possible",
      sourceObserved: "Observed",
      sourceInferred: "Inferred",
      sourceManual: "Manual",
      sourceUnknown: "Unknown",
      methodLabels: {
        site_session: "Site session",
        password: "Password",
        passkey: "Passkey",
        oauth: "OAuth",
        sso: "SSO",
        magic_link: "Magic link",
        unknown: "Unknown"
      }
    },
    onOpenSite: noop,
    embedded: true
  },
  softwareStore: {
    desktopApi: null,
    embedded: true,
    labels: {
      title: "Lyra Software",
      open: "Open Lyra Software",
      tabTitle: "Lyra Software",
      searchPlaceholder: "Search Lyra Software",
      refresh: "Refresh",
      loading: "Loading software...",
      unavailable: "Software registry unavailable.",
      allTab: "All",
      builtinTab: "Lyra Software",
      uiuxTab: "UIUX packs",
      builtinBadge: "Built in",
      uiuxBadge: "UIUX",
      activeBadge: "Active",
      pendingBadge: "Pending",
      trustedBadge: "Trusted",
      untrustedBadge: "Untrusted",
      revokedBadge: "Revoked",
      detailsTitle: "Software details",
      selectItemTitle: "Select software",
      selectItemDescription: "Manage Lyra software and UIUX packs.",
      emptyTitle: "No software",
      typeLabel: "Type",
      categoryLabel: "Category",
      versionLabel: "Version",
      sourceLabel: "Source",
      statusLabel: "Status",
      permissionsLabel: "Permissions",
      actionsLabel: "Actions",
      noActions: "No actions",
      riskLabel: "Risk",
      agentAccessLabel: "Agent access",
      noPermissions: "No permissions",
      builtinType: "Lyra Software",
      uiuxType: "UIUX pack",
      agentAccessNotConnected: "Not connected",
      agentAccessReadOnly: "Read only",
      agentAccessControllable: "Controllable",
      openBuiltin: "Open",
      openUnavailable: "Unavailable",
      chooseLocal: "Choose local package",
      installLocal: "Install local package",
      installGit: "Install from Git",
      installNpm: "Install from NPM",
      gitUrlLabel: "Git URL",
      gitRefLabel: "Ref",
      gitSubdirLabel: "Subdirectory",
      npmPackageLabel: "Package",
      npmVersionLabel: "Version",
      npmSubdirLabel: "Subdirectory",
      trust: "Trust",
      revokeTrust: "Revoke trust",
      activate: "Activate",
      activating: "Working...",
      operationSucceeded: "Operation completed.",
      operationFailed: "Operation failed",
      reloadRequired: "Reload required.",
      installedAtLabel: "Installed",
      updatedAtLabel: "Updated",
      localSource: "Local",
      gitSource: "Git",
      npmSource: "NPM",
      builtinSource: "Built in",
      builtinApps: []
    },
    softwareCapabilities: {
      software: [],
      loading: false,
      error: null,
      refresh: async () => undefined,
      handleBridgeQuery: () => ({ ok: true, value: null }) as never,
      createUiPackCapabilities: () => ({}) as never
    },
    activeUiPackId: "classic",
    onUiPackIdChange: noop,
    onOpenBuiltinApp: noop
  },
  onLocaleChange: noop,
  onThemeChange: noop,
  onWindowMaterialChange: noop,
  onUiStyleChange: noop,
  onSplitTriggerModeChange: noop,
  onSplitThreePaneLayoutChange: noop,
  onSplitOverflowPolicyChange: noop,
  onAiRichRenderChange: noop,
  onAiStopBehaviorChange: noop,
  onPreventSleepChange: noop,
  onJsReplChange: noop,
  onActCacheChange: noop,
  onCodeGraphEmbeddingChange: noop,
  onLeanPromptDeliveryChange: noop,
  onStatefulPromptContractChange: noop,
  onSearchWebEnginesChange: noop,
  onSearchSearxngEndpointChange: noop,
  onOmniboxNonBrowserSubmitTargetChange: noop,
  onSystemNotificationModeChange: noop,
  onSystemNotificationClickBehaviorChange: noop,
  onSystemNotificationActionsChange: noop,
  onLinuxCompatProfileChange: noop,
  onLinuxCompatRestart: noop,
  onOpenDocs: noop,
  ...overrides
});
