export type SettingsDownloadsLabels = {
  readonly title: string;
  readonly unavailable: string;
  readonly defaultDirectory: string;
  readonly defaultDirectorySystem: string;
  readonly chooseDirectory: string;
  readonly proxySection: string;
  readonly proxyMode: string;
  readonly proxyModeSystem: string;
  readonly proxyModeDirect: string;
  readonly proxyModeHttp: string;
  readonly proxyModeSocks5: string;
  readonly proxyUrl: string;
  readonly proxyUrlPlaceholder: string;
  readonly btSection: string;
  readonly btDht: string;
  readonly btPeerExchange: string;
  readonly btLocalPeerDiscovery: string;
  readonly btSeedTime: string;
  readonly btTrackers: string;
  readonly btTrackersPlaceholder: string;
};