import type { WorkbenchTheme } from "../types";
import { createThemeVars } from "./shared";

type EclipseResolvedThemeId = "eclipse-light" | "eclipse-dark";

export const ECLIPSE_RESOLVED_THEMES: Record<EclipseResolvedThemeId, WorkbenchTheme> = {
  "eclipse-light": {
    id: "eclipse-light",
    vars: createThemeVars({
      "--lyra-bg-app": "#e8e8e8",
      "--lyra-bg-surface": "#f4f4f4",
      "--lyra-bg-editor": "#ffffff",
      "--lyra-bg-hover": "#eaeaea",
      "--lyra-line-default": "#e0e0e0",
      "--lyra-line-variant": "#eaeaea",
      "--lyra-line-focused": "#000000",
      "--lyra-text-primary": "#000000",
      "--lyra-text-secondary": "#666666",
      "--lyra-text-muted": "#999999",
      "--lyra-text-accent": "#0070f3",
      "--lyra-browser-tabs-bg": "#f4f4f4",
      "--lyra-browser-tab-bg": "#f4f4f4",
      "--lyra-browser-tab-top-border": "#e0e0e0",
      "--lyra-window-close-hover-bg": "#e00000",
      "--lyra-status-success": "#007a1c",
      "--lyra-status-warning": "#f5a623",
      "--lyra-status-error": "#e00000",
      "--lyra-terminal-bg": "#ffffff",
      "--lyra-terminal-fg": "#000000",
      "--lyra-terminal-black": "#000000",
      "--lyra-terminal-red": "#e00000",
      "--lyra-terminal-green": "#007a1c",
      "--lyra-terminal-yellow": "#f5a623",
      "--lyra-terminal-blue": "#0070f3",
      "--lyra-terminal-magenta": "#7928ca",
      "--lyra-terminal-cyan": "#50e3c2",
      "--lyra-terminal-white": "#ffffff",
      "--lyra-terminal-bright-black": "#666666",
      "--lyra-terminal-bright-red": "#ff0000",
      "--lyra-terminal-bright-green": "#00a026",
      "--lyra-terminal-bright-yellow": "#f8b939",
      "--lyra-terminal-bright-blue": "#3291ff",
      "--lyra-terminal-bright-magenta": "#8a2be2",
      "--lyra-terminal-bright-cyan": "#79ffe1",
      "--lyra-terminal-bright-white": "#ffffff"
    })
  },
  "eclipse-dark": {
    id: "eclipse-dark",
    vars: createThemeVars({
      "--lyra-bg-app": "#000000",
      "--lyra-bg-surface": "#0a0a0a",
      "--lyra-bg-editor": "#111111",
      "--lyra-bg-hover": "#222222",
      "--lyra-line-default": "#333333",
      "--lyra-line-variant": "#222222",
      "--lyra-line-focused": "#ffffff",
      "--lyra-text-primary": "#ffffff",
      "--lyra-text-secondary": "#888888",
      "--lyra-text-muted": "#666666",
      "--lyra-text-accent": "#0070f3",
      "--lyra-browser-tabs-bg": "#0a0a0a",
      "--lyra-browser-tab-bg": "#0a0a0a",
      "--lyra-browser-tab-top-border": "#333333",
      "--lyra-window-close-hover-bg": "#ff0000",
      "--lyra-status-success": "#50e3c2",
      "--lyra-status-warning": "#f5a623",
      "--lyra-status-error": "#ff0000",
      "--lyra-terminal-bg": "#111111",
      "--lyra-terminal-fg": "#ffffff",
      "--lyra-terminal-black": "#000000",
      "--lyra-terminal-red": "#ff0000",
      "--lyra-terminal-green": "#50e3c2",
      "--lyra-terminal-yellow": "#f5a623",
      "--lyra-terminal-blue": "#0070f3",
      "--lyra-terminal-magenta": "#7928ca",
      "--lyra-terminal-cyan": "#8a2be2",
      "--lyra-terminal-white": "#ffffff",
      "--lyra-terminal-bright-black": "#333333",
      "--lyra-terminal-bright-red": "#ff3333",
      "--lyra-terminal-bright-green": "#79ffe1",
      "--lyra-terminal-bright-yellow": "#f8b939",
      "--lyra-terminal-bright-blue": "#3291ff",
      "--lyra-terminal-bright-magenta": "#8a2be2",
      "--lyra-terminal-bright-cyan": "#79ffe1",
      "--lyra-terminal-bright-white": "#ffffff"
    })
  }
};
