import type { WorkbenchTheme } from "../types";
import { createThemeVars } from "./shared";

type LyraResolvedThemeId = "lyra-light" | "lyra-dark";

export const LYRA_RESOLVED_THEMES: Record<LyraResolvedThemeId, WorkbenchTheme> = {
  "lyra-light": {
    id: "lyra-light",
    vars: createThemeVars({
      "--lyra-bg-app": "#dcdcdd",
      "--lyra-bg-surface": "#ebebec",
      "--lyra-bg-editor": "#fafafa",
      "--lyra-bg-hover": "#dfdfe0",
      "--lyra-line-default": "#d8d8da",
      "--lyra-line-variant": "#e6e6e8",
      "--lyra-line-focused": "#7d82e8",
      "--lyra-text-primary": "#242529",
      "--lyra-text-secondary": "#58585a",
      "--lyra-text-muted": "#7e8086",
      "--lyra-text-accent": "#5c78e2",
      "--lyra-browser-tabs-bg": "#ebebec",
      "--lyra-browser-tab-bg": "#ebebec",
      "--lyra-browser-tab-top-border": "#d8d8da",
      "--lyra-window-close-hover-bg": "#d36151",
      "--lyra-status-success": "#669f59",
      "--lyra-status-warning": "#a48819",
      "--lyra-status-error": "#d36151",
      "--lyra-terminal-bg": "#fafafa",
      "--lyra-terminal-fg": "#2a2c33",
      "--lyra-terminal-black": "#000000",
      "--lyra-terminal-red": "#de3e35",
      "--lyra-terminal-green": "#3f953a",
      "--lyra-terminal-yellow": "#d2b67c",
      "--lyra-terminal-blue": "#2f5af3",
      "--lyra-terminal-magenta": "#950095",
      "--lyra-terminal-cyan": "#0997b3",
      "--lyra-terminal-white": "#bbbbbb",
      "--lyra-terminal-bright-black": "#000000",
      "--lyra-terminal-bright-red": "#de3e35",
      "--lyra-terminal-bright-green": "#3f953a",
      "--lyra-terminal-bright-yellow": "#d2b67c",
      "--lyra-terminal-bright-blue": "#2f5af3",
      "--lyra-terminal-bright-magenta": "#a00095",
      "--lyra-terminal-bright-cyan": "#0bbcd6",
      "--lyra-terminal-bright-white": "#ffffff"
    })
  },
  "lyra-dark": {
    id: "lyra-dark",
    vars: createThemeVars({
      "--lyra-bg-app": "#3b414d",
      "--lyra-bg-surface": "#2f343e",
      "--lyra-bg-editor": "#282c33",
      "--lyra-bg-hover": "#363c46",
      "--lyra-line-default": "#3c414c",
      "--lyra-line-variant": "#363c46",
      "--lyra-line-focused": "#47679e",
      "--lyra-text-primary": "#dce0e5",
      "--lyra-text-secondary": "#a9afbc",
      "--lyra-text-muted": "#878a98",
      "--lyra-text-accent": "#74ade8",
      "--lyra-browser-tabs-bg": "#2f343e",
      "--lyra-browser-tab-bg": "#2f343e",
      "--lyra-browser-tab-top-border": "#3c414c",
      "--lyra-window-close-hover-bg": "#d07277",
      "--lyra-status-success": "#a1c181",
      "--lyra-status-warning": "#dec184",
      "--lyra-status-error": "#d07277",
      "--lyra-terminal-bg": "#282c34",
      "--lyra-terminal-fg": "#abb2bf",
      "--lyra-terminal-black": "#282c34",
      "--lyra-terminal-red": "#e06c75",
      "--lyra-terminal-green": "#98c379",
      "--lyra-terminal-yellow": "#e5c07b",
      "--lyra-terminal-blue": "#61afef",
      "--lyra-terminal-magenta": "#c678dd",
      "--lyra-terminal-cyan": "#56b6c2",
      "--lyra-terminal-white": "#abb2bf",
      "--lyra-terminal-bright-black": "#636d83",
      "--lyra-terminal-bright-red": "#ea858b",
      "--lyra-terminal-bright-green": "#aad581",
      "--lyra-terminal-bright-yellow": "#ffd885",
      "--lyra-terminal-bright-blue": "#85c1ff",
      "--lyra-terminal-bright-magenta": "#d398eb",
      "--lyra-terminal-bright-cyan": "#6ed5de",
      "--lyra-terminal-bright-white": "#fafafa"
    })
  }
};
