import type { WorkbenchTheme } from "../types";
import { createThemeVars } from "./shared";

type NovaResolvedThemeId = "nova-light" | "nova-dark";

export const NOVA_RESOLVED_THEMES: Record<NovaResolvedThemeId, WorkbenchTheme> = {
  "nova-light": {
    id: "nova-light",
    vars: createThemeVars({
      "--lyra-bg-app": "#dcddde",
      "--lyra-bg-surface": "#ececed",
      "--lyra-bg-editor": "#fcfcfc",
      "--lyra-bg-hover": "#dfe0e1",
      "--lyra-line-default": "#cfd1d2",
      "--lyra-line-variant": "#dfe0e1",
      "--lyra-line-focused": "#c4daf6",
      "--lyra-text-primary": "#5c6166",
      "--lyra-text-secondary": "#8b8e92",
      "--lyra-text-muted": "#a9acae",
      "--lyra-text-accent": "#3b9ee5",
      "--lyra-browser-tabs-bg": "#ececed",
      "--lyra-browser-tab-bg": "#ececed",
      "--lyra-browser-tab-top-border": "#cfd1d2",
      "--lyra-window-close-hover-bg": "#ef7271",
      "--lyra-status-success": "#85b304",
      "--lyra-status-warning": "#f1ad49",
      "--lyra-status-error": "#ef7271",
      "--lyra-terminal-bg": "#fcfcfc",
      "--lyra-terminal-fg": "#5c6166",
      "--lyra-terminal-black": "#5c6166",
      "--lyra-terminal-red": "#ef7271",
      "--lyra-terminal-green": "#85b304",
      "--lyra-terminal-yellow": "#f1ad49",
      "--lyra-terminal-blue": "#3b9ee5",
      "--lyra-terminal-magenta": "#55b4d3",
      "--lyra-terminal-cyan": "#4dbf99",
      "--lyra-terminal-white": "#fcfcfc",
      "--lyra-terminal-bright-black": "#3b9ee5",
      "--lyra-terminal-bright-red": "#febab6",
      "--lyra-terminal-bright-green": "#c7d98f",
      "--lyra-terminal-bright-yellow": "#fed5a3",
      "--lyra-terminal-bright-blue": "#abcdf2",
      "--lyra-terminal-bright-magenta": "#b1d8e8",
      "--lyra-terminal-bright-cyan": "#ace0cb",
      "--lyra-terminal-bright-white": "#ffffff"
    })
  },
  "nova-dark": {
    id: "nova-dark",
    vars: createThemeVars({
      "--lyra-bg-app": "#313337",
      "--lyra-bg-surface": "#1f2127",
      "--lyra-bg-editor": "#0d1016",
      "--lyra-bg-hover": "#2d2f34",
      "--lyra-line-default": "#3f4043",
      "--lyra-line-variant": "#2d2f34",
      "--lyra-line-focused": "#1b4a6e",
      "--lyra-text-primary": "#bfbdb6",
      "--lyra-text-secondary": "#8a8986",
      "--lyra-text-muted": "#696a6a",
      "--lyra-text-accent": "#5ac1fe",
      "--lyra-browser-tabs-bg": "#1f2127",
      "--lyra-browser-tab-bg": "#1f2127",
      "--lyra-browser-tab-top-border": "#3f4043",
      "--lyra-window-close-hover-bg": "#ef7177",
      "--lyra-status-success": "#aad84c",
      "--lyra-status-warning": "#feb454",
      "--lyra-status-error": "#ef7177",
      "--lyra-terminal-bg": "#0d1016",
      "--lyra-terminal-fg": "#bfbdb6",
      "--lyra-terminal-black": "#0d1016",
      "--lyra-terminal-red": "#ef7177",
      "--lyra-terminal-green": "#aad84c",
      "--lyra-terminal-yellow": "#feb454",
      "--lyra-terminal-blue": "#5ac1fe",
      "--lyra-terminal-magenta": "#39bae5",
      "--lyra-terminal-cyan": "#95e5cb",
      "--lyra-terminal-white": "#bfbdb6",
      "--lyra-terminal-bright-black": "#545557",
      "--lyra-terminal-bright-red": "#83353b",
      "--lyra-terminal-bright-green": "#567627",
      "--lyra-terminal-bright-yellow": "#92582b",
      "--lyra-terminal-bright-blue": "#27618c",
      "--lyra-terminal-bright-magenta": "#205a78",
      "--lyra-terminal-bright-cyan": "#4c806f",
      "--lyra-terminal-bright-white": "#fafafa"
    })
  }
};
