import type { WorkbenchTheme } from "../types";
import { createThemeVars } from "./shared";

type OceanResolvedThemeId = "ocean-light" | "ocean-dark";

export const OCEAN_RESOLVED_THEMES: Record<OceanResolvedThemeId, WorkbenchTheme> = {
  "ocean-light": {
    id: "ocean-light",
    vars: createThemeVars({
      "--lyra-bg-app": "#d8dee9",
      "--lyra-bg-surface": "#e5e9f0",
      "--lyra-bg-editor": "#eceff4",
      "--lyra-bg-hover": "#e0e5ed",
      "--lyra-line-default": "#c6cad3",
      "--lyra-line-variant": "#d2d6df",
      "--lyra-line-focused": "#88c0d0",
      "--lyra-text-primary": "#2e3440",
      "--lyra-text-secondary": "#4c566a",
      "--lyra-text-muted": "#8fbcbb",
      "--lyra-text-accent": "#5e81ac",
      "--lyra-browser-tabs-bg": "#e5e9f0",
      "--lyra-browser-tab-bg": "#e5e9f0",
      "--lyra-browser-tab-top-border": "#c6cad3",
      "--lyra-window-close-hover-bg": "#bf616a",
      "--lyra-status-success": "#a3be8c",
      "--lyra-status-warning": "#ebcb8b",
      "--lyra-status-error": "#bf616a",
      "--lyra-terminal-bg": "#eceff4",
      "--lyra-terminal-fg": "#2e3440",
      "--lyra-terminal-black": "#3b4252",
      "--lyra-terminal-red": "#bf616a",
      "--lyra-terminal-green": "#a3be8c",
      "--lyra-terminal-yellow": "#ebcb8b",
      "--lyra-terminal-blue": "#81a1c1",
      "--lyra-terminal-magenta": "#b48ead",
      "--lyra-terminal-cyan": "#88c0d0",
      "--lyra-terminal-white": "#e5e9f0",
      "--lyra-terminal-bright-black": "#4c566a",
      "--lyra-terminal-bright-red": "#bf616a",
      "--lyra-terminal-bright-green": "#a3be8c",
      "--lyra-terminal-bright-yellow": "#ebcb8b",
      "--lyra-terminal-bright-blue": "#81a1c1",
      "--lyra-terminal-bright-magenta": "#b48ead",
      "--lyra-terminal-bright-cyan": "#8fbcbb",
      "--lyra-terminal-bright-white": "#eceff4"
    })
  },
  "ocean-dark": {
    id: "ocean-dark",
    vars: createThemeVars({
      "--lyra-bg-app": "#2e3440",
      "--lyra-bg-surface": "#3b4252",
      "--lyra-bg-editor": "#434c5e",
      "--lyra-bg-hover": "#4c566a",
      "--lyra-line-default": "#505b70",
      "--lyra-line-variant": "#4c566a",
      "--lyra-line-focused": "#81a1c1",
      "--lyra-text-primary": "#eceff4",
      "--lyra-text-secondary": "#e5e9f0",
      "--lyra-text-muted": "#d8dee9",
      "--lyra-text-accent": "#88c0d0",
      "--lyra-browser-tabs-bg": "#3b4252",
      "--lyra-browser-tab-bg": "#3b4252",
      "--lyra-browser-tab-top-border": "#505b70",
      "--lyra-window-close-hover-bg": "#bf616a",
      "--lyra-status-success": "#a3be8c",
      "--lyra-status-warning": "#ebcb8b",
      "--lyra-status-error": "#bf616a",
      "--lyra-terminal-bg": "#434c5e",
      "--lyra-terminal-fg": "#eceff4",
      "--lyra-terminal-black": "#3b4252",
      "--lyra-terminal-red": "#bf616a",
      "--lyra-terminal-green": "#a3be8c",
      "--lyra-terminal-yellow": "#ebcb8b",
      "--lyra-terminal-blue": "#81a1c1",
      "--lyra-terminal-magenta": "#b48ead",
      "--lyra-terminal-cyan": "#88c0d0",
      "--lyra-terminal-white": "#e5e9f0",
      "--lyra-terminal-bright-black": "#4c566a",
      "--lyra-terminal-bright-red": "#bf616a",
      "--lyra-terminal-bright-green": "#a3be8c",
      "--lyra-terminal-bright-yellow": "#ebcb8b",
      "--lyra-terminal-bright-blue": "#81a1c1",
      "--lyra-terminal-bright-magenta": "#b48ead",
      "--lyra-terminal-bright-cyan": "#8fbcbb",
      "--lyra-terminal-bright-white": "#eceff4"
    })
  }
};
