import type { WorkbenchTheme } from "../types";
import { createThemeVars } from "./shared";

type TerraResolvedThemeId = "terra-light" | "terra-dark";

export const TERRA_RESOLVED_THEMES: Record<TerraResolvedThemeId, WorkbenchTheme> = {
  "terra-light": {
    id: "terra-light",
    vars: createThemeVars({
      "--lyra-bg-app": "#d9c8a4",
      "--lyra-bg-surface": "#ecddb4",
      "--lyra-bg-editor": "#fbf1c7",
      "--lyra-bg-hover": "#ddcca7",
      "--lyra-line-default": "#c8b899",
      "--lyra-line-variant": "#ddcca7",
      "--lyra-line-focused": "#adc5cc",
      "--lyra-text-primary": "#282828",
      "--lyra-text-secondary": "#5f5650",
      "--lyra-text-muted": "#897b6e",
      "--lyra-text-accent": "#0b6678",
      "--lyra-browser-tabs-bg": "#ecddb4",
      "--lyra-browser-tab-bg": "#ecddb4",
      "--lyra-browser-tab-top-border": "#c8b899",
      "--lyra-window-close-hover-bg": "#9d0308",
      "--lyra-status-success": "#797410",
      "--lyra-status-warning": "#b57615",
      "--lyra-status-error": "#9d0308",
      "--lyra-terminal-bg": "#fbf1c7",
      "--lyra-terminal-fg": "#282828",
      "--lyra-terminal-black": "#fbf1c7",
      "--lyra-terminal-red": "#cc241d",
      "--lyra-terminal-green": "#98971a",
      "--lyra-terminal-yellow": "#d79921",
      "--lyra-terminal-blue": "#458588",
      "--lyra-terminal-magenta": "#b16286",
      "--lyra-terminal-cyan": "#689d6a",
      "--lyra-terminal-white": "#7c6f64",
      "--lyra-terminal-bright-black": "#928374",
      "--lyra-terminal-bright-red": "#9d0006",
      "--lyra-terminal-bright-green": "#79740e",
      "--lyra-terminal-bright-yellow": "#b57614",
      "--lyra-terminal-bright-blue": "#076678",
      "--lyra-terminal-bright-magenta": "#8f3f71",
      "--lyra-terminal-bright-cyan": "#427b58",
      "--lyra-terminal-bright-white": "#282828"
    })
  },
  "terra-dark": {
    id: "terra-dark",
    vars: createThemeVars({
      "--lyra-bg-app": "#4c4642",
      "--lyra-bg-surface": "#3a3735",
      "--lyra-bg-editor": "#282828",
      "--lyra-bg-hover": "#494340",
      "--lyra-line-default": "#5b534d",
      "--lyra-line-variant": "#494340",
      "--lyra-line-focused": "#303a36",
      "--lyra-text-primary": "#fbf1c7",
      "--lyra-text-secondary": "#c5b597",
      "--lyra-text-muted": "#998b78",
      "--lyra-text-accent": "#83a598",
      "--lyra-browser-tabs-bg": "#3a3735",
      "--lyra-browser-tab-bg": "#3a3735",
      "--lyra-browser-tab-top-border": "#5b534d",
      "--lyra-window-close-hover-bg": "#fb4a35",
      "--lyra-status-success": "#b7bb26",
      "--lyra-status-warning": "#f9bd2f",
      "--lyra-status-error": "#fb4a35",
      "--lyra-terminal-bg": "#282828",
      "--lyra-terminal-fg": "#ebdbb2",
      "--lyra-terminal-black": "#282828",
      "--lyra-terminal-red": "#cc241d",
      "--lyra-terminal-green": "#98971a",
      "--lyra-terminal-yellow": "#d79921",
      "--lyra-terminal-blue": "#458588",
      "--lyra-terminal-magenta": "#b16286",
      "--lyra-terminal-cyan": "#689d6a",
      "--lyra-terminal-white": "#a89984",
      "--lyra-terminal-bright-black": "#928374",
      "--lyra-terminal-bright-red": "#fb4934",
      "--lyra-terminal-bright-green": "#b8bb26",
      "--lyra-terminal-bright-yellow": "#fabd2f",
      "--lyra-terminal-bright-blue": "#83a598",
      "--lyra-terminal-bright-magenta": "#d3869b",
      "--lyra-terminal-bright-cyan": "#8ec07c",
      "--lyra-terminal-bright-white": "#fbf1c7"
    })
  }
};
