// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSearchContentMode } from "./LocalSearchContentMode";

export type LocalSearchIndexRootParams = { root: string, includeHidden?: boolean, includeVendor?: boolean, respectGitignore?: boolean, contentMode?: LocalSearchContentMode, maxFileSizeBytes?: bigint, };
