// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSearchIndexState } from "./LocalSearchIndexState";
import type { LocalSearchKind } from "./LocalSearchKind";
import type { LocalSearchMatchKind } from "./LocalSearchMatchKind";
import type { LocalSearchMetadata } from "./LocalSearchMetadata";
import type { LocalSearchSource } from "./LocalSearchSource";

export type LocalSearchResult = { path: string, displayPath: string, root: string, kind: LocalSearchKind, score: number, source: LocalSearchSource, matchKind: LocalSearchMatchKind, snippet?: string, metadata?: LocalSearchMetadata, indexState: LocalSearchIndexState, };
