// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSearchIndexState } from "./LocalSearchIndexState";

export type LocalSearchRootStatus = { root: string, state: LocalSearchIndexState, indexedFileCount: bigint, indexedDirCount: bigint, indexedContentFileCount: bigint, lastIndexedAt?: bigint, error?: string, };
