// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalSearchReadResultResponse = { path: string, offset: bigint, bytesRead: number, contents: string, truncated: boolean, };
