// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSearchIndexState } from "./LocalSearchIndexState";
import type { LocalSearchRootStatus } from "./LocalSearchRootStatus";

export type LocalSearchStatus = { state: LocalSearchIndexState, roots: Array<LocalSearchRootStatus>, indexedFileCount: bigint, indexedDirCount: bigint, indexedContentFileCount: bigint, sqliteFtsAvailable: boolean, };
