// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSearchContentMode } from "./LocalSearchContentMode";
import type { LocalSearchKind } from "./LocalSearchKind";

export type LocalSearchSearchParams = { query: string, roots: Array<string>, kinds: Array<LocalSearchKind>, extensions: Array<string>, limit?: number, includeHidden?: boolean, includeVendor?: boolean, respectGitignore?: boolean, contentMode?: LocalSearchContentMode, maxFileSizeBytes?: bigint, cancellationToken?: string, };
