// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalSearchIndexState } from "./LocalSearchIndexState";
import type { LocalSearchResult } from "./LocalSearchResult";

export type LocalSearchSearchResponse = { query: string, roots: Array<string>, results: Array<LocalSearchResult>, totalMatchCount: number, truncated: boolean, indexState: LocalSearchIndexState, };
