// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanArtifactBlock } from "./PlanArtifactBlock";
import type { PlanArtifactStatus } from "./PlanArtifactStatus";

export type PlanArtifact = { planId: string, status: PlanArtifactStatus, title: string, summary: string, objective: string, assumptions: Array<PlanArtifactBlock>, steps: Array<PlanArtifactBlock>, interfaces: Array<PlanArtifactBlock>, risks: Array<PlanArtifactBlock>, tests: Array<PlanArtifactBlock>, acceptanceCriteria: Array<PlanArtifactBlock>, };
