[package]
edition.workspace = true
license.workspace = true
name = "lyra-model-provider-info"
version.workspace = true

[lib]
doctest = false
name = "lyra_model_provider_info"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
lyra-api = { workspace = true }
lyra-app-server-protocol = { workspace = true }
lyra-protocol = { workspace = true }
http = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }

[dev-dependencies]
lyra-utils-absolute-path = { workspace = true }
maplit = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
