[package]
name = "lyra-download-napi"
version = "0.1.0"
edition = "2021"
license-file.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
lyra-download-core = { path = "../lyra-download-core" }
napi = { version = "2.16.13", default-features = false, features = ["napi8"] }
napi-derive = "2.16.13"

[build-dependencies]
napi-build = "2.1.4"
