use crate::model::ToolManifest;

pub(super) fn manifests() -> Vec<ToolManifest> {
    vec![
        super::s(
            "/tools/browser/interact",
            "browser",
            "interact",
            "Browser interact",
            "Run a short declarative action sequence (navigate, wait, click, scroll, type) then extract read/map in one call.",
            Some("browser_interact"),
        ),
        super::s(
            "/tools/browser/map",
            "browser",
            "map",
            "Map browser page",
            "Map actionable browser elements.",
            Some("browser_map"),
        ),
        super::s(
            "/tools/browser/plan",
            "browser",
            "plan",
            "Plan browser actions",
            "Map once and return deterministic targetRef action candidates for batch act/type.",
            Some("browser_plan"),
        ),
        super::s(
            "/tools/browser/read",
            "browser",
            "read",
            "Read browser page",
            "Read text from a browser page.",
            Some("browser_read"),
        ),
        super::s(
            "/tools/browser/find",
            "browser",
            "find",
            "Find in browser page",
            "Search text within a browser page and optionally reveal the selected match.",
            Some("browser_find"),
        ),
        super::s(
            "/tools/browser/locate",
            "browser",
            "locate",
            "Locate browser page section",
            "Find or semantically locate text on a browser page, reveal it, and map nearby controls.",
            Some("browser_locate"),
        ),
        super::s(
            "/tools/browser/see",
            "browser",
            "see",
            "See browser page",
            "Capture a visual browser snapshot.",
            None,
        ),
        super::s(
            "/tools/browser/act",
            "browser",
            "act",
            "Act in browser",
            "Click or hover a browser target.",
            None,
        ),
        super::s(
            "/tools/browser/vact",
            "browser",
            "vact",
            "Visually act in browser",
            "Click, drag, or scroll a browser page using device-pixel coordinates read from the latest see screenshot.",
            None,
        ),
        super::s(
            "/tools/browser/type",
            "browser",
            "type",
            "Type in browser",
            "Type text into a browser target.",
            None,
        ),
        super::s(
            "/tools/browser/press",
            "browser",
            "press",
            "Press browser key",
            "Press a browser keyboard key.",
            None,
        ),
        super::s(
            "/tools/browser/submit",
            "browser",
            "submit",
            "Submit browser control",
            "Submit focused browser control.",
            None,
        ),
        super::s(
            "/tools/browser/scroll",
            "browser",
            "scroll",
            "Scroll browser page",
            "Scroll the browser viewport or a target area before mapping or interacting.",
            Some("browser_scroll"),
        ),
        super::s(
            "/tools/browser/scroll_to_target",
            "browser",
            "scroll_to_target",
            "Scroll to browser target",
            "Bring a mapped browser target near the visible viewport center.",
            Some("browser_scroll_to_target"),
        ),
        super::s(
            "/tools/browser/ensure_visible",
            "browser",
            "ensure_visible",
            "Ensure browser target visible",
            "Auto-scroll a browser target or point into the visible viewport before acting.",
            Some("browser_ensure_visible"),
        ),
        super::s(
            "/tools/browser/wait",
            "browser",
            "wait",
            "Wait browser",
            "Wait for browser page state.",
            None,
        ),
        super::s(
            "/tools/browser/read_until",
            "browser",
            "read_until",
            "Read browser until",
            "Wait and read browser text.",
            None,
        ),
        super::s(
            "/tools/browser/navigate",
            "browser",
            "navigate",
            "Navigate browser",
            "Navigate a browser page.",
            None,
        ),
        super::s(
            "/tools/browser/reveal",
            "browser",
            "reveal",
            "Reveal browser target",
            "Reveal a browser target.",
            None,
        ),
        super::s(
            "/tools/browser/focus_scan",
            "browser",
            "focus_scan",
            "Focus scan browser",
            "Scan focusable browser targets.",
            None,
        ),
        super::s(
            "/tools/browser/follow_audit",
            "browser",
            "follow_audit",
            "Audit browser Follow",
            "Audit browser follow state.",
            None,
        ),
        super::s(
            "/tools/browser/explain_target",
            "browser",
            "explain_target",
            "Explain browser target",
            "Explain a browser target reference.",
            None,
        ),
        super::s(
            "/tools/browser/audit",
            "browser",
            "audit",
            "Audit browser",
            "Audit browser state.",
            None,
        ),
        super::s(
            "/tools/browser/elevate",
            "browser",
            "elevate",
            "Elevate browser task",
            "Elevate an isolated browser task.",
            None,
        ),
        super::s(
            "/tools/browser/judge_task",
            "browser",
            "judge_task",
            "Judge browser task",
            "Verify browser task completion from trajectory and final observation.",
            Some("browser_judge_task"),
        ),
    ]
}
