use crate::model::ToolManifest;

pub(super) fn manifests() -> Vec<ToolManifest> {
    vec![
        super::s(
            "/tools/browser/map",
            "browser",
            "map",
            "Map browser page",
            "Map actionable elements the user can operate — current window first, then controls that need a scroll. Nested chrome is collapsed to the button itself.",
            Some("browser_map"),
        ),
        super::s(
            "/tools/browser/read",
            "browser",
            "read",
            "Read browser page",
            "Read page text, search in-page text, or return a JSON schema hint for structured extraction.",
            Some("browser_read"),
        ),
        super::s(
            "/tools/browser/see",
            "browser",
            "see",
            "See browser page",
            "Capture a visual snapshot of any web page — inspect real product UIs, design references, live demos.",
            None,
        ),
        super::s(
            "/tools/browser/detect_qr",
            "browser",
            "detect_qr",
            "Detect browser QR codes",
            "Capture the current browser viewport and detect QR codes with device-pixel bounds, optional QR-only crops, and vact-compatible captureId.",
            None,
        ),
        super::s(
            "/tools/browser/act",
            "browser",
            "act",
            "Act in browser",
            "Click or hover a browser target. Off-screen targetRefs are scrolled into view first.",
            None,
        ),
        super::s(
            "/tools/browser/vact",
            "browser",
            "vact",
            "Visually act in browser",
            "Click, drag, or scroll a browser page using device-pixel coordinates read from the latest see screenshot.",
            None,
        ),
        super::s(
            "/tools/browser/type",
            "browser",
            "type",
            "Type in browser",
            "Type text into a browser target.",
            None,
        ),
        super::s(
            "/tools/browser/press",
            "browser",
            "press",
            "Press browser key",
            "Press a browser keyboard key (Enter, Escape, shortcuts).",
            None,
        ),
        super::s(
            "/tools/browser/scroll",
            "browser",
            "scroll",
            "Scroll browser page",
            "Scroll the viewport when there is no targetRef — infinite feeds, load-more. Do not use this to discover controls; map already lists Needs scroll.",
            Some("browser_scroll"),
        ),
        super::s(
            "/tools/browser/wait",
            "browser",
            "wait",
            "Wait browser",
            "Wait for browser page state (idle, text, URL).",
            None,
        ),
        super::s(
            "/tools/browser/navigate",
            "browser",
            "navigate",
            "Navigate browser",
            "Open any URL — GitHub repos, documentation sites, real products, online AI services, free online tools, design galleries. Entire internet accessible.",
            None,
        ),
        super::s(
            "/tools/browser/elevate",
            "browser",
            "elevate",
            "Elevate browser task",
            "Elevate an isolated browser task.",
            None,
        ),
    ]
}
