use crate::model::ToolManifest;

pub(super) fn manifests() -> Vec<ToolManifest> {
    vec![
        super::s(
            "/tools/workbench/list_tabs",
            "workbench",
            "list_tabs",
            "List workbench tabs",
            "List Lyra workbench tabs.",
            Some("workbench_list_tabs"),
        ),
        super::s(
            "/tools/workbench/read_workspace",
            "workbench",
            "read_workspace",
            "Read workspace",
            "Read visible workspace state.",
            Some("workbench_read_workspace"),
        ),
        super::s(
            "/tools/workbench/read_tab",
            "workbench",
            "read_tab",
            "Read workbench tab",
            "Read one Lyra workbench tab.",
            Some("workbench_read_tab"),
        ),
        super::s(
            "/tools/workbench/capture_visual_evidence",
            "workbench",
            "capture_visual_evidence",
            "Capture workspace visual evidence",
            "Capture visible Lyra workspace visual evidence for model vision, including the workspace window, Image Viewer, file previews, terminal surfaces, and browser tab screenshots.",
            Some("workbench_capture_visual_evidence"),
        ),
        super::s(
            "/tools/workbench/activate_tab",
            "workbench",
            "activate_tab",
            "Activate workbench tab",
            "Activate one Lyra workbench tab.",
            None,
        ),
        super::s(
            "/tools/workbench/close_tab",
            "workbench",
            "close_tab",
            "Close workbench tab",
            "Close one Lyra workbench tab.",
            None,
        ),
        super::s(
            "/tools/workbench/reorder_tab",
            "workbench",
            "reorder_tab",
            "Reorder workbench tab",
            "Move a workbench tab to a new index in the tab strip.",
            None,
        ),
        super::s(
            "/tools/workbench/split_tabs",
            "workbench",
            "split_tabs",
            "Split workbench tabs",
            "Split two workbench tabs into a visible split layout (up to four panes).",
            None,
        ),
        super::s(
            "/tools/workbench/detach_split",
            "workbench",
            "detach_split",
            "Detach split pane",
            "Detach one tab from the current split layout.",
            None,
        ),
        super::s(
            "/tools/workbench/list_terminals",
            "workbench",
            "list_terminals",
            "List terminal panes",
            "List visible terminal panes in the dock and workspace.",
            Some("workbench_list_terminals"),
        ),
        super::s(
            "/tools/workbench/open_terminal",
            "workbench",
            "open_terminal",
            "Open terminal pane",
            "Open a terminal pane in the dock or workspace, optionally splitting an existing pane.",
            None,
        ),
        super::s(
            "/tools/workbench/focus_terminal",
            "workbench",
            "focus_terminal",
            "Focus terminal pane",
            "Focus a terminal pane by session, pane, or terminal tab id.",
            None,
        ),
        super::s(
            "/tools/workbench/close_terminal",
            "workbench",
            "close_terminal",
            "Close terminal pane",
            "Close a terminal pane by session, pane, or terminal tab id.",
            None,
        ),
        super::s(
            "/tools/workbench/move_terminal",
            "workbench",
            "move_terminal",
            "Move terminal tab",
            "Move a terminal tab between the dock and workspace.",
            None,
        ),
        super::s(
            "/tools/workbench/extract_tab_text",
            "workbench",
            "extract_tab_text",
            "Extract tab text",
            "Extract paginated text from one workbench tab.",
            Some("workbench_extract_tab_text"),
        ),
    ]
}