// @ts-nocheck
import * as __fd_glob_53 from "../content/docs/developers/uiux-packs.zh-CN.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/developers/uiux-packs.en-US.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/developers/software-capabilities.zh-CN.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/developers/software-capabilities.en-US.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/developers/skills.zh-CN.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/developers/skills.en-US.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/developers/security-errors.zh-CN.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/developers/security-errors.en-US.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/developers/schemas.zh-CN.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/developers/schemas.en-US.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/developers/mcp.zh-CN.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/developers/mcp.en-US.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/developers/language-packs.zh-CN.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/developers/language-packs.en-US.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/developers/index.zh-CN.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/developers/index.en-US.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/developers/compatibility.zh-CN.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/developers/compatibility.en-US.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/developers/cli.zh-CN.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/developers/cli.en-US.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/developers/changelog.zh-CN.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/developers/changelog.en-US.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/workbench.zh-CN.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/workbench.en-US.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/settings-data.zh-CN.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/settings-data.en-US.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/safety.zh-CN.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/safety.en-US.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/releases.zh-CN.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/releases.en-US.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/product-overview.zh-CN.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/product-overview.en-US.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/models-providers.zh-CN.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/models-providers.en-US.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/linux.zh-CN.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/linux.en-US.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/limitations-troubleshooting.zh-CN.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/limitations-troubleshooting.en-US.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/index.zh-CN.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/index.en-US.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/getting-started.zh-CN.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/getting-started.en-US.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/extensions.zh-CN.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/extensions.en-US.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/browser-automation.zh-CN.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/browser-automation.en-US.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/agent-solo.zh-CN.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/agent-solo.en-US.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/agent-oma.zh-CN.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/agent-oma.en-US.mdx?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/developers/meta.zh-CN.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/developers/meta.en-US.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/meta.zh-CN.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.en-US.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.en-US.json": __fd_glob_0, "meta.zh-CN.json": __fd_glob_1, "developers/meta.en-US.json": __fd_glob_2, "developers/meta.zh-CN.json": __fd_glob_3, }, {"agent-oma.en-US.mdx": __fd_glob_4, "agent-oma.zh-CN.mdx": __fd_glob_5, "agent-solo.en-US.mdx": __fd_glob_6, "agent-solo.zh-CN.mdx": __fd_glob_7, "browser-automation.en-US.mdx": __fd_glob_8, "browser-automation.zh-CN.mdx": __fd_glob_9, "extensions.en-US.mdx": __fd_glob_10, "extensions.zh-CN.mdx": __fd_glob_11, "getting-started.en-US.mdx": __fd_glob_12, "getting-started.zh-CN.mdx": __fd_glob_13, "index.en-US.mdx": __fd_glob_14, "index.zh-CN.mdx": __fd_glob_15, "limitations-troubleshooting.en-US.mdx": __fd_glob_16, "limitations-troubleshooting.zh-CN.mdx": __fd_glob_17, "linux.en-US.mdx": __fd_glob_18, "linux.zh-CN.mdx": __fd_glob_19, "models-providers.en-US.mdx": __fd_glob_20, "models-providers.zh-CN.mdx": __fd_glob_21, "product-overview.en-US.mdx": __fd_glob_22, "product-overview.zh-CN.mdx": __fd_glob_23, "releases.en-US.mdx": __fd_glob_24, "releases.zh-CN.mdx": __fd_glob_25, "safety.en-US.mdx": __fd_glob_26, "safety.zh-CN.mdx": __fd_glob_27, "settings-data.en-US.mdx": __fd_glob_28, "settings-data.zh-CN.mdx": __fd_glob_29, "workbench.en-US.mdx": __fd_glob_30, "workbench.zh-CN.mdx": __fd_glob_31, "developers/changelog.en-US.mdx": __fd_glob_32, "developers/changelog.zh-CN.mdx": __fd_glob_33, "developers/cli.en-US.mdx": __fd_glob_34, "developers/cli.zh-CN.mdx": __fd_glob_35, "developers/compatibility.en-US.mdx": __fd_glob_36, "developers/compatibility.zh-CN.mdx": __fd_glob_37, "developers/index.en-US.mdx": __fd_glob_38, "developers/index.zh-CN.mdx": __fd_glob_39, "developers/language-packs.en-US.mdx": __fd_glob_40, "developers/language-packs.zh-CN.mdx": __fd_glob_41, "developers/mcp.en-US.mdx": __fd_glob_42, "developers/mcp.zh-CN.mdx": __fd_glob_43, "developers/schemas.en-US.mdx": __fd_glob_44, "developers/schemas.zh-CN.mdx": __fd_glob_45, "developers/security-errors.en-US.mdx": __fd_glob_46, "developers/security-errors.zh-CN.mdx": __fd_glob_47, "developers/skills.en-US.mdx": __fd_glob_48, "developers/skills.zh-CN.mdx": __fd_glob_49, "developers/software-capabilities.en-US.mdx": __fd_glob_50, "developers/software-capabilities.zh-CN.mdx": __fd_glob_51, "developers/uiux-packs.en-US.mdx": __fd_glob_52, "developers/uiux-packs.zh-CN.mdx": __fd_glob_53, });