// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { LyraAiProviderModelEntry } from "./LyraAiProviderModelEntry";

export type LyraConfigProfileUpsertParams = { id?: string | null, name: string, providerId: string, protocolId: string, presetId?: string | null, connectionConfig: { [key in string]?: string }, authConfig: { [key in string]?: string }, secretValues: { [key in string]?: JsonValue }, clearSecretFields: Array<string>, headers: { [key in string]?: string }, model: string, customModels: Array<LyraAiProviderModelEntry>, };
