// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LyraAiProviderFieldOption } from "./LyraAiProviderFieldOption";

export type LyraAiProviderFieldSchema = { id: string, label: string, kind: string, scope: string, placeholder?: string | null, description?: string | null, required?: boolean | null, secret?: boolean | null, options?: Array<LyraAiProviderFieldOption>, };
