// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LyraPersonaContextParams = { personaName: string, companyName: string, companyDescription: string, coworkerLabel: string, localTime: string, timezone: string, locale: string, locationDisplay: string, locationSource: string, locationConfidence: string, locationDetail: string, physicalLocationDisplay: string, ipLocationDisplay: string, ipAddress?: string | null, deviceName: string, deviceProfile: string, osName: string, osVersion: string, architecture: string, cpuModel: string, cpuCores: string, memoryGb: string, };
