// Copyright 2025-2026 Andrey Vasilevsky <anvanster@gmail.com>
// SPDX-License-Identifier: Apache-2.0

//! Embedded project metadata and build-time provenance.

/// Project author.
pub const AUTHOR: &str = "Andrey Vasilevsky <anvanster@gmail.com>";

/// SPDX license identifier.
pub const LICENSE: &str = "Apache-2.0";

/// Source repository URL.
pub const REPOSITORY: &str = "https://github.com/codegraph-ai/CodeGraph";

/// Package version from Cargo.toml.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Package name from Cargo.toml.
pub const NAME: &str = env!("CARGO_PKG_NAME");

// Build-time provenance generated by build.rs
include!(concat!(env!("OUT_DIR"), "/build_info.rs"));

/// Print a formatted summary of project metadata to stdout.
pub fn print_metadata() {
    println!("{} v{} ({})", NAME, VERSION, GIT_HASH_SHORT);
    println!("Author: {}", AUTHOR);
    println!("License: {}", LICENSE);
    println!("Repository: {}", REPOSITORY);
    println!("Built: {} with {}", BUILD_TIMESTAMP, RUSTC_VERSION);
}

/// Return a formatted summary of project metadata as a `String`.
#[must_use]
pub fn metadata_string() -> String {
    format!(
        "{name} v{version} ({git})\n\
         Author: {author}\n\
         License: {license}\n\
         Repository: {repo}\n\
         Built: {timestamp} with {rustc}",
        name = NAME,
        version = VERSION,
        git = GIT_HASH_SHORT,
        author = AUTHOR,
        license = LICENSE,
        repo = REPOSITORY,
        timestamp = BUILD_TIMESTAMP,
        rustc = RUSTC_VERSION,
    )
}
