import type { AiProviderPreset } from "../../../../shared/ai";
import { apiKeyField, connectionField } from "./shared";

const regionField = () => ({
  id: "region",
  label: "Region",
  kind: "text" as const,
  scope: "connection" as const,
  placeholder: "us-east-1",
  required: true
});

export const agentPresets: readonly AiProviderPreset[] = [
  {
    id: "openrouter",
    providerId: "openrouter",
    protocolId: "openrouter_chat_completions",
    runtimeMetadata: {
      adapterId: "openai_chat_completions",
      compatibilitySource: "provider-compatible",
      nativeToolCalling: true
    },
    label: "OpenRouter",
    description: "OpenRouter hosted model routing.",
    section: "mainstream",
    iconKey: "openrouter",
    defaultModel: "",
    discoveryMode: "dynamic",
    modelDiscoverySupported: true,
    customHeadersSupported: false,
    customModelsSupported: true,
    runtimeSupported: true,
    simpleFields: ["apiKey"],
    connectionFields: [],
    authFields: [apiKeyField()],
    defaultConnectionConfig: { baseUrl: "https://openrouter.ai/api/v1" },
    defaultAuthConfig: {},
    recommendedModels: []
  },
  {
    id: "copilot",
    providerId: "copilot",
    protocolId: "copilot_chat_completions",
    label: "GitHub Copilot",
    description: "Lyra Agent Copilot provider route.",
    section: "mainstream",
    iconKey: "copilot",
    defaultModel: "",
    discoveryMode: "static",
    modelDiscoverySupported: false,
    customHeadersSupported: false,
    customModelsSupported: true,
    runtimeSupported: false,
    simpleFields: ["apiKey"],
    connectionFields: [],
    authFields: [apiKeyField(false, "Copilot bearer token")],
    defaultConnectionConfig: {},
    defaultAuthConfig: {},
    recommendedModels: []
  },
  {
    id: "antigravity",
    providerId: "antigravity",
    protocolId: "antigravity_chat",
    label: "Antigravity",
    description: "Lyra Agent Antigravity provider route.",
    section: "mainstream",
    iconKey: "antigravity",
    defaultModel: "",
    discoveryMode: "static",
    modelDiscoverySupported: false,
    customHeadersSupported: false,
    customModelsSupported: true,
    runtimeSupported: false,
    simpleFields: ["apiKey"],
    connectionFields: [],
    authFields: [apiKeyField(false)],
    defaultConnectionConfig: {},
    defaultAuthConfig: {},
    recommendedModels: []
  },
  {
    id: "cursor",
    providerId: "cursor",
    protocolId: "cursor_chat",
    label: "Cursor",
    description: "Lyra Agent Cursor provider route.",
    section: "mainstream",
    iconKey: "cursor",
    defaultModel: "",
    discoveryMode: "static",
    modelDiscoverySupported: false,
    customHeadersSupported: false,
    customModelsSupported: true,
    runtimeSupported: false,
    simpleFields: ["apiKey"],
    connectionFields: [],
    authFields: [apiKeyField(false)],
    defaultConnectionConfig: {},
    defaultAuthConfig: {},
    recommendedModels: []
  },
  {
    id: "aws_bedrock",
    providerId: "aws_bedrock",
    protocolId: "aws_bedrock_converse",
    label: "AWS Bedrock",
    description: "Lyra Agent Bedrock provider route.",
    section: "mainstream",
    iconKey: "aws_bedrock",
    defaultModel: "",
    discoveryMode: "static",
    modelDiscoverySupported: false,
    customHeadersSupported: false,
    customModelsSupported: true,
    runtimeSupported: false,
    simpleFields: ["region"],
    connectionFields: [regionField()],
    authFields: [],
    defaultConnectionConfig: { region: "us-east-1" },
    defaultAuthConfig: {},
    recommendedModels: []
  }
];
