const EXTENSION_LANGUAGE: Record<string, string> = {
  bash: "shell",
  bat: "bat",
  c: "c",
  cc: "cpp",
  clj: "clojure",
  cpp: "cpp",
  cs: "csharp",
  css: "css",
  cxx: "cpp",
  dart: "dart",
  ex: "elixir",
  exs: "elixir",
  fish: "shell",
  go: "go",
  graphql: "graphql",
  gql: "graphql",
  h: "c",
  hpp: "cpp",
  htm: "html",
  html: "html",
  ini: "ini",
  java: "java",
  js: "javascript",
  json: "json",
  jsonc: "json",
  jsx: "javascript",
  kt: "kotlin",
  kts: "kotlin",
  less: "less",
  lua: "lua",
  md: "markdown",
  mdx: "mdx",
  mjs: "javascript",
  cjs: "javascript",
  php: "php",
  proto: "protobuf",
  ps1: "powershell",
  py: "python",
  r: "r",
  rb: "ruby",
  rs: "rust",
  scss: "scss",
  sh: "shell",
  sol: "solidity",
  sql: "sql",
  svg: "xml",
  swift: "swift",
  toml: "toml",
  ts: "typescript",
  tsx: "typescript",
  mts: "typescript",
  cts: "typescript",
  xml: "xml",
  yaml: "yaml",
  yml: "yaml",
  zsh: "shell",
  astro: "astro",
  prisma: "prisma",
  zig: "zig",
  zon: "zig",
  gleam: "gleam",
  nix: "nix",
  hs: "haskell",
  lhs: "haskell",
  jl: "julia",
  typ: "typst",
  tex: "latex",
  sty: "latex",
  fs: "fsharp",
  fsi: "fsharp",
  fsx: "fsharp",
  tf: "terraform",
  tfvars: "terraform",
  vue: "vue",
  svelte: "svelte",
  wgsl: "wgsl"
};

export const languageFromPath = (filePath: string): string => {
  const base = (filePath.replaceAll("\\", "/").split("/").pop() ?? "").toLowerCase();
  if (base === "dockerfile" || base.startsWith("dockerfile.")) {
    return "dockerfile";
  }
  const dot = base.lastIndexOf(".");
  if (dot <= 0) {
    return "plaintext";
  }
  return EXTENSION_LANGUAGE[base.slice(dot + 1)] ?? "plaintext";
};
