name: Test Other Secret

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: SemVer release version
        default: 0.1.0-preview.1
        required: true
        type: string
      release_tag:
        description: Tag to create
        default: v0.1.0-preview.1
        required: true
        type: string
      sequence:
        description: Sequence
        default: 1
        required: true
        type: number
      publish:
        description: Publish
        default: false
        required: true
        type: boolean
      release_scope:
        description: Scope
        default: local-darwin-x64
        required: true
        type: choice
        options:
          - local-darwin-x64
          - hosted-darwin-x64
          - all-hosted

permissions:
  contents: read

concurrency:
  group: test-other-secret-${{ inputs.release_tag }}
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Other secret test
        env:
          KEY_PEM: ${{ secrets.LYRA_RELEASE_PRIVATE_KEY_PEM }}
        run: echo "key length is ${#KEY_PEM}"