name: Test Secret No If

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: SemVer release version
        default: 0.1.0-preview.1
        required: true
        type: string
      release_tag:
        description: Tag to create
        default: v0.1.0-preview.1
        required: true
        type: string
      sequence:
        description: Sequence
        default: 1
        required: true
        type: number
      publish:
        description: Publish
        default: false
        required: true
        type: boolean
      release_scope:
        description: Scope
        default: local-darwin-x64
        required: true
        type: choice
        options:
          - local-darwin-x64
          - hosted-darwin-x64
          - all-hosted

permissions:
  contents: read

concurrency:
  group: test-secret-no-if-${{ inputs.release_tag }}
  cancel-in-progress: false

jobs:
  publish-draft:
    name: Publish draft binary release
    runs-on: ubuntu-latest
    steps:
      - name: Simple secret test
        env:
          GH_TOKEN: ${{ secrets.LYRA_RELEASES_TOKEN }}
        run: echo "token length is ${#GH_TOKEN}"