name: Test Minimal
on:
  workflow_dispatch:
    inputs:
      test_input:
        description: Test input
        default: hello
        required: false
        type: string
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test ${{ inputs.test_input }}"
